unit UDMCadParametros;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr, LogTypes;

type
  TDMCadParametros = class(TDataModule)
    sdsParametros: TSQLDataSet;
    dspParametros: TDataSetProvider;
    cdsParametros: TClientDataSet;
    dsParametros: TDataSource;
    sdsOperacao_Nota: TSQLDataSet;
    dspOperacao_Nota: TDataSetProvider;
    cdsOperacao_Nota: TClientDataSet;
    cdsOperacao_NotaID: TIntegerField;
    cdsOperacao_NotaNOME: TStringField;
    cdsOperacao_NotaPEDIR_FINALIDADE: TStringField;
    dsOperacao_Nota: TDataSource;
    sdsTipoCobranca: TSQLDataSet;
    dspTipoCobranca: TDataSetProvider;
    cdsTipoCobranca: TClientDataSet;
    cdsTipoCobrancaID: TIntegerField;
    cdsTipoCobrancaNOME: TStringField;
    dsTipoCobranca: TDataSource;
    sdsContas: TSQLDataSet;
    dspContas: TDataSetProvider;
    cdsContas: TClientDataSet;
    cdsContasID: TIntegerField;
    cdsContasNOME: TStringField;
    dsContas: TDataSource;
    sdsFolhaEncargos: TSQLDataSet;
    dspFolhaEncargos: TDataSetProvider;
    cdsFolhaEncargos: TClientDataSet;
    dsFolhaEncargos: TDataSource;
    cdsFolhaEncargosID: TIntegerField;
    cdsFolhaEncargosVALOR_PERC: TFloatField;
    cdsFolhaEncargosSIMPLES: TStringField;
    cdsFolhaEncargosHORISTA: TStringField;
    cdsFolhaEncargosNOME: TStringField;
    sdsCFOP: TSQLDataSet;
    dspCFOP: TDataSetProvider;
    cdsCFOP: TClientDataSet;
    dsCFOP: TDataSource;
    cdsCFOPID: TIntegerField;
    cdsCFOPCODCFOP: TStringField;
    cdsCFOPNOME: TStringField;
    cdsCFOPENTRADASAIDA: TStringField;
    cdsCFOPNOME_INTERNO: TStringField;
    sdsCliente: TSQLDataSet;
    dspCliente: TDataSetProvider;
    cdsCliente: TClientDataSet;
    cdsClienteCODIGO: TIntegerField;
    cdsClienteNOME: TStringField;
    cdsClienteFANTASIA: TStringField;
    dsCliente: TDataSource;
    sdsNCM: TSQLDataSet;
    dspNCM: TDataSetProvider;
    cdsNCM: TClientDataSet;
    dsNCM: TDataSource;
    cdsNCMID: TIntegerField;
    cdsNCMNCM: TStringField;
    cdsNCMNOME: TStringField;
    cdsNCMPERC_RED_STRIB: TFloatField;
    cdsNCMGERAR_ST: TStringField;
    sdsContaOrcamento: TSQLDataSet;
    dspContaOrcamento: TDataSetProvider;
    cdsContaOrcamento: TClientDataSet;
    cdsContaOrcamentoID: TIntegerField;
    cdsContaOrcamentoTIPO: TStringField;
    cdsContaOrcamentoCODIGO: TStringField;
    cdsContaOrcamentoDESCRICAO: TStringField;
    cdsContaOrcamentoNIVEL: TIntegerField;
    cdsContaOrcamentoSUPERIOR: TStringField;
    dsContaOrcamento: TDataSource;
    sdsObs_Lei: TSQLDataSet;
    dspObs_Lei: TDataSetProvider;
    cdsObs_Lei: TClientDataSet;
    dsObs_Lei: TDataSource;
    cdsObs_LeiID: TIntegerField;
    cdsObs_LeiNOME: TStringField;
    cdsObs_LeiOBS: TStringField;
    dsParametros_Mestre: TDataSource;
    sdsParametros_Usuario: TSQLDataSet;
    cdsParametros_Usuario: TClientDataSet;
    dsParametros_Usuario: TDataSource;
    sdsParametros_UsuarioID: TIntegerField;
    sdsParametros_UsuarioTIPO_REG_PRODUTO_PADRAO: TStringField;
    sdsParametros_UsuarioTIPO_CONSULTA_PRODUTO_PADRAO: TStringField;
    sdsUsuarios: TSQLDataSet;
    dspUsuarios: TDataSetProvider;
    cdsUsuarios: TClientDataSet;
    dsUsuarios: TDataSource;
    cdsUsuariosUCLOGIN: TStringField;
    cdsParametros_UsuarioID: TIntegerField;
    cdsParametros_UsuarioTIPO_REG_PRODUTO_PADRAO: TStringField;
    cdsParametros_UsuarioTIPO_CONSULTA_PRODUTO_PADRAO: TStringField;
    sdsParametros_UsuarioUSUARIO: TStringField;
    cdsParametros_UsuarioUSUARIO: TStringField;
    sdsCondPgto: TSQLDataSet;
    dspCondPgto: TDataSetProvider;
    cdsCondPgto: TClientDataSet;
    dsCondPgto: TDataSource;
    cdsCondPgtoID: TIntegerField;
    cdsCondPgtoNOME: TStringField;
    sdsAtelier: TSQLDataSet;
    dspAtelier: TDataSetProvider;
    cdsAtelier: TClientDataSet;
    dsAtelier: TDataSource;
    cdsAtelierCODIGO: TIntegerField;
    cdsAtelierNOME: TStringField;
    cdsAtelierFANTASIA: TStringField;
    sdsParametrosID: TIntegerField;
    sdsParametrosENDXMLNFE: TStringField;
    sdsParametrosENDPDFNFE: TStringField;
    sdsParametrosSERIENORMAL: TStringField;
    sdsParametrosSERIECONTINGENCIA: TStringField;
    sdsParametrosLOCALSERVIDORNFE: TStringField;
    sdsParametrosEMAILRESPONSAVELSISTEMA: TStringField;
    sdsParametrosNFEPRODUCAO: TStringField;
    sdsParametrosANEXARDANFE: TStringField;
    sdsParametrosVERSAONFE: TStringField;
    sdsParametrosVERSAOEMISSAONFE: TStringField;
    sdsParametrosTIPOLOGONFE: TStringField;
    sdsParametrosAPLICARDESCONTONOICMS: TStringField;
    sdsParametrosAPLICARDESCONTONOIPI: TStringField;
    sdsParametrosSOMARNOPROD_FRETE: TStringField;
    sdsParametrosSOMARNOPROD_OUTRASDESP: TStringField;
    sdsParametrosSOMARNOPROD_SEGURO: TStringField;
    sdsParametrosAJUSTELOGONFEAUTOMATICO: TStringField;
    sdsParametrosINFNUMNOTAMANUAL: TStringField;
    sdsParametrosOPCAO_DTENTREGAPEDIDO: TStringField;
    sdsParametrosOBS_SIMPLES: TStringField;
    sdsParametrosIMP_OBSSIMPLES: TStringField;
    sdsParametrosIMP_REFERENCIANANOTA: TStringField;
    sdsParametrosENVIARNOTABENEF_NANFE: TStringField;
    sdsParametrosESPECIE_NOTA: TStringField;
    sdsParametrosMARCA_NOTA: TStringField;
    sdsParametrosVERSAO_BANCO: TIntegerField;
    sdsParametrosUSA_QTDPACOTE_NTE: TStringField;
    sdsParametrosATUALIZAR_PRECO: TStringField;
    sdsParametrosUSA_VENDEDOR: TStringField;
    sdsParametrosUSA_CONSUMO: TStringField;
    sdsParametrosIMP_CODPRODCLI_DANFE: TStringField;
    sdsParametrosUSA_DESCRICAODANOTA: TStringField;
    sdsParametrosID_OPERACAO_BENEF_RET: TIntegerField;
    sdsParametrosID_OPERACAO_MAOOBRA: TIntegerField;
    sdsParametrosCONFECCAO: TStringField;
    sdsParametrosID_OPERACAO_TRIANGULAR: TIntegerField;
    sdsParametrosCADASTRAR_REF_DUP: TStringField;
    sdsParametrosMOSTRAR_NO_CONSUMO: TStringField;
    sdsParametrosUSA_COD_BARRAS: TStringField;
    sdsParametrosUSA_ID_PRODUTO: TStringField;
    sdsParametrosUSA_AGENDA_POR_FUNC: TStringField;
    sdsParametrosEMPRESA_VEICULO: TStringField;
    sdsParametrosID_CONTA_PADRAO: TIntegerField;
    sdsParametrosID_TIPO_COBRANCA_PADRAO: TIntegerField;
    sdsParametrosPERMITE_QTDMAIOR_PEDIDO: TStringField;
    sdsParametrosUSA_TAB_PRECO: TStringField;
    sdsParametrosENDXML_NOTAENTRADA: TStringField;
    sdsParametrosPERMITE_MESMA_OC: TStringField;
    sdsParametrosEMAIL_CONTADOR: TStringField;
    sdsParametrosID_BANCO_REMESSA: TIntegerField;
    sdsParametrosENDXMLNFSE: TStringField;
    sdsParametrosENDPDFNFSE: TStringField;
    sdsParametrosUSA_SERVICO: TStringField;
    sdsParametrosID_CFOP_REQ: TIntegerField;
    sdsParametrosID_CFOP_REQ2: TIntegerField;
    sdsParametrosUSA_PROJETO_OC: TStringField;
    sdsParametrosMOSTRAR_CONSULTA: TStringField;
    sdsParametrosID_CLIENTE_CONSUMIDOR: TIntegerField;
    sdsParametrosIMPRESSORA_FISCAL: TStringField;
    sdsParametrosQUITAR_AVISTA_AUT: TStringField;
    sdsParametrosIMPRESSAO_MATRICIAL: TStringField;
    sdsParametrosEMPRESA_RH: TStringField;
    sdsParametrosIMPRESSORA_CAMINHO: TStringField;
    sdsParametrosGRAVAR_NA_REF_CODPRODFORN: TStringField;
    sdsParametrosGRAVAR_PROD_MAT_RECXML: TStringField;
    sdsParametrosNOTA_ENTRADA_MOSTRAR_PROD: TStringField;
    sdsParametrosATUALIZAR_PRECO_DOC: TStringField;
    sdsParametrosBAIXAR_REQ_AUTOMATICO: TStringField;
    sdsParametrosDESTACAR_IMPOSTO_NOTA: TStringField;
    sdsParametrosCONTROLAR_PEDIDO_LIBERACAO: TStringField;
    sdsParametrosUSA_GRADE: TStringField;
    sdsParametrosTIPO_GRADE_REG: TStringField;
    sdsParametrosINFORMA_MAT_PEDIDO: TStringField;
    sdsParametrosMOSTRAR_NOME_ETIQUETA: TStringField;
    sdsParametrosMOSTRAR_MATERIAL_PED: TStringField;
    sdsParametrosMOSTRAR_CFOP_PEDIDO: TStringField;
    sdsParametrosDIGITACAO_PED_ITENS: TStringField;
    sdsParametrosID_CLIENTE_ESTOQUE: TIntegerField;
    sdsParametrosUSA_LOTE: TStringField;
    sdsParametrosUSA_POSICAO_CONSUMO: TStringField;
    sdsParametrosGRAVAR_INF_ADICIONAIS_NTE: TStringField;
    sdsParametrosUSA_AMOSTRA_GRATIS: TStringField;
    sdsParametrosCALCULAR_PESO_CONSUMO: TStringField;
    sdsParametrosTIPO_REL_PEDIDO: TStringField;
    sdsParametrosUSA_CARIMBO: TStringField;
    sdsParametrosMOSTRAR_MAT_LOTE: TStringField;
    sdsParametrosID_CONTA_FECHAMENTO: TIntegerField;
    sdsParametrosEMPRESA_INJETADO: TStringField;
    sdsParametrosEMPRESA_TRANSPASS: TStringField;
    sdsParametrosUSA_TAMANHO_AGRUPADO_NFE: TStringField;
    sdsParametrosEMPRESA_CARTONAGEM: TStringField;
    sdsParametrosUSA_DTPRODUCAO: TStringField;
    sdsParametrosEMPRESA_NAVALHA: TStringField;
    sdsParametrosIMP_PRECO_PED: TStringField;
    sdsParametrosUSA_NUM_SERIE_PROD: TStringField;
    sdsParametrosPERC_IPI_PADRAO: TFloatField;
    sdsParametrosID_NCM_PADRAO: TIntegerField;
    sdsParametrosUSA_CONTA_ORCAMENTO: TStringField;
    sdsParametrosID_CONTA_ORC_SERVICO: TIntegerField;
    sdsParametrosID_CONTA_ORC_COMISSAO: TIntegerField;
    sdsParametrosTIPO_LEI_TRANSPARENCIA: TStringField;
    sdsParametrosUSA_PRECO_FORN: TStringField;
    sdsParametrosEND_IMPRESSORA_DOS: TStringField;
    sdsParametrosIMP_PESO_PED: TStringField;
    sdsParametrosUSA_EDI: TStringField;
    sdsParametrosID_OPERACAO_VENDA: TIntegerField;
    sdsParametrosUSA_FAIXA_SIMPLES: TStringField;
    sdsParametrosESCOLA: TStringField;
    sdsParametrosALTURA_ETIQ_ROT: TIntegerField;
    sdsParametrosEMPRESA_SUCATA: TStringField;
    sdsParametrosBAIXA_ESTOQUE_MP: TStringField;
    sdsParametrosVERSAO_LEIAUTE_SPED: TIntegerField;
    sdsParametrosIMP_MESANO_REF_NOITEM_NFSE: TStringField;
    sdsParametrosUSA_LIMITE_CREDITO: TStringField;
    sdsParametrosSENHA_CREDITO: TStringField;
    sdsParametrosUSA_SPED: TStringField;
    sdsParametrosTIPO_COMISSAO_NFSE: TStringField;
    sdsParametrosTIPO_COMISSAO_PROD: TStringField;
    sdsParametrosOBS_EXPORTACAO_EXCEL: TMemoField;
    sdsParametrosEND_SALVAR_EXCEL_EXP: TStringField;
    sdsParametrosUSA_PEDIDO_CONTROLE_MOBRA: TStringField;
    sdsParametrosIMP_NFE_REF_PROD: TStringField;
    sdsParametrosID_OBS_LEI_SIMPLES: TIntegerField;
    sdsParametrosPERC_JUROS_PADRAO: TFloatField;
    sdsParametrosUSA_FCI: TStringField;
    sdsParametrosARREDONDAR_5: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_IMP_ITEM: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_TEXTO_ITEM: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_PERC_ADIC: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_SERVICO: TStringField;
    sdsParametrosUSA_VALE: TStringField;
    sdsParametrosSENHA_EXCLUIR_VALE: TStringField;
    sdsParametrosIMP_MEIA_FOLHA_PED: TStringField;
    sdsParametrosUSA_PRODUTO_CLIENTE: TStringField;
    sdsParametrosSOMAR_PIS_COFINS_IMP: TStringField;
    sdsParametrosUSA_CUPOM_FISCAL: TStringField;
    sdsParametrosALERTA_VALE: TStringField;
    sdsParametrosPRODUTO_PRECO_POR_FINALIDADE: TStringField;
    sdsParametrosSENHA_PEDIDO: TStringField;
    sdsParametrosALERTA_VLR_ATRASO: TStringField;
    sdsParametrosID_CONTA_ORC_JUROS_REC: TIntegerField;
    sdsParametrosID_CONTA_ORC_TAXA_BANCARIA_REC: TIntegerField;
    sdsParametrosID_CONTA_ORC_DESPESA_REC: TIntegerField;
    sdsParametrosID_CONTA_ORC_JUROS_PAG: TIntegerField;
    sdsParametrosID_CONTA_ORC_DESPESA_PAG: TIntegerField;
    sdsParametrosTIPO_REL_OC: TStringField;
    sdsParametrosUSA_PERC_MARGEM_RECEPCAO: TStringField;
    sdsParametrosUSA_BOLETO_ACBR: TStringField;
    sdsParametrosUSA_PREVISAO: TStringField;
    sdsParametrosUSA_ENVIO_EMAIL_CATEGORIA: TStringField;
    sdsParametrosUSA_DANFE_FLEXDOCS: TStringField;
    sdsParametrosUSA_DESONERACAO: TStringField;
    sdsParametrosTIPO_REG_PRODUTO_PADRAO: TStringField;
    sdsParametrosTIPO_CONSULTA_PRODUTO_PADRAO: TStringField;
    sdsParametrosABRIR_NFECONFIG: TStringField;
    sdsParametrosCADASTRA_ORGAO_PUBLICO: TStringField;
    sdsParametrosCONTROLAR_NOTIFICACAO: TStringField;
    sdsParametrosUSA_RECIBO_NFSE: TStringField;
    sdsParametrosINFORMAR_COR_MATERIAL: TStringField;
    sdsParametrosNFSE_RETEN_PIS: TStringField;
    sdsParametrosNUMERO_SERIE_INTERNO: TStringField;
    sdsParametrosUSA_PEDIDO_FUT: TStringField;
    sdsParametrosID_OPERACAO_PED_FUT: TIntegerField;
    sdsParametrosUSA_COPIA_OS_NOTA: TStringField;
    sdsParametrosEMPRESA_CONTABIL: TStringField;
    sdsParametrosID_COND_PGTO_NFSE: TIntegerField;
    sdsParametrosIMP_TIPO_TRIBUTOS_ITENS: TStringField;
    sdsParametrosIMP_TIPO_TRIBUTOS: TStringField;
    sdsParametrosIMP_PERC_TRIB_DADOS_ADIC: TStringField;
    sdsParametrosIMP_PERC_TRIB_ITENS: TStringField;
    sdsParametrosIMP_TIPO_TRIBUTOS_SERVICO: TStringField;
    sdsParametrosIMP_PERC_TRIB_SERVICO: TStringField;
    sdsParametrosIMP_NOME_POSICAO: TStringField;
    sdsParametrosPROCURAR_POR_REF_XML: TStringField;
    sdsParametrosQTD_DIG_COD_CLI_CTB: TIntegerField;
    sdsParametrosEMPRESA_AMBIENTES: TStringField;
    sdsParametrosINFORMAR_COR_PROD: TStringField;
    sdsParametrosINV_TRAZER_QTD_ZERADA: TStringField;
    sdsParametrosMOSTRAR_MARCAR_PROD: TStringField;
    sdsParametrosMOSTRAR_LINHA_PROD: TStringField;
    sdsParametrosMOSTRAR_EMBALAGEM: TStringField;
    sdsParametrosCONTROLAR_FAT_SEPARADO: TStringField;
    sdsParametrosCONTROLAR_DUP_PEDIDO: TStringField;
    sdsParametrosID_RESP_SUPORTE: TIntegerField;
    sdsParametrosCONTROLAR_ISSQN_RET: TStringField;
    sdsParametrosOBS_SIMPLES2: TStringField;
    sdsParametrosPERC_COMISSAO_PAGA_NOTA: TFloatField;
    sdsParametrosUSA_SETOR_CONSUMO: TStringField;
    sdsParametrosMOSTRAR_ATELIER_PROD: TStringField;
    sdsParametrosGERAR_TALAO_AUXILIAR: TStringField;
    sdsParametrosTIPO_ESTOQUE: TStringField;
    sdsParametrosUSA_COD_BARRAS_PROPRIO: TStringField;
    sdsParametrosUSA_ETIQUETA_IND: TStringField;
    sdsParametrosCALC_VOLUME_EMB: TStringField;
    sdsParametrosGERAR_ROTULO_EMB: TStringField;
    sdsParametrosUSA_NFCE: TStringField;
    sdsParametrosENDXMLNFCE: TStringField;
    sdsParametrosENDPDFNFCE: TStringField;
    sdsParametrosUSA_ENVIO_NOVO_NFE: TStringField;
    sdsParametrosOPCAO_ESCOLHER_PRECO_COR: TStringField;
    sdsParametrosCONTROLAR_ESTOQUE_SAIDA: TStringField;
    sdsParametrosSENHA_LIBERA_ESTOQUE: TStringField;
    sdsParametrosOPCAO_REL_PED_AGRUPADO: TStringField;
    sdsParametrosGERAR_NUM_AUT_CONTRATO: TStringField;
    sdsParametrosUSA_ANO_CONTRATO: TStringField;
    sdsParametrosUSA_COPIA_PEDIDO_ITEM: TStringField;
    sdsParametrosUSA_COPIA_OS_NFSE: TStringField;
    sdsParametrosUSA_COPIA_PEDIDO: TStringField;
    sdsParametrosSOMAR_SISCOMEX_IMP: TStringField;
    sdsParametrosSOMAR_IPI_IMP: TStringField;
    sdsParametrosSOMAR_II_IMP: TStringField;
    sdsParametrosSOMAR_SEGURO_IMP: TStringField;
    sdsParametrosSOMAR_ADUANEIRA_IMP: TStringField;
    sdsParametrosCONTRATO_CONSUMO: TStringField;
    sdsParametrosUSA_SERVICO_MOTOR: TStringField;
    sdsParametrosCONTROLAR_MENSAL_CSRF: TStringField;
    sdsParametrosGRAVAR_CONSUMO_NOTA: TStringField;
    sdsParametrosID_ATELIER_ADEFINIR: TIntegerField;
    sdsParametrosINFORMAR_COR_MATERIAL_RZ: TStringField;
    sdsParametrosGRAVAR_FINANCEIRO_ATELIER: TStringField;
    sdsParametrosID_CONTA_ORC_ATELIER: TIntegerField;
    sdsParametrosUSA_ICMSOPERACAO_CST51: TStringField;
    cdsParametrosID: TIntegerField;
    cdsParametrosENDXMLNFE: TStringField;
    cdsParametrosENDPDFNFE: TStringField;
    cdsParametrosSERIENORMAL: TStringField;
    cdsParametrosSERIECONTINGENCIA: TStringField;
    cdsParametrosLOCALSERVIDORNFE: TStringField;
    cdsParametrosEMAILRESPONSAVELSISTEMA: TStringField;
    cdsParametrosNFEPRODUCAO: TStringField;
    cdsParametrosANEXARDANFE: TStringField;
    cdsParametrosVERSAONFE: TStringField;
    cdsParametrosVERSAOEMISSAONFE: TStringField;
    cdsParametrosTIPOLOGONFE: TStringField;
    cdsParametrosAPLICARDESCONTONOICMS: TStringField;
    cdsParametrosAPLICARDESCONTONOIPI: TStringField;
    cdsParametrosSOMARNOPROD_FRETE: TStringField;
    cdsParametrosSOMARNOPROD_OUTRASDESP: TStringField;
    cdsParametrosSOMARNOPROD_SEGURO: TStringField;
    cdsParametrosAJUSTELOGONFEAUTOMATICO: TStringField;
    cdsParametrosINFNUMNOTAMANUAL: TStringField;
    cdsParametrosOPCAO_DTENTREGAPEDIDO: TStringField;
    cdsParametrosOBS_SIMPLES: TStringField;
    cdsParametrosIMP_OBSSIMPLES: TStringField;
    cdsParametrosIMP_REFERENCIANANOTA: TStringField;
    cdsParametrosENVIARNOTABENEF_NANFE: TStringField;
    cdsParametrosESPECIE_NOTA: TStringField;
    cdsParametrosMARCA_NOTA: TStringField;
    cdsParametrosVERSAO_BANCO: TIntegerField;
    cdsParametrosUSA_QTDPACOTE_NTE: TStringField;
    cdsParametrosATUALIZAR_PRECO: TStringField;
    cdsParametrosUSA_VENDEDOR: TStringField;
    cdsParametrosUSA_CONSUMO: TStringField;
    cdsParametrosIMP_CODPRODCLI_DANFE: TStringField;
    cdsParametrosUSA_DESCRICAODANOTA: TStringField;
    cdsParametrosID_OPERACAO_BENEF_RET: TIntegerField;
    cdsParametrosID_OPERACAO_MAOOBRA: TIntegerField;
    cdsParametrosCONFECCAO: TStringField;
    cdsParametrosID_OPERACAO_TRIANGULAR: TIntegerField;
    cdsParametrosCADASTRAR_REF_DUP: TStringField;
    cdsParametrosMOSTRAR_NO_CONSUMO: TStringField;
    cdsParametrosUSA_COD_BARRAS: TStringField;
    cdsParametrosUSA_ID_PRODUTO: TStringField;
    cdsParametrosUSA_AGENDA_POR_FUNC: TStringField;
    cdsParametrosEMPRESA_VEICULO: TStringField;
    cdsParametrosID_CONTA_PADRAO: TIntegerField;
    cdsParametrosID_TIPO_COBRANCA_PADRAO: TIntegerField;
    cdsParametrosPERMITE_QTDMAIOR_PEDIDO: TStringField;
    cdsParametrosUSA_TAB_PRECO: TStringField;
    cdsParametrosENDXML_NOTAENTRADA: TStringField;
    cdsParametrosPERMITE_MESMA_OC: TStringField;
    cdsParametrosEMAIL_CONTADOR: TStringField;
    cdsParametrosID_BANCO_REMESSA: TIntegerField;
    cdsParametrosENDXMLNFSE: TStringField;
    cdsParametrosENDPDFNFSE: TStringField;
    cdsParametrosUSA_SERVICO: TStringField;
    cdsParametrosID_CFOP_REQ: TIntegerField;
    cdsParametrosID_CFOP_REQ2: TIntegerField;
    cdsParametrosUSA_PROJETO_OC: TStringField;
    cdsParametrosMOSTRAR_CONSULTA: TStringField;
    cdsParametrosID_CLIENTE_CONSUMIDOR: TIntegerField;
    cdsParametrosIMPRESSORA_FISCAL: TStringField;
    cdsParametrosQUITAR_AVISTA_AUT: TStringField;
    cdsParametrosIMPRESSAO_MATRICIAL: TStringField;
    cdsParametrosEMPRESA_RH: TStringField;
    cdsParametrosIMPRESSORA_CAMINHO: TStringField;
    cdsParametrosGRAVAR_NA_REF_CODPRODFORN: TStringField;
    cdsParametrosGRAVAR_PROD_MAT_RECXML: TStringField;
    cdsParametrosNOTA_ENTRADA_MOSTRAR_PROD: TStringField;
    cdsParametrosATUALIZAR_PRECO_DOC: TStringField;
    cdsParametrosBAIXAR_REQ_AUTOMATICO: TStringField;
    cdsParametrosDESTACAR_IMPOSTO_NOTA: TStringField;
    cdsParametrosCONTROLAR_PEDIDO_LIBERACAO: TStringField;
    cdsParametrosUSA_GRADE: TStringField;
    cdsParametrosTIPO_GRADE_REG: TStringField;
    cdsParametrosINFORMA_MAT_PEDIDO: TStringField;
    cdsParametrosMOSTRAR_NOME_ETIQUETA: TStringField;
    cdsParametrosMOSTRAR_MATERIAL_PED: TStringField;
    cdsParametrosMOSTRAR_CFOP_PEDIDO: TStringField;
    cdsParametrosDIGITACAO_PED_ITENS: TStringField;
    cdsParametrosID_CLIENTE_ESTOQUE: TIntegerField;
    cdsParametrosUSA_LOTE: TStringField;
    cdsParametrosUSA_POSICAO_CONSUMO: TStringField;
    cdsParametrosGRAVAR_INF_ADICIONAIS_NTE: TStringField;
    cdsParametrosUSA_AMOSTRA_GRATIS: TStringField;
    cdsParametrosCALCULAR_PESO_CONSUMO: TStringField;
    cdsParametrosTIPO_REL_PEDIDO: TStringField;
    cdsParametrosUSA_CARIMBO: TStringField;
    cdsParametrosMOSTRAR_MAT_LOTE: TStringField;
    cdsParametrosID_CONTA_FECHAMENTO: TIntegerField;
    cdsParametrosEMPRESA_INJETADO: TStringField;
    cdsParametrosEMPRESA_TRANSPASS: TStringField;
    cdsParametrosUSA_TAMANHO_AGRUPADO_NFE: TStringField;
    cdsParametrosEMPRESA_CARTONAGEM: TStringField;
    cdsParametrosUSA_DTPRODUCAO: TStringField;
    cdsParametrosEMPRESA_NAVALHA: TStringField;
    cdsParametrosIMP_PRECO_PED: TStringField;
    cdsParametrosUSA_NUM_SERIE_PROD: TStringField;
    cdsParametrosPERC_IPI_PADRAO: TFloatField;
    cdsParametrosID_NCM_PADRAO: TIntegerField;
    cdsParametrosUSA_CONTA_ORCAMENTO: TStringField;
    cdsParametrosID_CONTA_ORC_SERVICO: TIntegerField;
    cdsParametrosID_CONTA_ORC_COMISSAO: TIntegerField;
    cdsParametrosTIPO_LEI_TRANSPARENCIA: TStringField;
    cdsParametrosUSA_PRECO_FORN: TStringField;
    cdsParametrosEND_IMPRESSORA_DOS: TStringField;
    cdsParametrosIMP_PESO_PED: TStringField;
    cdsParametrosUSA_EDI: TStringField;
    cdsParametrosID_OPERACAO_VENDA: TIntegerField;
    cdsParametrosUSA_FAIXA_SIMPLES: TStringField;
    cdsParametrosESCOLA: TStringField;
    cdsParametrosALTURA_ETIQ_ROT: TIntegerField;
    cdsParametrosEMPRESA_SUCATA: TStringField;
    cdsParametrosBAIXA_ESTOQUE_MP: TStringField;
    cdsParametrosVERSAO_LEIAUTE_SPED: TIntegerField;
    cdsParametrosIMP_MESANO_REF_NOITEM_NFSE: TStringField;
    cdsParametrosUSA_LIMITE_CREDITO: TStringField;
    cdsParametrosSENHA_CREDITO: TStringField;
    cdsParametrosUSA_SPED: TStringField;
    cdsParametrosTIPO_COMISSAO_NFSE: TStringField;
    cdsParametrosTIPO_COMISSAO_PROD: TStringField;
    cdsParametrosOBS_EXPORTACAO_EXCEL: TMemoField;
    cdsParametrosEND_SALVAR_EXCEL_EXP: TStringField;
    cdsParametrosUSA_PEDIDO_CONTROLE_MOBRA: TStringField;
    cdsParametrosIMP_NFE_REF_PROD: TStringField;
    cdsParametrosID_OBS_LEI_SIMPLES: TIntegerField;
    cdsParametrosPERC_JUROS_PADRAO: TFloatField;
    cdsParametrosUSA_FCI: TStringField;
    cdsParametrosARREDONDAR_5: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_IMP_ITEM: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_TEXTO_ITEM: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_PERC_ADIC: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_SERVICO: TStringField;
    cdsParametrosUSA_VALE: TStringField;
    cdsParametrosSENHA_EXCLUIR_VALE: TStringField;
    cdsParametrosIMP_MEIA_FOLHA_PED: TStringField;
    cdsParametrosUSA_PRODUTO_CLIENTE: TStringField;
    cdsParametrosSOMAR_PIS_COFINS_IMP: TStringField;
    cdsParametrosUSA_CUPOM_FISCAL: TStringField;
    cdsParametrosALERTA_VALE: TStringField;
    cdsParametrosPRODUTO_PRECO_POR_FINALIDADE: TStringField;
    cdsParametrosSENHA_PEDIDO: TStringField;
    cdsParametrosALERTA_VLR_ATRASO: TStringField;
    cdsParametrosID_CONTA_ORC_JUROS_REC: TIntegerField;
    cdsParametrosID_CONTA_ORC_TAXA_BANCARIA_REC: TIntegerField;
    cdsParametrosID_CONTA_ORC_DESPESA_REC: TIntegerField;
    cdsParametrosID_CONTA_ORC_JUROS_PAG: TIntegerField;
    cdsParametrosID_CONTA_ORC_DESPESA_PAG: TIntegerField;
    cdsParametrosTIPO_REL_OC: TStringField;
    cdsParametrosUSA_PERC_MARGEM_RECEPCAO: TStringField;
    cdsParametrosUSA_BOLETO_ACBR: TStringField;
    cdsParametrosUSA_PREVISAO: TStringField;
    cdsParametrosUSA_ENVIO_EMAIL_CATEGORIA: TStringField;
    cdsParametrosUSA_DANFE_FLEXDOCS: TStringField;
    cdsParametrosUSA_DESONERACAO: TStringField;
    cdsParametrosTIPO_REG_PRODUTO_PADRAO: TStringField;
    cdsParametrosTIPO_CONSULTA_PRODUTO_PADRAO: TStringField;
    cdsParametrosABRIR_NFECONFIG: TStringField;
    cdsParametrosCADASTRA_ORGAO_PUBLICO: TStringField;
    cdsParametrosCONTROLAR_NOTIFICACAO: TStringField;
    cdsParametrosUSA_RECIBO_NFSE: TStringField;
    cdsParametrosINFORMAR_COR_MATERIAL: TStringField;
    cdsParametrosNFSE_RETEN_PIS: TStringField;
    cdsParametrosNUMERO_SERIE_INTERNO: TStringField;
    cdsParametrosUSA_PEDIDO_FUT: TStringField;
    cdsParametrosID_OPERACAO_PED_FUT: TIntegerField;
    cdsParametrosUSA_COPIA_OS_NOTA: TStringField;
    cdsParametrosEMPRESA_CONTABIL: TStringField;
    cdsParametrosID_COND_PGTO_NFSE: TIntegerField;
    cdsParametrosIMP_TIPO_TRIBUTOS_ITENS: TStringField;
    cdsParametrosIMP_TIPO_TRIBUTOS: TStringField;
    cdsParametrosIMP_PERC_TRIB_DADOS_ADIC: TStringField;
    cdsParametrosIMP_PERC_TRIB_ITENS: TStringField;
    cdsParametrosIMP_TIPO_TRIBUTOS_SERVICO: TStringField;
    cdsParametrosIMP_PERC_TRIB_SERVICO: TStringField;
    cdsParametrosIMP_NOME_POSICAO: TStringField;
    cdsParametrosPROCURAR_POR_REF_XML: TStringField;
    cdsParametrosQTD_DIG_COD_CLI_CTB: TIntegerField;
    cdsParametrosEMPRESA_AMBIENTES: TStringField;
    cdsParametrosINFORMAR_COR_PROD: TStringField;
    cdsParametrosINV_TRAZER_QTD_ZERADA: TStringField;
    cdsParametrosMOSTRAR_MARCAR_PROD: TStringField;
    cdsParametrosMOSTRAR_LINHA_PROD: TStringField;
    cdsParametrosMOSTRAR_EMBALAGEM: TStringField;
    cdsParametrosCONTROLAR_FAT_SEPARADO: TStringField;
    cdsParametrosCONTROLAR_DUP_PEDIDO: TStringField;
    cdsParametrosID_RESP_SUPORTE: TIntegerField;
    cdsParametrosCONTROLAR_ISSQN_RET: TStringField;
    cdsParametrosOBS_SIMPLES2: TStringField;
    cdsParametrosPERC_COMISSAO_PAGA_NOTA: TFloatField;
    cdsParametrosUSA_SETOR_CONSUMO: TStringField;
    cdsParametrosMOSTRAR_ATELIER_PROD: TStringField;
    cdsParametrosGERAR_TALAO_AUXILIAR: TStringField;
    cdsParametrosTIPO_ESTOQUE: TStringField;
    cdsParametrosUSA_COD_BARRAS_PROPRIO: TStringField;
    cdsParametrosUSA_ETIQUETA_IND: TStringField;
    cdsParametrosCALC_VOLUME_EMB: TStringField;
    cdsParametrosGERAR_ROTULO_EMB: TStringField;
    cdsParametrosUSA_NFCE: TStringField;
    cdsParametrosENDXMLNFCE: TStringField;
    cdsParametrosENDPDFNFCE: TStringField;
    cdsParametrosUSA_ENVIO_NOVO_NFE: TStringField;
    cdsParametrosOPCAO_ESCOLHER_PRECO_COR: TStringField;
    cdsParametrosCONTROLAR_ESTOQUE_SAIDA: TStringField;
    cdsParametrosSENHA_LIBERA_ESTOQUE: TStringField;
    cdsParametrosOPCAO_REL_PED_AGRUPADO: TStringField;
    cdsParametrosGERAR_NUM_AUT_CONTRATO: TStringField;
    cdsParametrosUSA_ANO_CONTRATO: TStringField;
    cdsParametrosUSA_COPIA_PEDIDO_ITEM: TStringField;
    cdsParametrosUSA_COPIA_OS_NFSE: TStringField;
    cdsParametrosUSA_COPIA_PEDIDO: TStringField;
    cdsParametrosSOMAR_SISCOMEX_IMP: TStringField;
    cdsParametrosSOMAR_IPI_IMP: TStringField;
    cdsParametrosSOMAR_II_IMP: TStringField;
    cdsParametrosSOMAR_SEGURO_IMP: TStringField;
    cdsParametrosSOMAR_ADUANEIRA_IMP: TStringField;
    cdsParametrosCONTRATO_CONSUMO: TStringField;
    cdsParametrosUSA_SERVICO_MOTOR: TStringField;
    cdsParametrosCONTROLAR_MENSAL_CSRF: TStringField;
    cdsParametrosGRAVAR_CONSUMO_NOTA: TStringField;
    cdsParametrosID_ATELIER_ADEFINIR: TIntegerField;
    cdsParametrosINFORMAR_COR_MATERIAL_RZ: TStringField;
    cdsParametrosGRAVAR_FINANCEIRO_ATELIER: TStringField;
    cdsParametrosID_CONTA_ORC_ATELIER: TIntegerField;
    cdsParametrosUSA_ICMSOPERACAO_CST51: TStringField;
    cdsParametrossdsParametros_Usuario: TDataSetField;
    sdsParametrosUSA_PRODUTO_FORNECEDOR: TStringField;
    sdsParametrosUSA_PRODUTO_LOCALIZACAO: TStringField;
    cdsParametrosUSA_PRODUTO_FORNECEDOR: TStringField;
    cdsParametrosUSA_PRODUTO_LOCALIZACAO: TStringField;
    sdsParametrosMOSTRAR_TOTAL_ACUMULADO_DUP: TStringField;
    cdsParametrosMOSTRAR_TOTAL_ACUMULADO_DUP: TStringField;
    sdsParametrosID_CONTA_ORC_DESCONTADA: TIntegerField;
    cdsParametrosID_CONTA_ORC_DESCONTADA: TIntegerField;
    sdsParametrosREPETIR_ULTIMO_ITEM_PED: TStringField;
    cdsParametrosREPETIR_ULTIMO_ITEM_PED: TStringField;
    sdsParametrosUNIDADE_PECA: TStringField;
    cdsParametrosUNIDADE_PECA: TStringField;
    sdsUnidade: TSQLDataSet;
    dspUnidade: TDataSetProvider;
    cdsUnidade: TClientDataSet;
    dsUnidade: TDataSource;
    cdsUnidadeUNIDADE: TStringField;
    cdsUnidadeCONVERSOR: TFloatField;
    cdsUnidadeNOME: TStringField;
    sdsParametrosDECISAO: TStringField;
    cdsParametrosDECISAO: TStringField;
    sdsParametrosEMPRESA_LIVRARIA: TStringField;
    cdsParametrosEMPRESA_LIVRARIA: TStringField;
    sdsParametrosUSA_LOCAL_ESTOQUE: TStringField;
    cdsParametrosUSA_LOCAL_ESTOQUE: TStringField;
    sdsParametrosFUSOHORARIO: TStringField;
    sdsParametrosFUSOHORARIO_VERAO: TStringField;
    cdsParametrosFUSOHORARIO: TStringField;
    cdsParametrosFUSOHORARIO_VERAO: TStringField;
    sdsParametrosUSA_APROVACAO_PED: TStringField;
    cdsParametrosUSA_APROVACAO_PED: TStringField;
    sdsParametrosUSA_ROTULO2: TStringField;
    cdsParametrosUSA_ROTULO2: TStringField;
    sdsParametrosUSA_LOTE_CONTROLE: TStringField;
    cdsParametrosUSA_LOTE_CONTROLE: TStringField;
    sdsParametrosUSA_PERC_ORGAO_PUBLICO: TStringField;
    sdsParametrosUSA_PERC_ORGAO_PUBLICO_IMP: TStringField;
    cdsParametrosUSA_PERC_ORGAO_PUBLICO: TStringField;
    cdsParametrosUSA_PERC_ORGAO_PUBLICO_IMP: TStringField;
    sdsParametrosUSA_APROVACAO_OC_FORN: TStringField;
    cdsParametrosUSA_APROVACAO_OC_FORN: TStringField;
    sdsLocal_Estoque: TSQLDataSet;
    dspLocal_Estoque: TDataSetProvider;
    cdsLocal_Estoque: TClientDataSet;
    dsLocal_Estoque: TDataSource;
    cdsLocal_EstoqueID: TIntegerField;
    cdsLocal_EstoqueCOD_LOCAL: TIntegerField;
    cdsLocal_EstoqueNOME: TStringField;
    cdsLocal_EstoquePRINCIPAL: TStringField;
    cdsLocal_EstoqueINATIVO: TStringField;
    sdsParametrosID_LOCAL_ESTOQUE_NTE: TIntegerField;
    cdsParametrosID_LOCAL_ESTOQUE_NTE: TIntegerField;
    sdsParametrosUSA_ADIANTAMENTO_PEDIDO: TStringField;
    cdsParametrosUSA_ADIANTAMENTO_PEDIDO: TStringField;
    sdsParametros_UsuarioMOSTRAR_CODIGO_PROD_ANT: TStringField;
    cdsParametros_UsuarioMOSTRAR_CODIGO_PROD_ANT: TStringField;
    sdsParametrosID_CONTA_PADRAO_ADI: TIntegerField;
    sdsParametrosID_TIPO_COBRANCA_PADRAO_ADI: TIntegerField;
    cdsParametrosID_CONTA_PADRAO_ADI: TIntegerField;
    cdsParametrosID_TIPO_COBRANCA_PADRAO_ADI: TIntegerField;
    sdsParametros_UsuarioMOSTRAR_TOTAL_PEDIDO: TStringField;
    cdsParametros_UsuarioMOSTRAR_TOTAL_PEDIDO: TStringField;
    sdsParametrosSOMAR_BASE_ICMS_SISCOMEX: TStringField;
    cdsParametrosSOMAR_BASE_ICMS_SISCOMEX: TStringField;
    sdsParametrosCONTROLAR_SERIE_OPERACAO: TStringField;
    cdsParametrosCONTROLAR_SERIE_OPERACAO: TStringField;
    sdsParametrosMOSTRAR_END_ENTREGA_DADOS_ADI: TStringField;
    cdsParametrosMOSTRAR_END_ENTREGA_DADOS_ADI: TStringField;
    sdsParametrosMSG_PADRAO_NOTA: TMemoField;
    cdsParametrosMSG_PADRAO_NOTA: TMemoField;
    sdsParametrosALERTA_FRETE_DEST: TStringField;
    cdsParametrosALERTA_FRETE_DEST: TStringField;
    sdsParametrosUSA_OBS_PEDIDO_NOTA: TStringField;
    cdsParametrosUSA_OBS_PEDIDO_NOTA: TStringField;
    sdsParametrosID_LOCAL_ESTOQUE_PROD: TIntegerField;
    cdsParametrosID_LOCAL_ESTOQUE_PROD: TIntegerField;
    sdsParametros_Fin: TSQLDataSet;
    cdsParametros_Fin: TClientDataSet;
    dsParametros_Fin: TDataSource;
    sdsParametros_FinID: TIntegerField;
    sdsParametros_FinCONTROLAR_DUP_USUARIO: TStringField;
    cdsParametrossdsParametros_Fin: TDataSetField;
    cdsParametros_FinID: TIntegerField;
    cdsParametros_FinCONTROLAR_DUP_USUARIO: TStringField;
    sdsParametros_UsuarioMOSTRAR_DUP_REC_PAG: TStringField;
    cdsParametros_UsuarioMOSTRAR_DUP_REC_PAG: TStringField;
    sdsParametros_Ped: TSQLDataSet;
    cdsParametros_Ped: TClientDataSet;
    dsParametros_Ped: TDataSource;
    sdsParametros_PedID: TIntegerField;
    sdsParametros_PedFATURAR_PED_INTEGRAL: TStringField;
    sdsParametros_PedUSA_DTEXPEDICAO: TStringField;
    sdsParametros_PedIMP_REF_COD_PEDIDO: TStringField;
    cdsParametrossdsParametros_Ped: TDataSetField;
    cdsParametros_PedID: TIntegerField;
    cdsParametros_PedFATURAR_PED_INTEGRAL: TStringField;
    cdsParametros_PedUSA_DTEXPEDICAO: TStringField;
    cdsParametros_PedIMP_REF_COD_PEDIDO: TStringField;
    sdsParametros_FinUSA_METAS_VENDEDOR: TStringField;
    cdsParametros_FinUSA_METAS_VENDEDOR: TStringField;
    sdsParametros_Geral: TSQLDataSet;
    cdsParametros_Geral: TClientDataSet;
    dsParametros_Geral: TDataSource;
    sdsParametros_GeralID: TIntegerField;
    sdsParametros_GeralENDGRIDS: TStringField;
    cdsParametrossdsParametros_Geral: TDataSetField;
    cdsParametros_GeralID: TIntegerField;
    cdsParametros_GeralENDGRIDS: TStringField;
    sdsParametros_FinUSA_LIMITE_COMPRAS: TStringField;
    cdsParametros_FinUSA_LIMITE_COMPRAS: TStringField;
    sdsParametros_FinMOSTRAR_VLR_ROD_DUP: TStringField;
    cdsParametros_FinMOSTRAR_VLR_ROD_DUP: TStringField;
    sdsParametros_Est: TSQLDataSet;
    cdsParametros_Est: TClientDataSet;
    dsParametros_Est: TDataSource;
    sdsParametros_EstID: TIntegerField;
    sdsParametros_EstUSA_RESERVA: TStringField;
    cdsParametrossdsParametros_Est: TDataSetField;
    cdsParametros_EstID: TIntegerField;
    cdsParametros_EstUSA_RESERVA: TStringField;
    sdsParametros_Com: TSQLDataSet;
    cdsParametros_Com: TClientDataSet;
    dsParametros_Com: TDataSource;
    sdsParametros_ComID: TIntegerField;
    sdsParametros_ComCOMISSAO_DESCONTAR: TStringField;
    cdsParametrossdsParametros_Com: TDataSetField;
    cdsParametros_ComID: TIntegerField;
    cdsParametros_ComCOMISSAO_DESCONTAR: TStringField;
    sdsParametros_Imp: TSQLDataSet;
    cdsParametros_Imp: TClientDataSet;
    dsParametros_Imp: TDataSource;
    sdsParametros_ImpID: TIntegerField;
    sdsParametros_ImpSOMAR_VLR_II_NO_IPI: TStringField;
    cdsParametrossdsParametros_Imp: TDataSetField;
    cdsParametros_ImpID: TIntegerField;
    cdsParametros_ImpSOMAR_VLR_II_NO_IPI: TStringField;
    sdsParametros_Ser: TSQLDataSet;
    cdsParametros_Ser: TClientDataSet;
    dsParametros_Ser: TDataSource;
    sdsParametros_SerID: TIntegerField;
    sdsParametros_SerIMP_NA_OS_REF_PROD: TStringField;
    cdsParametrossdsParametros_Ser: TDataSetField;
    cdsParametros_SerID: TIntegerField;
    cdsParametros_SerIMP_NA_OS_REF_PROD: TStringField;
    sdsParametros_NFe: TSQLDataSet;
    cdsParametros_NFe: TClientDataSet;
    dsParametros_NFe: TDataSource;
    sdsParametros_NFeID: TIntegerField;
    sdsParametros_NFeSOMAR_IPI_NO_ICMS: TStringField;
    cdsParametrossdsParametros_NFe: TDataSetField;
    cdsParametros_NFeID: TIntegerField;
    cdsParametros_NFeSOMAR_IPI_NO_ICMS: TStringField;
    sdsParametros_Cta_Orc: TSQLDataSet;
    cdsParametros_Cta_Orc: TClientDataSet;
    dsParametros_Cta_Orc: TDataSource;
    sdsParametros_Cta_OrcID: TIntegerField;
    sdsParametros_Cta_OrcID_CONTA_ORC_RECEITA: TIntegerField;
    sdsParametros_Cta_OrcID_CONTA_ORC_DESPESA: TIntegerField;
    cdsParametrossdsParametros_Cta_Orc: TDataSetField;
    cdsParametros_Cta_OrcID: TIntegerField;
    cdsParametros_Cta_OrcID_CONTA_ORC_RECEITA: TIntegerField;
    cdsParametros_Cta_OrcID_CONTA_ORC_DESPESA: TIntegerField;
    sdsParametros_SerAGRUPA_CONTRATO_NFSE: TStringField;
    cdsParametros_SerAGRUPA_CONTRATO_NFSE: TStringField;
    sdsParametros_SerUSA_AJUSTE_PRECO: TStringField;
    cdsParametros_SerUSA_AJUSTE_PRECO: TStringField;
    sdsParametros_ComPAGAR_SOMENTE_PRIMEIRA: TStringField;
    cdsParametros_ComPAGAR_SOMENTE_PRIMEIRA: TStringField;
    sdsParametros_GeralUSA_PONTOS_LOCACAO: TStringField;
    cdsParametros_GeralUSA_PONTOS_LOCACAO: TStringField;
    sdsParametros_PedUSA_NUM_PEDIDO_POR_FILIAL: TStringField;
    cdsParametros_PedUSA_NUM_PEDIDO_POR_FILIAL: TStringField;
    sdsParametros_FinMOSTRAR_ULT_REMESSA: TStringField;
    cdsParametros_FinMOSTRAR_ULT_REMESSA: TStringField;
    sdsParametros_GeralMOSTRAR_DADOS_PESSOA_FISICA: TStringField;
    cdsParametros_GeralMOSTRAR_DADOS_PESSOA_FISICA: TStringField;
    sdsParametros_FinDTENVIO_EMAIL_TITULOS: TDateField;
    cdsParametros_FinDTENVIO_EMAIL_TITULOS: TDateField;
    sdsParametros_FinENVIAR_EMAIL_TITULOS_ATR: TStringField;
    cdsParametros_FinENVIAR_EMAIL_TITULOS_ATR: TStringField;
    sdsParametros_EstGERAR_LOTE_AUT: TStringField;
    cdsParametros_EstGERAR_LOTE_AUT: TStringField;
    sdsParametros_NFeOBS_EMAIL_NFE: TMemoField;
    cdsParametros_NFeOBS_EMAIL_NFE: TMemoField;
    sdsParametros_FinCONTROLAR_BANCO_REM_DEP: TStringField;
    cdsParametros_FinCONTROLAR_BANCO_REM_DEP: TStringField;
    sdsParametros_UsuarioALT_ESTOQUE_MOV: TStringField;
    cdsParametros_UsuarioALT_ESTOQUE_MOV: TStringField;
    sdsParametros_PedCONTROLAR_FILIAL_NA_COPIA_NOTA: TStringField;
    cdsParametros_PedCONTROLAR_FILIAL_NA_COPIA_NOTA: TStringField;
    sdsParametros_PedID_CONDPGTO_PRIMEIRO_PED: TIntegerField;
    cdsParametros_PedID_CONDPGTO_PRIMEIRO_PED: TIntegerField;
    cdsParametros_Prod: TClientDataSet;
    dsParametros_Prod: TDataSource;
    sdsParametros_ProdID: TIntegerField;
    sdsParametros_ProdGERAR_COD_BARRA_INT: TStringField;
    cdsParametrossdsParametros_Prod: TDataSetField;
    cdsParametros_ProdID: TIntegerField;
    cdsParametros_ProdGERAR_COD_BARRA_INT: TStringField;
    sdsParametros_SerTIPO_COBRANCA_NFSE: TStringField;
    cdsParametros_SerTIPO_COBRANCA_NFSE: TStringField;
    sdsParametros_GeralLIBERAR_DIG_DTCADASTRO: TStringField;
    cdsParametros_GeralLIBERAR_DIG_DTCADASTRO: TStringField;
    sdsParametros_FinSEPARADOR_NUM_DA_PARC: TStringField;
    cdsParametros_FinSEPARADOR_NUM_DA_PARC: TStringField;
    sdsParametros_NFeSOMAR_IPI_NO_ICM_TC: TStringField;
    cdsParametros_NFeSOMAR_IPI_NO_ICM_TC: TStringField;
    sdsParametros_PedUSA_PROCESSO: TStringField;
    cdsParametros_PedUSA_PROCESSO: TStringField;
    sdsParametros_NFeIMP_COMBINACAO_NFE: TStringField;
    cdsParametros_NFeIMP_COMBINACAO_NFE: TStringField;
    sdsParametros_PedCONTROLAR_ROT_IMPRESSO: TStringField;
    cdsParametros_PedCONTROLAR_ROT_IMPRESSO: TStringField;
    sdsParametros_SerGERAR_DUPLICATA_CONTRATO: TStringField;
    cdsParametros_SerGERAR_DUPLICATA_CONTRATO: TStringField;
    sdsParametros_OC: TSQLDataSet;
    cdsParametros_OC: TClientDataSet;
    dsParametros_OC: TDataSource;
    sdsParametros_OCID: TIntegerField;
    sdsParametros_OCOBS_OC: TMemoField;
    cdsParametrossdsParametros_OC: TDataSetField;
    cdsParametros_OCID: TIntegerField;
    cdsParametros_OCOBS_OC: TMemoField;
    sdsParametros_NFeIMP_RODAPE_DANFE_CLI: TStringField;
    cdsParametros_NFeIMP_RODAPE_DANFE_CLI: TStringField;
    sdsParametros_NFeUSA_OPCAO_IMP_COD_CLI: TStringField;
    cdsParametros_NFeUSA_OPCAO_IMP_COD_CLI: TStringField;
    sdsParametros_PedEXIGIR_NUM_PED_CLIENTE: TStringField;
    cdsParametros_PedEXIGIR_NUM_PED_CLIENTE: TStringField;
    sdsParametros_SerUSA_OS_REDUZIDA: TStringField;
    cdsParametros_SerUSA_OS_REDUZIDA: TStringField;
    sdsParametros_PedCONTROLAR_VLR_ENTRADA: TStringField;
    cdsParametros_PedCONTROLAR_VLR_ENTRADA: TStringField;
    sdsParametros_NFeIMP_END_COBRANCA: TStringField;
    cdsParametros_NFeIMP_END_COBRANCA: TStringField;
    sdsParametros_NFeGRAVAR_TAB_TAMANHO: TStringField;
    cdsParametros_NFeGRAVAR_TAB_TAMANHO: TStringField;
    sdsParametros_NFeUSA_SEL_PEDIDO_TAM: TStringField;
    cdsParametros_NFeUSA_SEL_PEDIDO_TAM: TStringField;
    sdsParametros_PedMOSTRAR_TERCEIRO: TStringField;
    cdsParametros_PedMOSTRAR_TERCEIRO: TStringField;
    sdsParametros_GeralUSAR_PESSOA_FILIAL: TStringField;
    cdsParametros_GeralUSAR_PESSOA_FILIAL: TStringField;
    sdsParametros_ProdUSA_PRODUTO_FILIAL: TStringField;
    cdsParametros_ProdUSA_PRODUTO_FILIAL: TStringField;
    sdsParametros_ImpSOMAR_FRETE_ICMS: TStringField;
    cdsParametros_ImpSOMAR_FRETE_ICMS: TStringField;
    sdsParametros_ProdSENHA_ALT_PROD_MOV: TStringField;
    cdsParametros_ProdSENHA_ALT_PROD_MOV: TStringField;
    sdsParametros_OCUSAR_GERAR_COBRANCA: TStringField;
    cdsParametros_OCUSAR_GERAR_COBRANCA: TStringField;
    sdsParametros_ProdMOSTRAR_OBS_CONSULTA: TStringField;
    cdsParametros_ProdMOSTRAR_OBS_CONSULTA: TStringField;
    sdsParametros_EstID_LOCAL_ESTOQUE_SEMI: TIntegerField;
    sdsParametros_EstID_LOCAL_ESTOQUE_MAT: TIntegerField;
    sdsParametros_EstID_LOCAL_ESTOQUE_MAT_CONS: TIntegerField;
    cdsParametros_EstID_LOCAL_ESTOQUE_SEMI: TIntegerField;
    cdsParametros_EstID_LOCAL_ESTOQUE_MAT: TIntegerField;
    cdsParametros_EstID_LOCAL_ESTOQUE_MAT_CONS: TIntegerField;
    sdsParametros_SerMOSTRAR_SERIE_TROCA: TStringField;
    cdsParametros_SerMOSTRAR_SERIE_TROCA: TStringField;
    sdsParametros_SerIMP_CONTRATO_NFSE: TStringField;
    cdsParametros_SerIMP_CONTRATO_NFSE: TStringField;
    sdsParametros_PedIMP_IPI_DEPOIS_VLR: TStringField;
    cdsParametros_PedIMP_IPI_DEPOIS_VLR: TStringField;
    sdsParametros_GeralMOSTRAR_COD_CONTABIL: TStringField;
    cdsParametros_GeralMOSTRAR_COD_CONTABIL: TStringField;
    sdsParametros_GeralEND_ARQ_INT_CONTABIL: TStringField;
    cdsParametros_GeralEND_ARQ_INT_CONTABIL: TStringField;
    sdsParametros_GeralUSA_TIPO_CONTR_VARIACAO: TStringField;
    cdsParametros_GeralUSA_TIPO_CONTR_VARIACAO: TStringField;
    sdsParametros_Prod: TSQLDataSet;
    sdsParametros_ProdMARCAR_BAIXAR_ESTOQUE_MAT: TStringField;
    cdsParametros_ProdMARCAR_BAIXAR_ESTOQUE_MAT: TStringField;
    sdsParametros_RecXML: TSQLDataSet;
    cdsParametros_RecXML: TClientDataSet;
    dsParametros_RecXML: TDataSource;
    sdsParametros_RecXMLID: TIntegerField;
    sdsParametros_RecXMLPROCURAR_REM_NOME_PROD: TStringField;
    cdsParametrossdsParametros_RecXML: TDataSetField;
    cdsParametros_RecXMLID: TIntegerField;
    cdsParametros_RecXMLPROCURAR_REM_NOME_PROD: TStringField;
    sdsParametros_NFeCOPIAR_QTD_REST_ADEVOLVER: TStringField;
    cdsParametros_NFeCOPIAR_QTD_REST_ADEVOLVER: TStringField;
    sdsParametros_UsuarioSENHA_PEDIDO: TStringField;
    cdsParametros_UsuarioSENHA_PEDIDO: TStringField;
    sdsParametros_UsuarioSENHA_CREDITO: TStringField;
    cdsParametros_UsuarioSENHA_CREDITO: TStringField;
    sdsParametros_FinMOSTRAR_VLR_MULTA_DUP: TStringField;
    cdsParametros_FinMOSTRAR_VLR_MULTA_DUP: TStringField;
    sdsParametros_Cta_OrcID_CONTA_ORC_MULTA_PAG: TIntegerField;
    sdsParametros_Cta_OrcID_CONTA_ORC_MULTA_REC: TIntegerField;
    cdsParametros_Cta_OrcID_CONTA_ORC_MULTA_PAG: TIntegerField;
    cdsParametros_Cta_OrcID_CONTA_ORC_MULTA_REC: TIntegerField;
    sdsParametros_NFeIMP_CONSUMO_NOTA: TStringField;
    cdsParametros_NFeIMP_CONSUMO_NOTA: TStringField;
    sdsParametros_EstGERAR_LOTE_AUT_CONSUMO: TStringField;
    cdsParametros_EstGERAR_LOTE_AUT_CONSUMO: TStringField;
    sdsParametros_FinUSA_REGIME_CAIXA_DUP: TStringField;
    cdsParametros_FinUSA_REGIME_CAIXA_DUP: TStringField;
    sdsParametros_GeralGRAVAR_HIST_SENHA: TStringField;
    cdsParametros_GeralGRAVAR_HIST_SENHA: TStringField;
    sdsParametros_FCI: TSQLDataSet;
    cdsParametros_FCI: TClientDataSet;
    dsParametros_FCI: TDataSource;
    sdsParametros_FCIID: TIntegerField;
    sdsParametros_FCIENDERECO_ARQ: TStringField;
    cdsParametrossdsParametros_FCI: TDataSetField;
    cdsParametros_FCIID: TIntegerField;
    cdsParametros_FCIENDERECO_ARQ: TStringField;
    sdsParametros_SerMOSTRAR_STATUS: TStringField;
    cdsParametros_SerMOSTRAR_STATUS: TStringField;
    sdsParametros_FCIVERSAO_LEIAUTE: TStringField;
    cdsParametros_FCIVERSAO_LEIAUTE: TStringField;
    sdsParametros_ProdUSA_MEDIDA: TStringField;
    cdsParametros_ProdUSA_MEDIDA: TStringField;
    sdsParametros_NFeOBS_DADOS_ADI_DESONERACAO: TStringField;
    cdsParametros_NFeOBS_DADOS_ADI_DESONERACAO: TStringField;
    sdsParametros_ProdUSA_QTD_EMBALAGEM: TStringField;
    cdsParametros_ProdUSA_QTD_EMBALAGEM: TStringField;
    sdsParametros_NFeDESC_ICMS_DESONERADO: TStringField;
    cdsParametros_NFeDESC_ICMS_DESONERADO: TStringField;
    sdsParametros_GeralEND_ARQ_PERDCOMP: TStringField;
    cdsParametros_GeralEND_ARQ_PERDCOMP: TStringField;
    sdsParametros_FinSENHA_RECIBO: TStringField;
    cdsParametros_FinSENHA_RECIBO: TStringField;
    sdsParametros_RecXMLUSA_OPCAO_NOTA_LANC: TStringField;
    cdsParametros_RecXMLUSA_OPCAO_NOTA_LANC: TStringField;
    sdsParametros_FinIMP_NOSSO_NUMERO: TStringField;
    cdsParametros_FinIMP_NOSSO_NUMERO: TStringField;
    sdsParametros_FinTIPO_GERACAO_REM: TStringField;
    cdsParametros_FinTIPO_GERACAO_REM: TStringField;
    sdsParametros_OCPERMITIR_ENT_MAIOR: TStringField;
    cdsParametros_OCPERMITIR_ENT_MAIOR: TStringField;
    sdsParametros_NFeAJUSTA_VARIACAO: TStringField;
    cdsParametros_NFeAJUSTA_VARIACAO: TStringField;
    sdsParametros_GeralVERSAO_BANCO_NFE: TIntegerField;
    cdsParametros_GeralVERSAO_BANCO_NFE: TIntegerField;
    sdsParametros_NTE: TSQLDataSet;
    cdsParametros_NTE: TClientDataSet;
    dsParametros_NTE: TDataSource;
    sdsParametros_NTEID: TIntegerField;
    sdsParametros_NTESOMAR_IPI_NO_CUSTO: TStringField;
    sdsParametros_NTESOMAR_FRETE_NO_CUSTO: TStringField;
    cdsParametrossdsParametros_NTE: TDataSetField;
    cdsParametros_NTEID: TIntegerField;
    cdsParametros_NTESOMAR_IPI_NO_CUSTO: TStringField;
    cdsParametros_NTESOMAR_FRETE_NO_CUSTO: TStringField;
    sdsParametros_PedCONS_PREENCHER_DTINI: TStringField;
    cdsParametros_PedCONS_PREENCHER_DTINI: TStringField;
    sdsParametros_ProdOPCAO_APLICAR_MARGEM: TStringField;
    cdsParametros_ProdOPCAO_APLICAR_MARGEM: TStringField;
    sdsParametros_NTEATUALIZAR_CUSTO: TStringField;
    cdsParametros_NTEATUALIZAR_CUSTO: TStringField;
    sdsParametros_ProdPERC_MARGEM_PRECO: TFloatField;
    cdsParametros_ProdPERC_MARGEM_PRECO: TFloatField;
    sdsParametros_SerMOSTRA_OS_DEFEITO_ALEG: TStringField;
    sdsParametros_SerMOSTRA_OS_DEFEITO_ENC: TStringField;
    sdsParametros_SerMOSTRA_OS_ACESSORIOS: TStringField;
    cdsParametros_SerMOSTRA_OS_DEFEITO_ALEG: TStringField;
    cdsParametros_SerMOSTRA_OS_DEFEITO_ENC: TStringField;
    cdsParametros_SerMOSTRA_OS_ACESSORIOS: TStringField;
    sdsParametros_ProdOPCAO_PRECO_CONSUMO: TStringField;
    cdsParametros_ProdOPCAO_PRECO_CONSUMO: TStringField;
    sdsParametros_ProdGRAVA_CONSUMO_PRVENDA: TStringField;
    cdsParametros_ProdGRAVA_CONSUMO_PRVENDA: TStringField;
    sdsParametros_FinMOSTRAR_TIPO_CRED: TStringField;
    cdsParametros_FinMOSTRAR_TIPO_CRED: TStringField;
    sdsParametros_NFeSOMAR_FRETE_ICMS_NAC: TStringField;
    sdsParametros_NFeSOMAR_FRETE_NO_ICMS_TC: TStringField;
    cdsParametros_NFeSOMAR_FRETE_ICMS_NAC: TStringField;
    cdsParametros_NFeSOMAR_FRETE_NO_ICMS_TC: TStringField;
    sdsParametros_PedUSA_CONFERENCIA: TStringField;
    sdsParametros_PedOPCAO_CONSULTA: TStringField;
    cdsParametros_PedUSA_CONFERENCIA: TStringField;
    cdsParametros_PedOPCAO_CONSULTA: TStringField;
    sdsParametros_RecXMLATUALIZAR_NCM: TStringField;
    cdsParametros_RecXMLATUALIZAR_NCM: TStringField;
    sdsParametros_ProdQTD_CARACTER_NIVEL_GR: TIntegerField;
    cdsParametros_ProdQTD_CARACTER_NIVEL_GR: TIntegerField;
    sdsParametros_ProdUSA_DESC_MAXIMO: TStringField;
    cdsParametros_ProdUSA_DESC_MAXIMO: TStringField;
    sdsParametros_PedUSA_DESC_VAREJO: TStringField;
    sdsParametros_PedUSA_OS_REMESSA: TStringField;
    cdsParametros_PedUSA_DESC_VAREJO: TStringField;
    cdsParametros_PedUSA_OS_REMESSA: TStringField;
    sdsParametros_FinUSA_DESCONTO_VALE: TStringField;
    cdsParametros_FinUSA_DESCONTO_VALE: TStringField;
    sdsParametros_GeralEMPRESA_VAREJO: TStringField;
    cdsParametros_GeralEMPRESA_VAREJO: TStringField;
    sdsParametros_FinUSA_TABPRECO_PROM: TStringField;
    cdsParametros_FinUSA_TABPRECO_PROM: TStringField;
    sdsParametros_FinID_TABPRECO1: TIntegerField;
    sdsParametros_FinID_TABPRECO2: TIntegerField;
    sdsParametros_FinID_TABPRECO3: TIntegerField;
    cdsParametros_FinID_TABPRECO1: TIntegerField;
    cdsParametros_FinID_TABPRECO2: TIntegerField;
    cdsParametros_FinID_TABPRECO3: TIntegerField;
    sdsTab_Preco: TSQLDataSet;
    dspTab_Preco: TDataSetProvider;
    cdsTab_Preco: TClientDataSet;
    dsTab_Preco: TDataSource;
    cdsTab_PrecoID: TIntegerField;
    cdsTab_PrecoNOME: TStringField;
    cdsTab_PrecoDTCADASTRO: TDateField;
    cdsTab_PrecoOBS: TMemoField;
    cdsTab_PrecoDTINICIAL: TDateField;
    cdsTab_PrecoDTFINAL: TDateField;
    cdsTab_PrecoTABPROMOCIONAL: TStringField;
    sdsParametros_PedDESABILITAR_OC_PED: TStringField;
    cdsParametros_PedDESABILITAR_OC_PED: TStringField;
    sdsParametros_FinCOPIAR_DESC_VALE: TStringField;
    cdsParametros_FinCOPIAR_DESC_VALE: TStringField;
    sdsParametros_ProdCONS_PROD_USA_PERC: TStringField;
    cdsParametros_ProdCONS_PROD_USA_PERC: TStringField;
    sdsParametros_PedMOSTRAR_ALT_DT_ENTREGA: TStringField;
    cdsParametros_PedMOSTRAR_ALT_DT_ENTREGA: TStringField;
    sdsParametros_FinSENHA_LIBERAR_DESC: TStringField;
    cdsParametros_FinSENHA_LIBERAR_DESC: TStringField;
    sdsParametros_UsuarioMOSTRAR_PED_USUARIO: TStringField;
    cdsParametros_UsuarioMOSTRAR_PED_USUARIO: TStringField;
    sdsParametros_NFeCOPIAR_VLR_FRETE_PED: TStringField;
    cdsParametros_NFeCOPIAR_VLR_FRETE_PED: TStringField;
    sdsParametros_RecXMLMOSTRAR_VLR_VENDA: TStringField;
    cdsParametros_RecXMLMOSTRAR_VLR_VENDA: TStringField;
    sdsParametros_UsuarioALT_PRECO_PED: TStringField;
    cdsParametros_UsuarioALT_PRECO_PED: TStringField;
    sdsParametros_FinCONTROLE_DIG_PRECO: TStringField;
    cdsParametros_FinCONTROLE_DIG_PRECO: TStringField;
    sdsParametros_FinREMESSA_FILIAL_DIF: TStringField;
    cdsParametros_FinREMESSA_FILIAL_DIF: TStringField;
    sdsParametros_PedUSAR_VEND_USUARIO: TStringField;
    cdsParametros_PedUSAR_VEND_USUARIO: TStringField;
    sdsParametros_GeralINF_USUARIO_VEND: TStringField;
    cdsParametros_GeralINF_USUARIO_VEND: TStringField;
    sdsParametros_PedINF_CONSUMIDOR_AUT: TStringField;
    cdsParametros_PedINF_CONSUMIDOR_AUT: TStringField;
    sdsParametros_FinDUP_DIA_FIN_VECTO: TStringField;
    cdsParametros_FinDUP_DIA_FIN_VECTO: TStringField;
    sdsParametros_PedCONFERENCIA_SIMPLES: TStringField;
    cdsParametros_PedCONFERENCIA_SIMPLES: TStringField;
    sdsParametros_ProdID_PRODUTO_GENERICO: TIntegerField;
    cdsParametros_ProdID_PRODUTO_GENERICO: TIntegerField;
    sdsParametros_GeralEND_ASSINATURA: TStringField;
    cdsParametros_GeralEND_ASSINATURA: TStringField;
    sdsParametros_NTESOMAR_ST_NO_CUSTO: TStringField;
    cdsParametros_NTESOMAR_ST_NO_CUSTO: TStringField;
    sdsParametros_Lote: TSQLDataSet;
    cdsParametros_Lote: TClientDataSet;
    sdsParametros_LoteID: TIntegerField;
    sdsParametros_LoteTIPO_PROCESSO: TStringField;
    dsParametros_Lote: TDataSource;
    cdsParametrossdsParametros_Lote: TDataSetField;
    cdsParametros_LoteID: TIntegerField;
    cdsParametros_LoteTIPO_PROCESSO: TStringField;
    sdsParametros_ImpSOMAR_VLR_AFRMM_ICMS: TStringField;
    sdsParametros_ImpSOMAR_VLR_AFRMM_ODESP: TStringField;
    cdsParametros_ImpSOMAR_VLR_AFRMM_ICMS: TStringField;
    cdsParametros_ImpSOMAR_VLR_AFRMM_ODESP: TStringField;
    sdsParametros_ImpSOMAR_FRETE_ODESP: TStringField;
    cdsParametros_ImpSOMAR_FRETE_ODESP: TStringField;
    sdsParametros_LoteLOTE_TEXTIL: TStringField;
    cdsParametros_LoteLOTE_TEXTIL: TStringField;
    sdsParametros_MDFe: TSQLDataSet;
    cdsParametros_MDFe: TClientDataSet;
    dsParametros_MDFe: TDataSource;
    sdsParametros_MDFeID: TIntegerField;
    sdsParametros_MDFeVERSAO_EMISSAO: TStringField;
    sdsParametros_MDFeVERSAO_LEIAUTE: TStringField;
    sdsParametros_MDFeVERSAO_MODAL: TStringField;
    sdsParametros_MDFeENDXMLMDFE: TStringField;
    sdsParametros_MDFeENDPDFMDFE: TStringField;
    cdsParametrossdsParametros_MDFe: TDataSetField;
    cdsParametros_MDFeID: TIntegerField;
    cdsParametros_MDFeVERSAO_EMISSAO: TStringField;
    cdsParametros_MDFeVERSAO_LEIAUTE: TStringField;
    cdsParametros_MDFeVERSAO_MODAL: TStringField;
    cdsParametros_MDFeENDXMLMDFE: TStringField;
    cdsParametros_MDFeENDPDFMDFE: TStringField;
    sdsParametros_FinPROTESTAR_CLIENTE: TStringField;
    cdsParametros_FinPROTESTAR_CLIENTE: TStringField;
    sdsParametros_GeralPESSOA_TIPO_PADRAO: TStringField;
    sdsParametros_GeralPESSOA_PAIS_PADRAO: TIntegerField;
    sdsParametros_GeralPESSOA_CIDADE_PADRAO: TIntegerField;
    cdsParametros_GeralPESSOA_TIPO_PADRAO: TStringField;
    cdsParametros_GeralPESSOA_PAIS_PADRAO: TIntegerField;
    cdsParametros_GeralPESSOA_CIDADE_PADRAO: TIntegerField;
    sdsParametros_PedIMP_RESUMO_UNID: TStringField;
    cdsParametros_PedIMP_RESUMO_UNID: TStringField;
    sdsParametros_EstID_LOCAL_ESTOQUE_ECOM: TIntegerField;
    sdsParametros_EstEND_SALVAR_ARQ: TStringField;
    sdsParametros_EstNOME_ARQ: TStringField;
    cdsParametros_EstID_LOCAL_ESTOQUE_ECOM: TIntegerField;
    cdsParametros_EstEND_SALVAR_ARQ: TStringField;
    cdsParametros_EstNOME_ARQ: TStringField;
    sdsParametros_PedUSA_OPERACAO_SERV: TStringField;
    cdsParametros_PedUSA_OPERACAO_SERV: TStringField;
    sdsParametros_PedINF_LUCRATIVIDADE: TStringField;
    cdsParametros_PedINF_LUCRATIVIDADE: TStringField;
    sdsParametros_Etiq: TSQLDataSet;
    cdsParametros_Etiq: TClientDataSet;
    dsParametros_Etiq: TDataSource;
    sdsParametros_EtiqID: TIntegerField;
    sdsParametros_EtiqOFFSET_BORDA: TIntegerField;
    sdsParametros_EtiqBACKFEED: TIntegerField;
    sdsParametros_EtiqTEMPERATURA: TIntegerField;
    sdsParametros_EtiqVELOCIDADE: TStringField;
    cdsParametrossdsParametros_Etiq: TDataSetField;
    cdsParametros_EtiqID: TIntegerField;
    cdsParametros_EtiqOFFSET_BORDA: TIntegerField;
    cdsParametros_EtiqBACKFEED: TIntegerField;
    cdsParametros_EtiqTEMPERATURA: TIntegerField;
    cdsParametros_EtiqVELOCIDADE: TStringField;
    sdsParametros_EtiqENDERECO: TStringField;
    cdsParametros_EtiqENDERECO: TStringField;
    sdsParametros_NFeALTERAR_NOME_PROD: TStringField;
    cdsParametros_NFeALTERAR_NOME_PROD: TStringField;
    sdsParametros_ProdPRODUTO_PRECO_COR: TStringField;
    cdsParametros_ProdPRODUTO_PRECO_COR: TStringField;
    sdsParametros_PedUSA_NUM_TALAO: TStringField;
    cdsParametros_PedUSA_NUM_TALAO: TStringField;
    sdsParametros_NFeMOSTRAR_OC_NO_ITEM: TStringField;
    cdsParametros_NFeMOSTRAR_OC_NO_ITEM: TStringField;
    sdsParametros_NFeMOSTRAR_OS_NO_ITEM: TStringField;
    cdsParametros_NFeMOSTRAR_OS_NO_ITEM: TStringField;
    sdsParametros_PedUSA_COD_CLIENTE: TStringField;
    cdsParametros_PedUSA_COD_CLIENTE: TStringField;
    sdsParametros_ProdUSA_CONSUMO_COMB: TStringField;
    cdsParametros_ProdUSA_CONSUMO_COMB: TStringField;
    sdsParametros_LoteID_COR_CRU: TIntegerField;
    cdsParametros_LoteID_COR_CRU: TIntegerField;
    sdsParametros_FinANEXAR_BOLETO_TITULOS_ATR: TStringField;
    cdsParametros_FinANEXAR_BOLETO_TITULOS_ATR: TStringField;
    sdsParametros_SerCID_PRESTACAO_SERV: TStringField;
    cdsParametros_SerCID_PRESTACAO_SERV: TStringField;
    sdsParametros_GeralEND_ARQ_EDI: TStringField;
    cdsParametros_GeralEND_ARQ_EDI: TStringField;
    sdsParametros_EtiqTIPO_CLIENTE: TStringField;
    sdsParametros_EtiqTIPO_IMPRESSORA: TStringField;
    cdsParametros_EtiqTIPO_CLIENTE: TStringField;
    cdsParametros_EtiqTIPO_IMPRESSORA: TStringField;
    cdsParametros_RecXMLATUALIZAR_CEST: TStringField;
    sdsParametros_NFeMOSTRAR_VLR_FRETE_CONS: TStringField;
    cdsParametros_NFeMOSTRAR_VLR_FRETE_CONS: TStringField;
    sdsParametros_NFeMOSTRAR_VLR_DEVOL_CONS: TStringField;
    cdsParametros_NFeMOSTRAR_VLR_DEVOL_CONS: TStringField;
    sdsParametros_ImpSOMAR_NO_ICMS_OUTROS_VLR: TStringField;
    cdsParametros_ImpSOMAR_NO_ICMS_OUTROS_VLR: TStringField;
    sdsParametros_SerUSA_PROCESSO_OS: TStringField;
    cdsParametros_SerUSA_PROCESSO_OS: TStringField;
    sdsParametros_PedDESCRICAO_PHP: TStringField;
    cdsParametros_PedDESCRICAO_PHP: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_PED: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_EXP: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_FAT: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_TRANSP: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_PED: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_EXP: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_FAT: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_TRANSP: TStringField;
    sdsParametros_PedUSA_EMAIL_NO_PED: TStringField;
    cdsParametros_PedUSA_EMAIL_NO_PED: TStringField;
    sdsParametros_RecXMLATUALIZAR_CEST: TStringField;
    sdsParametros_RecXMLUSA_DIRETORIO_COPIADO: TStringField;
    cdsParametros_RecXMLUSA_DIRETORIO_COPIADO: TStringField;
    sdsParametros_UsuarioMOSTRAR_CUSTO_OS: TStringField;
    cdsParametros_UsuarioMOSTRAR_CUSTO_OS: TStringField;
    sdsParametros_PedMOSTRAR_DT_REC: TStringField;
    cdsParametros_PedMOSTRAR_DT_REC: TStringField;
    sdsParametros_PedUSAR_COPIA_OS: TStringField;
    cdsParametros_PedUSAR_COPIA_OS: TStringField;
    sdsParametros_Cta_OrcUSA_VALOR_ORC: TStringField;
    cdsParametros_Cta_OrcUSA_VALOR_ORC: TStringField;
    sdsParametros_Cta_OrcMOSTRAR_PESSOA: TStringField;
    cdsParametros_Cta_OrcMOSTRAR_PESSOA: TStringField;
    sdsParametros_UsuarioALT_MATERIAL_NEC: TStringField;
    sdsParametros_UsuarioALT_CONSUMO_NEC: TStringField;
    cdsParametros_UsuarioALT_MATERIAL_NEC: TStringField;
    cdsParametros_UsuarioALT_CONSUMO_NEC: TStringField;
    sdsParametros_SerCONTROLAR_PROCESSO_ANT: TStringField;
    cdsParametros_SerCONTROLAR_PROCESSO_ANT: TStringField;
    sdsParametros_ProdUSA_PICTOGRAMA: TStringField;
    cdsParametros_ProdUSA_PICTOGRAMA: TStringField;
    sdsParametros_ProdUSA_ID_MATERIAL_CONS: TStringField;
    cdsParametros_ProdUSA_ID_MATERIAL_CONS: TStringField;
    sdsParametros_PedENVIA_SMS: TStringField;
    cdsParametros_PedENVIA_SMS: TStringField;
    sdsParametros_GeralEMPRESA_CALCADOS: TStringField;
    cdsParametros_GeralEMPRESA_CALCADOS: TStringField;
    sdsParametros_SerUSA_NATUREZA_CID_NFSE: TStringField;
    cdsParametros_SerUSA_NATUREZA_CID_NFSE: TStringField;
    sdsParametros_PedUSA_UNIDADE_VENDA: TStringField;
    cdsParametros_PedUSA_UNIDADE_VENDA: TStringField;
    sdsParametros_ProdUSA_TAM_INDIVIDUAL: TStringField;
    cdsParametros_ProdUSA_TAM_INDIVIDUAL: TStringField;
    sdsParametros_OCUSA_NOMEPROD_FORN_OC: TStringField;
    cdsParametros_OCUSA_NOMEPROD_FORN_OC: TStringField;
    sdsParametros_NFeUSA_NOMEPROD_FORN_NFE: TStringField;
    cdsParametros_NFeUSA_NOMEPROD_FORN_NFE: TStringField;
    sdsParametros_GeralUSA_ISENTO_PESSOA: TStringField;
    cdsParametros_GeralUSA_ISENTO_PESSOA: TStringField;
    sdsParametros_PedMOSTRAR_FONE: TStringField;
    sdsParametros_PedMOSTRAR_GRUPO_PESSOA: TStringField;
    cdsParametros_PedMOSTRAR_FONE: TStringField;
    cdsParametros_PedMOSTRAR_GRUPO_PESSOA: TStringField;
    sdsParametros_SerUSA_PROCESSO_SETOR: TStringField;
    cdsParametros_SerUSA_PROCESSO_SETOR: TStringField;
    sdsParametros_GeralUSA_CUSTO: TStringField;
    cdsParametros_GeralUSA_CUSTO: TStringField;
    sdsParametros_LoteTIPO_LOTE: TStringField;
    cdsParametros_LoteTIPO_LOTE: TStringField;
    sdsParametros_LoteUSA_NECESSIDADE_IF: TStringField;
    cdsParametros_LoteUSA_NECESSIDADE_IF: TStringField;
    sdsParametros_ProdCONT_TIPO_PROD: TStringField;
    cdsParametros_ProdCONT_TIPO_PROD: TStringField;
    sdsParametros_UsuarioALT_IT_PED_COM_OP: TStringField;
    cdsParametros_UsuarioALT_IT_PED_COM_OP: TStringField;
    sdsParametros_PedUSA_OBS_ETIQUETA: TStringField;
    cdsParametros_PedUSA_OBS_ETIQUETA: TStringField;
    sdsParametros_PedPEDIDO_LOJA: TStringField;
    cdsParametros_PedPEDIDO_LOJA: TStringField;
    sdsParametros_ProdUSA_LOTE_PROD: TStringField;
    cdsParametros_ProdUSA_LOTE_PROD: TStringField;
    sdsParametros_UsuarioCONFIRMA_ENVIO_NFE: TStringField;
    cdsParametros_UsuarioCONFIRMA_ENVIO_NFE: TStringField;
    sdsParametros_GeralATUALIZAR_PRECOVENDA_DOC: TStringField;
    cdsParametros_GeralATUALIZAR_PRECOVENDA_DOC: TStringField;
    sdsParametros_EtiqTIPO_IMP_ETIQ_INDIV: TStringField;
    cdsParametros_EtiqTIPO_IMP_ETIQ_INDIV: TStringField;
    sdsParametros_NTESUB_PISCOFINS_CUSTO: TStringField;
    sdsParametros_NTESUB_ICMS_CUSTO: TStringField;
    cdsParametros_NTESUB_PISCOFINS_CUSTO: TStringField;
    cdsParametros_NTESUB_ICMS_CUSTO: TStringField;
    sdsParametros_Custo: TSQLDataSet;
    cdsParametros_Custo: TClientDataSet;
    dsParametros_Custo: TDataSource;
    sdsParametros_CustoID: TIntegerField;
    sdsParametros_CustoREV_SOMAR_IPI: TStringField;
    sdsParametros_CustoREV_SOMAR_FRETE: TStringField;
    sdsParametros_CustoREV_SOMAR_ST: TStringField;
    sdsParametros_CustoREV_SUB_ICMS: TStringField;
    sdsParametros_CustoREV_SUB_PISCOFINS: TStringField;
    sdsParametros_CustoIND_SOMAR_IPI: TStringField;
    sdsParametros_CustoIND_SOMAR_FRETE: TStringField;
    sdsParametros_CustoIND_SOMAR_ST: TStringField;
    sdsParametros_CustoIND_SUB_ICMS: TStringField;
    sdsParametros_CustoIND_SUB_PISCOFINS: TStringField;
    sdsParametros_CustoCON_SOMAR_IPI: TStringField;
    sdsParametros_CustoCON_SOMAR_ST: TStringField;
    sdsParametros_CustoCON_SOMAR_FRETE: TStringField;
    sdsParametros_CustoCON_SUB_ICMS: TStringField;
    sdsParametros_CustoCON_SUB_PISCOFINS: TStringField;
    cdsParametrossdsParametros_Custo: TDataSetField;
    cdsParametros_CustoID: TIntegerField;
    cdsParametros_CustoREV_SOMAR_IPI: TStringField;
    cdsParametros_CustoREV_SOMAR_FRETE: TStringField;
    cdsParametros_CustoREV_SOMAR_ST: TStringField;
    cdsParametros_CustoREV_SUB_ICMS: TStringField;
    cdsParametros_CustoREV_SUB_PISCOFINS: TStringField;
    cdsParametros_CustoIND_SOMAR_IPI: TStringField;
    cdsParametros_CustoIND_SOMAR_FRETE: TStringField;
    cdsParametros_CustoIND_SOMAR_ST: TStringField;
    cdsParametros_CustoIND_SUB_ICMS: TStringField;
    cdsParametros_CustoIND_SUB_PISCOFINS: TStringField;
    cdsParametros_CustoCON_SOMAR_IPI: TStringField;
    cdsParametros_CustoCON_SOMAR_ST: TStringField;
    cdsParametros_CustoCON_SOMAR_FRETE: TStringField;
    cdsParametros_CustoCON_SUB_ICMS: TStringField;
    cdsParametros_CustoCON_SUB_PISCOFINS: TStringField;
    sdsParametros_NFeIMP_QTDE_PRODUTO: TStringField;
    cdsParametros_NFeIMP_QTDE_PRODUTO: TStringField;
    sdsParametros_UsuarioUTILIZA_PESSOA_REDUZIDO: TStringField;
    cdsParametros_UsuarioUTILIZA_PESSOA_REDUZIDO: TStringField;
    sdsParametros_PedUSA_EMAIL_NFECONFIG_CONF: TStringField;
    cdsParametros_PedUSA_EMAIL_NFECONFIG_CONF: TStringField;
    sdsParametros_EstMOSTRAR_PCUSTO_MOV: TStringField;
    cdsParametros_EstMOSTRAR_PCUSTO_MOV: TStringField;
    sdsParametros_GeralUSA_TRIANGULAR: TStringField;
    cdsParametros_GeralUSA_TRIANGULAR: TStringField;
    sdsParametros_PedUSA_FINANCEIRO_CONF: TStringField;
    cdsParametros_PedUSA_FINANCEIRO_CONF: TStringField;
    sdsParametros_UsuarioALT_FINANCEIRO_CONF: TStringField;
    cdsParametros_UsuarioALT_FINANCEIRO_CONF: TStringField;
    sdsParametros_UsuarioCONFERE_FINANC: TStringField;
    cdsParametros_UsuarioCONFERE_FINANC: TStringField;
    sdsParametros_EstUSA_QTD_INI: TStringField;
    cdsParametros_EstUSA_QTD_INI: TStringField;
    sdsParametros_NTEMOSTRAR_FINALIDADE: TStringField;
    cdsParametros_NTEMOSTRAR_FINALIDADE: TStringField;
    sdsParametros_FinEXIGIR_CONTA_ORC_DUP: TStringField;
    cdsParametros_FinEXIGIR_CONTA_ORC_DUP: TStringField;
    sdsParametros_RecXMLUSA_OC_XML: TStringField;
    cdsParametros_RecXMLUSA_OC_XML: TStringField;
    sdsParametros_UsuarioALT_PROD_CLIENTE: TStringField;
    cdsParametros_UsuarioALT_PROD_CLIENTE: TStringField;
    sdsParametros_PedUSA_RETIRADA: TStringField;
    cdsParametros_PedUSA_RETIRADA: TStringField;
    sdsParametros_ProdGERAR_REF_GRUPO: TStringField;
    cdsParametros_ProdGERAR_REF_GRUPO: TStringField;
    sdsParametros_ProdQTD_DIGITOS_REF: TIntegerField;
    cdsParametros_ProdQTD_DIGITOS_REF: TIntegerField;
    sdsParametros_ProdUSA_LARG: TStringField;
    cdsParametros_ProdUSA_LARG: TStringField;
    sdsParametros_ProdINF_CBARRA_MANUAL: TStringField;
    cdsParametros_ProdINF_CBARRA_MANUAL: TStringField;
    sdsParametros_LoteGERAR_SETOR_MAT: TStringField;
    cdsParametros_LoteGERAR_SETOR_MAT: TStringField;
    sdsParametros_ImpCOFINS_SOMAR_SEG: TStringField;
    sdsParametros_ImpCOFINS_SOMAR_FRETE: TStringField;
    cdsParametros_ImpCOFINS_SOMAR_SEG: TStringField;
    cdsParametros_ImpCOFINS_SOMAR_FRETE: TStringField;
    sdsParametros_ImpICMS_SOMAR_SEG: TStringField;
    cdsParametros_ImpICMS_SOMAR_SEG: TStringField;
    sdsParametros_EtiqMARGEM: TSmallintField;
    cdsParametros_EtiqMARGEM: TSmallintField;
    sdsParametros_EtiqDESLOCAMENTO_LATERAL: TStringField;
    cdsParametros_EtiqDESLOCAMENTO_LATERAL: TStringField;
    sdsParametros_NFeUSA_PROD_NTE: TStringField;
    cdsParametros_NFeUSA_PROD_NTE: TStringField;
    sdsParametros_PedCONCATENA_PROD_COR_TAM: TStringField;
    cdsParametros_PedCONCATENA_PROD_COR_TAM: TStringField;
    sdsParametros_CustoCON_SUB_IPI: TStringField;
    sdsParametros_CustoIND_SUB_IPI: TStringField;
    sdsParametros_CustoREV_SUB_IPI: TStringField;
    cdsParametros_CustoCON_SUB_IPI: TStringField;
    cdsParametros_CustoIND_SUB_IPI: TStringField;
    cdsParametros_CustoREV_SUB_IPI: TStringField;
    sdsParametros_GeralUSA_AJUSTE_CUSTO: TStringField;
    cdsParametros_GeralUSA_AJUSTE_CUSTO: TStringField;
    sdsParametros_EstMOSTRAR_PCUSTO_TOTAL_MOV: TStringField;
    cdsParametros_EstMOSTRAR_PCUSTO_TOTAL_MOV: TStringField;
    sdsParametros_NFeUSA_PROD_CLI_PED: TStringField;
    cdsParametros_NFeUSA_PROD_CLI_PED: TStringField;
    sdsParametros_LoteUSA_REMESSA: TStringField;
    cdsParametros_LoteUSA_REMESSA: TStringField;
    sdsParametros_NFeENDERECO_ENTREGA_BRANCO: TStringField;
    cdsParametros_NFeENDERECO_ENTREGA_BRANCO: TStringField;
    sdsParametros_ProdEXCLUI_PROD_SEL: TStringField;
    cdsParametros_ProdEXCLUI_PROD_SEL: TStringField;
    sdsParametros_NFeAVISA_GNRE: TStringField;
    cdsParametros_NFeAVISA_GNRE: TStringField;
    sdsParametros_ProdMOSTRA_PROD_TPRECO: TStringField;
    cdsParametros_ProdMOSTRA_PROD_TPRECO: TStringField;
    sdsParametros_PedUSA_OPERACAO_AUT: TStringField;
    cdsParametros_PedUSA_OPERACAO_AUT: TStringField;
    sdsParametros_ProdUSA_REF2: TStringField;
    cdsParametros_ProdUSA_REF2: TStringField;
    sdsParametros_GeralUSA_COD_VENDEDOR: TStringField;
    cdsParametros_GeralUSA_COD_VENDEDOR: TStringField;
    sdsParametros_NFeIMP_OC: TStringField;
    cdsParametros_NFeIMP_OC: TStringField;
    sdsParametros_NFeIMP_USUARIO: TStringField;
    cdsParametros_NFeIMP_USUARIO: TStringField;
    sdsParametros_RecXMLPROCURAR_POR_CBARRA: TStringField;
    cdsParametros_RecXMLPROCURAR_POR_CBARRA: TStringField;
    sdsParametros_LoteUSA_COR_COMB: TStringField;
    cdsParametros_LoteUSA_COR_COMB: TStringField;
    sdsParametros_NFePERMITE_IMPORTAR_S_CLIENTE: TStringField;
    cdsParametros_NFePERMITE_IMPORTAR_S_CLIENTE: TStringField;
    sdsParametros_GeralUSA_SENHA_CONTRASENHA: TStringField;
    cdsParametros_GeralUSA_SENHA_CONTRASENHA: TStringField;
    sdsParametros_LoteLOTE_PROCESSO: TStringField;
    cdsParametros_LoteLOTE_PROCESSO: TStringField;
    sdsParametros_PedUSA_ITEM_RED: TStringField;
    cdsParametros_PedUSA_ITEM_RED: TStringField;
    sdsParametros_PedPERMITE_ALT_NOMEPROD: TStringField;
    cdsParametros_PedPERMITE_ALT_NOMEPROD: TStringField;
    sdsParametros_PedACEITA_SEM_PRECO: TStringField;
    cdsParametros_PedACEITA_SEM_PRECO: TStringField;
    sdsParametros_NFeCOPIA_PED_IMPOSTO: TStringField;
    cdsParametros_NFeCOPIA_PED_IMPOSTO: TStringField;
    sdsParametros_GeralUSA_TIPO_MATERIAL: TStringField;
    cdsParametros_GeralUSA_TIPO_MATERIAL: TStringField;
    sdsParametros_PedIMP_ORDEM_ITEM_PED: TStringField;
    cdsParametros_PedIMP_ORDEM_ITEM_PED: TStringField;
    sdsParametros_ComMOSTRAR_PED: TStringField;
    cdsParametros_ComMOSTRAR_PED: TStringField;
    sdsParametros_ProdPERC_CALCULO_PED: TFloatField;
    cdsParametros_ProdPERC_CALCULO_PED: TFloatField;
    sdsParametros_ProdGRAVAR_PRECO_COMB: TStringField;
    cdsParametros_ProdGRAVAR_PRECO_COMB: TStringField;
    sdsParametros_PedOBRIGA_USO_DTENTREGA: TStringField;
    cdsParametros_PedOBRIGA_USO_DTENTREGA: TStringField;
    sdsParametros_FinUSA_NGR: TStringField;
    sdsParametros_FinUSA_APROVA_DUP: TStringField;
    cdsParametros_FinUSA_NGR: TStringField;
    cdsParametros_FinUSA_APROVA_DUP: TStringField;
    sdsParametros_UsuarioPERMITE_APROVAR_DUP: TStringField;
    cdsParametros_UsuarioPERMITE_APROVAR_DUP: TStringField;
    sdsParametros_NFeENVAR_CODBARRA: TStringField;
    cdsParametros_NFeENVAR_CODBARRA: TStringField;
    sdsParametros_ProdGRAVAR_PRIMEIRO_MAT: TStringField;
    cdsParametros_ProdGRAVAR_PRIMEIRO_MAT: TStringField;
    sdsParametros_GeralUSA_CUSTO_PROC_ATE: TStringField;
    cdsParametros_GeralUSA_CUSTO_PROC_ATE: TStringField;
    sdsParametros_ProdSENHA_PROD_CUSTO: TStringField;
    cdsParametros_ProdSENHA_PROD_CUSTO: TStringField;
    sdsParametros_ProdID_POSICAO_PADRAO: TIntegerField;
    cdsParametros_ProdID_POSICAO_PADRAO: TIntegerField;
    sdsPosicao: TSQLDataSet;
    dspPosicao: TDataSetProvider;
    cdsPosicao: TClientDataSet;
    dsPosicao: TDataSource;
    cdsPosicaoID: TIntegerField;
    cdsPosicaoNOME: TStringField;
    sdsParametros_PedUSA_DTVALIDADE: TStringField;
    sdsParametros_PedOBS_PEDIDO: TMemoField;
    cdsParametros_PedUSA_DTVALIDADE: TStringField;
    cdsParametros_PedOBS_PEDIDO: TMemoField;
    sdsParametros_FinUSA_CLIENTE_CUSTO: TStringField;
    cdsParametros_FinUSA_CLIENTE_CUSTO: TStringField;
    sdsParametros_FinINFORMA_MOBRA_MAN: TStringField;
    cdsParametros_FinINFORMA_MOBRA_MAN: TStringField;
    sdsParametros_NFeCALC_VOLUME_QTD: TStringField;
    cdsParametros_NFeCALC_VOLUME_QTD: TStringField;
    sdsParametros_PedUSA_TAB_PRECO: TStringField;
    cdsParametros_PedUSA_TAB_PRECO: TStringField;
    sdsParametros_ProdATUALIZAR_COMB: TStringField;
    cdsParametros_ProdATUALIZAR_COMB: TStringField;
    sdsParametros_PedUSA_NUM_PEDIDO_POR_VEND: TStringField;
    cdsParametros_PedUSA_NUM_PEDIDO_POR_VEND: TStringField;
    sdsParametros_LoteUSA_LOTE_REM: TStringField;
    cdsParametros_LoteUSA_LOTE_REM: TStringField;
    sdsParametros_LoteUSA_GEROU_LOTE_PROD: TStringField;
    cdsParametros_LoteUSA_GEROU_LOTE_PROD: TStringField;
    sdsParametros_LoteQTD_DIAS_DTEMISSAO: TIntegerField;
    cdsParametros_LoteQTD_DIAS_DTEMISSAO: TIntegerField;
    sdsParametros_FinUSA_PERC_CONDPGTO: TStringField;
    cdsParametros_FinUSA_PERC_CONDPGTO: TStringField;
    sdsParametros_FinARREDONDA_PRECO_TAB: TStringField;
    cdsParametros_FinARREDONDA_PRECO_TAB: TStringField;
    sdsParametros_FinMANTER_DUP_CANC: TStringField;
    cdsParametros_FinMANTER_DUP_CANC: TStringField;
    sdsParametros_PedIMP_MATERIAL: TStringField;
    cdsParametros_PedIMP_MATERIAL: TStringField;
    sdsParametros_ProdMOSTRAR_TAM_CALC: TStringField;
    cdsParametros_ProdMOSTRAR_TAM_CALC: TStringField;
    sdsParametros_NFeMSG_SIMPLES_COMP: TStringField;
    cdsParametros_NFeMSG_SIMPLES_COMP: TStringField;
    sdsParametros_NFeUSA_PREFAT: TStringField;
    cdsParametros_NFeUSA_PREFAT: TStringField;
    sdsParametros_NFeSERIE_CPF: TStringField;
    cdsParametros_NFeSERIE_CPF: TStringField;
    sdsParametros_LoteID_PROCESSO_CONF: TIntegerField;
    cdsParametros_LoteID_PROCESSO_CONF: TIntegerField;
    sdsProcesso: TSQLDataSet;
    dspProcesso: TDataSetProvider;
    cdsProcesso: TClientDataSet;
    dsProcesso: TDataSource;
    cdsProcessoID: TIntegerField;
    cdsProcessoNOME: TStringField;
    cdsProcessoLIMITE_POR_TALAO: TStringField;
    cdsProcessoQTD_LIMITE_POR_TALAO: TIntegerField;
    cdsProcessoAGRUPAR_PEDIDOS: TStringField;
    cdsProcessoTIPO: TStringField;
    cdsProcessoCALCULA_AREA: TStringField;
    cdsProcessoQTD_DIAS_PRAZO: TIntegerField;
    cdsProcessoTERCEIRO: TStringField;
    cdsProcessoENCERADO: TStringField;
    cdsProcessoENTRADA_AUTO: TStringField;
    sdsParametros_NFeTIPO_ATENDIMENTO: TSmallintField;
    cdsParametros_NFeTIPO_ATENDIMENTO: TSmallintField;
    sdsParametros_LoteUSA_LOTE_PEDIDO: TStringField;
    cdsParametros_LoteUSA_LOTE_PEDIDO: TStringField;
    sdsParametros_NFeVERSAONFCE: TStringField;
    cdsParametros_NFeVERSAONFCE: TStringField;
    sdsParametros_RecXMLCONTROLAR_GRAVA_PROD: TStringField;
    cdsParametros_RecXMLCONTROLAR_GRAVA_PROD: TStringField;
    sdsParametros_NFeENVIAR_VPAG_SEM_VLR: TIntegerField;
    cdsParametros_NFeENVIAR_VPAG_SEM_VLR: TIntegerField;
    sdsParametros_NFeTOKEN_IBPT: TStringField;
    cdsParametros_NFeTOKEN_IBPT: TStringField;
    sdsParametros_NFeVERIFICA_IBPT_MENU: TStringField;
    cdsParametros_NFeVERIFICA_IBPT_MENU: TStringField;
    sdsParametros_ProdUSA_TAM_REFER_GRADE: TStringField;
    cdsParametros_ProdUSA_TAM_REFER_GRADE: TStringField;
    sdsParametros_EstMARCAR_BAIXA_PEDIDO: TStringField;
    cdsParametros_EstMARCAR_BAIXA_PEDIDO: TStringField;
    sdsParametros_NTEUSA_CONTA_ORCAMENTO_ITENS: TStringField;
    sdsParametros_NTEUSA_CENTRO_CUSTO: TStringField;
    cdsParametros_NTEUSA_CONTA_ORCAMENTO_ITENS: TStringField;
    cdsParametros_NTEUSA_CENTRO_CUSTO: TStringField;
    sdsParametros_SerUSA_CALC_PISCOFINS: TStringField;
    cdsParametros_SerUSA_CALC_PISCOFINS: TStringField;
    sdsParametros_ProdUSA_MAQUINA: TStringField;
    cdsParametros_ProdUSA_MAQUINA: TStringField;
    sdsParametros_UsuarioPERMITE_CANC_PED_OP: TStringField;
    cdsParametros_UsuarioPERMITE_CANC_PED_OP: TStringField;
    sdsParametros_NFeIMPRIMIR_TOTAL_VALE: TStringField;
    cdsParametros_NFeIMPRIMIR_TOTAL_VALE: TStringField;
    sdsParametros_SerLIB_QTD_PEDIDO: TStringField;
    cdsParametros_SerLIB_QTD_PEDIDO: TStringField;
    sdsParametros_NFeCOPIAR_RECNF: TStringField;
    cdsParametros_NFeCOPIAR_RECNF: TStringField;
    sdsParametros_Cta_OrcUSA_SINTETICA: TStringField;
    cdsParametros_Cta_OrcUSA_SINTETICA: TStringField;
    sdsParametros_LoteIMP_CLIENTE_LOTE: TStringField;
    cdsParametros_LoteIMP_CLIENTE_LOTE: TStringField;
    sdsParametros_LoteQTD_DIV_LOTE: TIntegerField;
    cdsParametros_LoteQTD_DIV_LOTE: TIntegerField;
    sdsParametros_LoteIMP_TALAO_POR: TStringField;
    cdsParametros_LoteIMP_TALAO_POR: TStringField;
    sdsParametros_FinCONDPGTO_FRETE_IMP: TStringField;
    cdsParametros_FinCONDPGTO_FRETE_IMP: TStringField;
    sdsParametros_UsuarioMOSTRAR_CONS_ETIQ: TStringField;
    cdsParametros_UsuarioMOSTRAR_CONS_ETIQ: TStringField;
    sdsParametros_LoteQTD_PADRAO_ETIQ: TIntegerField;
    cdsParametros_LoteQTD_PADRAO_ETIQ: TIntegerField;
    sdsParametros_EstUSA_RESERVA_PROD: TStringField;
    cdsParametros_EstUSA_RESERVA_PROD: TStringField;
    sdsParametros_LoteID_PROCESSO_EST: TIntegerField;
    cdsParametros_LoteID_PROCESSO_EST: TIntegerField;
    sdsParametros_RecXMLUSA_REF_SEQUENCIAL: TStringField;
    cdsParametros_RecXMLUSA_REF_SEQUENCIAL: TStringField;
    sdsParametros_EstUSA_LOCALIZACAO_LOTE: TStringField;
    cdsParametros_EstUSA_LOCALIZACAO_LOTE: TStringField;
    sdsParametros_EstCONTROLA_DOC_CLIFORN: TStringField;
    cdsParametros_EstCONTROLA_DOC_CLIFORN: TStringField;
    sdsParametros_EstVERIFICA_ESTOQUE_ENT_PEDIDO: TStringField;
    cdsParametros_EstVERIFICA_ESTOQUE_ENT_PEDIDO: TStringField;
    sdsParametros_PedUSA_AMOSTRA: TStringField;
    cdsParametros_PedUSA_AMOSTRA: TStringField;
    sdsParametros_NFeEND_ARQUIVO_SUFRAMA: TStringField;
    cdsParametros_NFeEND_ARQUIVO_SUFRAMA: TStringField;
    sdsParametros_NFeVERSAO_SUFRAMA: TStringField;
    cdsParametros_NFeVERSAO_SUFRAMA: TStringField;
    sdsParametros_ProdMOSTRAR_FORMA: TStringField;
    cdsParametros_ProdMOSTRAR_FORMA: TStringField;
    sdsParametros_LoteLOTE_CALCADO_NOVO: TStringField;
    sdsParametros_PedUSA_CAIXINHA: TStringField;
    cdsParametros_PedUSA_CAIXINHA: TStringField;
    sdsParametros_NFeDESCONTA_ICMS_DESON: TStringField;
    cdsParametros_NFeDESCONTA_ICMS_DESON: TStringField;
    sdsParametros_ProdUSA_CONSTRUCAO: TStringField;
    cdsParametros_ProdUSA_CONSTRUCAO: TStringField;
    sdsParametros_EtiqETIQ_TAG_NOVO_LAYOUT: TStringField;
    sdsParametros_EtiqNAO_IMP_MSG_TROCA: TStringField;
    cdsParametros_EtiqETIQ_TAG_NOVO_LAYOUT: TStringField;
    cdsParametros_EtiqNAO_IMP_MSG_TROCA: TStringField;
    sdsParametros_LoteGRAVAR_OBS_LOTE: TStringField;
    cdsParametros_LoteGRAVAR_OBS_LOTE: TStringField;
    cdsParametros_LoteLOTE_CALCADO_NOVO: TStringField;
    sdsParametros_LoteUSA_LOTE_PED_SPROC: TStringField;
    cdsParametros_LoteUSA_LOTE_PED_SPROC: TStringField;
    sdsParametros_NFeSOMAR_FRETE_IPI: TStringField;
    cdsParametros_NFeSOMAR_FRETE_IPI: TStringField;
    sdsParametros_LoteID_PROCESSO_SEMI_EST: TIntegerField;
    cdsParametros_LoteID_PROCESSO_SEMI_EST: TIntegerField;
    sdsParametros_NFeCALCULAR_DIFAL: TStringField;
    cdsParametros_NFeCALCULAR_DIFAL: TStringField;
    sdsParametros_GeralPERMITE_CNPJ_DUPLICADO_TRANSP: TStringField;
    cdsParametros_GeralPERMITE_CNPJ_DUPLICADO_TRANSP: TStringField;
    procedure DataModuleCreate(Sender: TObject);
    procedure dspParametrosUpdateError(Sender: TObject;
      DataSet: TCustomClientDataSet; E: EUpdateError;
      UpdateKind: TUpdateKind; var Response: TResolverResponse);
  private
    { Private declarations }
    procedure DoLogAdditionalValues(ATableName: string; var AValues: TArrayLogData; var UserName: string);
  public
    { Public declarations }
    vMsgErro: String;
    ctCommand: String;

    procedure prc_Localizar(ID: Integer); //-1 = Inclusão
    procedure prc_Gravar;

    procedure prc_InserirFEncargos;
  end;

var
  DMCadParametros: TDMCadParametros;

implementation

uses DmdDatabase, LogProvider, uUtilPadrao;

{$R *.dfm}

{ TDMCadPais }

procedure TDMCadParametros.prc_Gravar;
begin
  vMsgErro := '';
  if trim(cdsParametrosENDXMLNFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Endereço para salvar o XML não foi informado!';
  if trim(cdsParametrosENDPDFNFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Endereço para salvar o PDF não foi informado!';
  if trim(cdsParametrosVERSAOEMISSAONFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Versão da emissão da NFe não foi informado!';
  if trim(cdsParametrosVERSAONFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Versão da NFe não foi informado!';
  if trim(cdsParametrosLOCALSERVIDORNFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Local do servidor da NFe não foi informado!';
  if trim(cdsParametrosSERIENORMAL.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Série para as notas não foi informado!';
  if trim(cdsParametrosSERIECONTINGENCIA.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Série para as notas de contingência não foi informado!';
  if vMsgErro <> '' then
    exit;

  if cdsParametros_Fin.State in [dsEdit,dsInsert] then
    cdsParametros_Fin.Post;
  if cdsParametros_Ped.State in [dsEdit,dsInsert] then
    cdsParametros_Ped.Post;
  if cdsParametros_Geral.State in [dsEdit,dsInsert] then
    cdsParametros_Geral.Post;
  if cdsParametros_Est.State in [dsEdit,dsInsert] then
    cdsParametros_Est.Post;
  if cdsParametros_Com.State in [dsEdit,dsInsert] then
    cdsParametros_Com.Post;
  if cdsParametros_Imp.State in [dsEdit,dsInsert] then
    cdsParametros_Imp.Post;
  if cdsParametros_Ser.State in [dsEdit,dsInsert] then
    cdsParametros_Ser.Post;
  if cdsParametros_NFe.State in [dsEdit,dsInsert] then
    cdsParametros_NFe.Post;
  if cdsParametros_Cta_Orc.State in [dsEdit,dsInsert] then
    cdsParametros_Cta_Orc.Post;
  if cdsParametros_Prod.State in [dsEdit,dsInsert] then
    cdsParametros_Prod.Post;
  if cdsParametros_OC.State in [dsEdit,dsInsert] then
    cdsParametros_OC.Post;
  if cdsParametros_RecXML.State in [dsEdit,dsInsert] then
    cdsParametros_RecXML.Post;
  if cdsParametros_FCI.State in [dsEdit,dsInsert] then
    cdsParametros_FCI.Post;
  if cdsParametros_MDFe.State in [dsEdit,dsInsert] then
    cdsParametros_MDFe.Post;
  if cdsParametros_Etiq.State in [dsEdit,dsInsert] then
    cdsParametros_Etiq.Post;
  if cdsParametros_Custo.State in [dsEdit,dsInsert] then
    cdsParametros_Custo.Post;
  cdsParametros.Post;
  cdsParametros.ApplyUpdates(0);

  cdsFolhaEncargos.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Localizar(ID: Integer);
begin
  cdsParametros.Close;
  sdsParametros.CommandText := ctCommand;
  if ID <> 0 then
    sdsParametros.CommandText := sdsParametros.CommandText
                         + ' WHERE ID = ' + IntToStr(ID);
  cdsParametros.Open;
  cdsParametros_Usuario.Close;
  cdsParametros_Usuario.Open;
  cdsParametros_Fin.Close;
  cdsParametros_Fin.Open;
  cdsParametros_Ped.Close;
  cdsParametros_Ped.Open;
  cdsParametros_Geral.Close;
  cdsParametros_Geral.Open;
  cdsParametros_Est.Close;
  cdsParametros_Est.Open;
  cdsParametros_Com.Close;
  cdsParametros_Com.Open;
  cdsParametros_Imp.Close;
  cdsParametros_Imp.Open;
  cdsParametros_Ser.Close;
  cdsParametros_Ser.Open;
  cdsParametros_NFe.Close;
  cdsParametros_NFe.Open;
  cdsParametros_Cta_Orc.Close;
  cdsParametros_Cta_Orc.Open;
  cdsParametros_Prod.Close;
  cdsParametros_Prod.Open;
  cdsParametros_OC.Close;
  cdsParametros_OC.Open;
  cdsParametros_RecXML.Close;
  cdsParametros_RecXML.Open;
  cdsParametros_FCI.Close;
  cdsParametros_FCI.Open;
end;

procedure TDMCadParametros.DataModuleCreate(Sender: TObject);
var
  i, x: Integer;
  vIndices: string;
  aIndices: array of string;
begin
  ctCommand := sdsParametros.CommandText;
  cdsOperacao_Nota.Open;
  cdsContas.Open;
  cdsTipoCobranca.Open;
  cdsCFOP.Open;
  cdsCliente.Open;
  cdsNCM.Open;
  cdsContaOrcamento.Open;
  cdsObs_Lei.Open;
  cdsUsuarios.Open;
  cdsCondPgto.Open;
  cdsAtelier.Open;
  cdsUnidade.Open;
  cdsTab_Preco.Open;
  cdsLocal_Estoque.Open;
  cdsPosicao.Open;
  cdsProcesso.Open;

  LogProviderList.OnAdditionalValues := DoLogAdditionalValues;
  for i := 0 to (Self.ComponentCount - 1) do
  begin
    if (Self.Components[i] is TClientDataSet) then
    begin
      SetLength(aIndices, 0);
      vIndices := TClientDataSet(Components[i]).IndexFieldNames;
      while (vIndices <> EmptyStr) do
      begin
        SetLength(aIndices, Length(aIndices) + 1);
        x := Pos(';', vIndices);
        if (x = 0) then
        begin
          aIndices[Length(aIndices) - 1] := vIndices;
          vIndices := EmptyStr;
        end
        else
        begin
          aIndices[Length(aIndices) - 1] := Copy(vIndices, 1, x - 1);
          vIndices := Copy(vIndices, x + 1, MaxInt);
        end;
      end;
      LogProviderList.AddProvider(TClientDataSet(Self.Components[i]), TClientDataSet(Self.Components[i]).Name, aIndices);
    end;
  end;
end;

procedure TDMCadParametros.dspParametrosUpdateError(Sender: TObject;
  DataSet: TCustomClientDataSet; E: EUpdateError; UpdateKind: TUpdateKind;
  var Response: TResolverResponse);
begin
  dmDatabase.prc_UpdateError(DataSet.Name,UpdateKind,E);
end;

procedure TDMCadParametros.prc_InserirFEncargos;
var
  vAux: Integer;
begin
  if not cdsFolhaEncargos.Active then
    prc_Localizar(-1);
  vAux := dmDatabase.ProximaSequencia('FOLHAENCARGOS',0);

  cdsFolhaEncargos.Insert;
  cdsFolhaEncargosID.AsInteger     := vAux;
  cdsFolhaEncargosSIMPLES.AsString := 'S';
  cdsFolhaEncargosHORISTA.AsString := 'H';
end;

procedure TDMCadParametros.DoLogAdditionalValues(ATableName: string;
  var AValues: TArrayLogData; var UserName: string);
begin
  UserName := vUsuario;
end;

end.
