unit UDMConsPedido;

interface

uses
  SysUtils, Classes, FMTBcd, DB,Forms, DBClient, Provider, SqlExpr, frxClass, frxDBSet, frxBarcode, JPEG, frxRich, frxExportMail,
  frxExportPDF, StrUtils, frxExportXLS;

type
  TDMConsPedido = class(TDataModule)
    sdsPedido_Item: TSQLDataSet;
    dspPedido_Item: TDataSetProvider;
    cdsPedido_Item: TClientDataSet;
    dsPedido_Item: TDataSource;
    sdsFilial: TSQLDataSet;
    dspFilial: TDataSetProvider;
    cdsFilial: TClientDataSet;
    dsFilial: TDataSource;
    cdsFilialID: TIntegerField;
    cdsFilialNOME: TStringField;
    sdsProduto: TSQLDataSet;
    dspProduto: TDataSetProvider;
    cdsProduto: TClientDataSet;
    cdsProdutoID: TIntegerField;
    cdsProdutoREFERENCIA: TStringField;
    cdsProdutoNOME: TStringField;
    dsProduto: TDataSource;
    cdsProdutoTIPO_REG: TStringField;
    sdsCliente: TSQLDataSet;
    dspCliente: TDataSetProvider;
    cdsCliente: TClientDataSet;
    dsCliente: TDataSource;
    cdsClienteCODIGO: TIntegerField;
    cdsClienteNOME: TStringField;
    cdsClienteFANTASIA: TStringField;
    sdsVendedor: TSQLDataSet;
    dspVendedor: TDataSetProvider;
    cdsVendedor: TClientDataSet;
    dsVendedor: TDataSource;
    cdsVendedorCODIGO: TIntegerField;
    cdsVendedorNOME: TStringField;
    cdsVendedorFANTASIA: TStringField;
    qParametros: TSQLQuery;
    qParametrosID: TIntegerField;
    qParametrosENDXMLNFE: TStringField;
    qParametrosENDPDFNFE: TStringField;
    qParametrosSERIENORMAL: TStringField;
    qParametrosSERIECONTINGENCIA: TStringField;
    qParametrosLOCALSERVIDORNFE: TStringField;
    qParametrosEMAILRESPONSAVELSISTEMA: TStringField;
    qParametrosNFEPRODUCAO: TStringField;
    qParametrosANEXARDANFE: TStringField;
    qParametrosVERSAONFE: TStringField;
    qParametrosVERSAOEMISSAONFE: TStringField;
    qParametrosTIPOLOGONFE: TStringField;
    qParametrosAPLICARDESCONTONOICMS: TStringField;
    qParametrosAPLICARDESCONTONOIPI: TStringField;
    qParametrosSOMARNOPROD_FRETE: TStringField;
    qParametrosSOMARNOPROD_OUTRASDESP: TStringField;
    qParametrosSOMARNOPROD_SEGURO: TStringField;
    qParametrosAJUSTELOGONFEAUTOMATICO: TStringField;
    qParametrosINFNUMNOTAMANUAL: TStringField;
    qParametrosOPCAO_DTENTREGAPEDIDO: TStringField;
    qParametrosOBS_SIMPLES: TStringField;
    qParametrosIMP_OBSSIMPLES: TStringField;
    qParametrosIMP_REFERENCIANANOTA: TStringField;
    qParametrosENVIARNOTABENEF_NANFE: TStringField;
    qParametrosESPECIE_NOTA: TStringField;
    qParametrosMARCA_NOTA: TStringField;
    qParametrosVERSAO_BANCO: TIntegerField;
    qParametrosUSA_QTDPACOTE_NTE: TStringField;
    qParametrosATUALIZAR_PRECO: TStringField;
    qParametrosUSA_VENDEDOR: TStringField;
    qParametrosUSA_CONSUMO: TStringField;
    sdsPedido_Nota: TSQLDataSet;
    dsPedido_Nota: TDataSource;
    cdsPedido_Nota: TClientDataSet;
    cdsPedido_NotaID_NOTA: TIntegerField;
    cdsPedido_NotaITEM_NOTA: TIntegerField;
    cdsPedido_NotaQTD: TFloatField;
    cdsPedido_NotaNUMNOTA: TIntegerField;
    cdsPedido_NotaDTEMISSAO: TDateField;
    cdsPedido_NotaSERIE: TStringField;
    sdsPedido_Mat: TSQLDataSet;
    dspPedido_Mat: TDataSetProvider;
    cdsPedido_Mat: TClientDataSet;
    dsPedido_Mat: TDataSource;
    mProdutoSC: TClientDataSet;
    mProdutoSCID_Produto: TIntegerField;
    mProdutoSCNomeProduto: TStringField;
    dsmProdutoSC: TDataSource;
    mConsumo: TClientDataSet;
    dsmConsumo: TDataSource;
    mConsumoID_Material: TIntegerField;
    mConsumoQtd_ConsumoCalc: TFloatField;
    mConsumoQtd_MaterialTerc: TFloatField;
    mConsumoSaldo: TFloatField;
    mConsumoID_Cliente: TIntegerField;
    mConsumoNome_Cliente: TStringField;
    qNotaEntrada: TSQLQuery;
    qNotaEntradaQTDRESTANTE: TFloatField;
    cdsPedido_MatID_CLIENTE: TIntegerField;
    cdsPedido_MatID_PRODUTO: TIntegerField;
    cdsPedido_MatID_MATERIAL: TIntegerField;
    cdsPedido_MatCONSUMO_TOTAL: TFloatField;
    cdsPedido_MatFILIAL: TIntegerField;
    mConsumoQtdProduto: TFloatField;
    mConsumoNomeMaterial: TStringField;
    cdsPedido_MatNOMEMATERIAL: TStringField;
    cdsPedido_MatNOMECLIENTE: TStringField;
    cdsPedido_MatQTD_RESTANTE: TFloatField;
    cdsPedido_MatNOMEPRODUTO: TStringField;
    sdsBaixa_Pedido: TSQLDataSet;
    cdsBaixa_Pedido: TClientDataSet;
    dsBaixa_Pedido: TDataSource;
    cdsBaixa_PedidoID: TIntegerField;
    cdsBaixa_PedidoID_PEDIDO: TIntegerField;
    cdsBaixa_PedidoITEM_PEDIDO: TIntegerField;
    cdsBaixa_PedidoDTBAIXA: TDateField;
    cdsBaixa_PedidoQTD: TFloatField;
    cdsBaixa_PedidoNUM_PEDIDO: TIntegerField;
    cdsBaixa_PedidoPEDIDO_CLIENTE: TStringField;
    cdsBaixa_PedidoID_MOVESTOQUE: TIntegerField;
    cdsPedido_NotaTIPO_NOTA: TStringField;
    sdsPrc_Atualiza_Status_Ped: TSQLDataSet;
    sdsPedido: TSQLDataSet;
    dspPedido: TDataSetProvider;
    cdsPedido: TClientDataSet;
    dsPedido: TDataSource;
    cdsPedidoID_CLIENTE: TIntegerField;
    cdsPedidoID: TIntegerField;
    cdsPedidoPEDIDO_CLIENTE: TStringField;
    cdsPedidoDTEMISSAO: TDateField;
    cdsPedidoNUM_PEDIDO: TIntegerField;
    cdsPedidoID_VENDEDOR: TIntegerField;
    cdsPedidoFILIAL: TIntegerField;
    cdsPedidoNOME_FILIAL: TStringField;
    cdsPedidoNOME_FILIAL_INT: TStringField;
    cdsPedidoNOME_CLIENTE: TStringField;
    cdsPedidoNOME_VENDEDOR: TStringField;
    cdsPedidoFANTASIA: TStringField;
    cdsPedidoDTENTREGA_ITEM: TDateField;
    cdsPedidoQTD: TFloatField;
    cdsPedidoQTD_FATURADO: TFloatField;
    cdsPedidoQTD_RESTANTE: TFloatField;
    cdsPedidoQTD_CANCELADO: TFloatField;
    cdsPedidoVLR_RESTANTE: TFloatField;
    cdsPedidoVLR_FATURADO: TFloatField;
    cdsPedidoVLR_CANCELADO: TFloatField;
    cdsPedidoVLR_TOTAL: TFloatField;
    sdsPedido_Fat: TSQLDataSet;
    dspPedido_Fat: TDataSetProvider;
    cdsPedido_Fat: TClientDataSet;
    dsPedido_Fat: TDataSource;
    cdsPedido_FatID_NOTA: TIntegerField;
    cdsPedido_FatITEM_NOTA: TIntegerField;
    cdsPedido_FatNUMNOTA: TIntegerField;
    cdsPedido_FatDTEMISSAO: TDateField;
    cdsPedido_FatSERIE: TStringField;
    cdsPedido_FatTIPO_NOTA: TStringField;
    cdsPedido_FatPEDIDO_CLIENTE: TStringField;
    cdsPedido_FatID_PEDIDO: TIntegerField;
    cdsPedido_FatNOME: TStringField;
    cdsPedido_FatREFERENCIA: TStringField;
    cdsPedido_FatNOME_PRODUTO: TStringField;
    cdsPedido_FatVLR_UNITARIO: TFloatField;
    cdsPedido_FatVLR_DESCONTO: TFloatField;
    cdsPedido_FatVLR_DESCONTORATEIO: TFloatField;
    cdsPedido_FatVLR_TOTAL: TFloatField;
    cdsPedido_FatQTD: TFloatField;
    cdsPedido_FatDTENTREGA: TDateField;
    cdsPedido_FatQTD_PEDIDO: TFloatField;
    cdsPedido_FatQTD_FATURADO: TFloatField;
    cdsPedido_FatQTD_RESTANTE: TFloatField;
    cdsPedido_FatITEM_PEDIDO: TIntegerField;
    cdsPedido_FatVLR_RESTANTE: TFloatField;
    cdsPedido_FatVLR_FATURADO: TFloatField;
    cdsPedido_FatVLR_CANCELADO: TFloatField;
    cdsPedido_FatNUM_PEDIDO: TIntegerField;
    cdsPedido_FatFILIAL: TIntegerField;
    cdsPedido_FatFANTASIA: TStringField;
    sdsPedido_FatPed: TSQLDataSet;
    dspPedido_FatPed: TDataSetProvider;
    cdsPedido_FatPed: TClientDataSet;
    dsPedido_FatPed: TDataSource;
    cdsPedido_FatPedDTEMISSAO: TDateField;
    cdsPedido_FatPedPEDIDO_CLIENTE: TStringField;
    cdsPedido_FatPedID_PEDIDO: TIntegerField;
    cdsPedido_FatPedNUM_PEDIDO: TIntegerField;
    cdsPedido_FatPedFILIAL: TIntegerField;
    cdsPedido_FatPedFANTASIA: TStringField;
    cdsPedido_FatPedQTD_NOTA: TFloatField;
    cdsPedido_FatPedVLR_TOTAL: TFloatField;
    dspPedido_Nota: TDataSetProvider;
    dspBaixa_Pedido: TDataSetProvider;
    cdsPedidoCLIENTE_ESTOQUE: TStringField;
    cdsBaixa_PedidoTIPO_REG: TStringField;
    cdsBaixa_PedidoTIPO_MOV: TStringField;
    qParametrosEMPRESA_NAVALHA: TStringField;
    cdsBaixa_PedidoTIPO_BAIXA: TStringField;
    cdsPedido_MatTAMANHO: TStringField;
    cdsPedido_MatTIPO_CONSUMO: TStringField;
    cdsPedido_MatCONSUMO_TOTAL_TAM: TFloatField;
    cdsPedido_MatclConsumo: TFloatField;
    qParametrosEMPRESA_SUCATA: TStringField;
    qParametrosUSA_VALE: TStringField;
    sdsPedido_Vale: TSQLDataSet;
    cdsPedido_Vale: TClientDataSet;
    dsPedido_Vale: TDataSource;
    dspPedido_Vale: TDataSetProvider;
    cdsPedido_ValeID_VALE: TIntegerField;
    cdsPedido_ValeITEM_VALE: TIntegerField;
    cdsPedido_ValeQTD: TFloatField;
    cdsPedido_ValeNUM_VALE: TIntegerField;
    cdsPedido_ValeDTEMISSAO: TDateField;
    sdsPedido_Ref: TSQLDataSet;
    dspPedido_Ref: TDataSetProvider;
    cdsPedido_Ref: TClientDataSet;
    dsPedido_Ref: TDataSource;
    cdsPedido_RefQTD: TFloatField;
    cdsPedido_RefQTD_FATURADO: TFloatField;
    cdsPedido_RefQTD_RESTANTE: TFloatField;
    cdsPedido_RefQTD_CANCELADO: TFloatField;
    cdsPedido_RefQTD_PECA: TFMTBCDField;
    cdsPedido_RefVLR_TOTAL: TFloatField;
    cdsPedido_RefVLR_RESTANTE: TFloatField;
    cdsPedido_RefVLR_FATURADO: TFloatField;
    cdsPedido_RefVLR_CANCELADO: TFloatField;
    cdsPedido_RefID_CLIENTE: TIntegerField;
    cdsPedido_RefNOME_FILIAL: TStringField;
    cdsPedido_RefNOME_FILIAL_INT: TStringField;
    cdsPedido_RefNOME_CLIENTE: TStringField;
    cdsPedido_RefNOME_PRODUTO: TStringField;
    cdsPedido_RefNOME_VENDEDOR: TStringField;
    cdsPedido_RefREFERENCIA: TStringField;
    cdsPedido_RefPEDIDO_CLIENTE: TStringField;
    cdsPedido_RefDTEMISSAO: TDateField;
    cdsPedido_RefDTENTREGA_PED: TDateField;
    cdsPedido_RefDTENTREGA_ITEM: TDateField;
    cdsPedido_RefNUM_PEDIDO: TIntegerField;
    cdsPedido_RefNUMOS: TStringField;
    cdsPedido_RefID_PRODUTO: TIntegerField;
    cdsPedido_RefFILIAL: TIntegerField;
    cdsPedido_RefCLIENTE_ESTOQUE: TStringField;
    cdsPedido_RefFANTASIA: TStringField;
    sdsPedido_Ref_Acum: TSQLDataSet;
    dspPedido_Ref_Acum: TDataSetProvider;
    cdsPedido_Ref_Acum: TClientDataSet;
    dsPedido_Ref_Acum: TDataSource;
    cdsPedido_Ref_AcumQTD: TFloatField;
    cdsPedido_Ref_AcumQTD_FATURADO: TFloatField;
    cdsPedido_Ref_AcumQTD_RESTANTE: TFloatField;
    cdsPedido_Ref_AcumQTD_CANCELADO: TFloatField;
    cdsPedido_Ref_AcumQTD_PECA: TFMTBCDField;
    cdsPedido_Ref_AcumVLR_TOTAL: TFloatField;
    cdsPedido_Ref_AcumVLR_RESTANTE: TFloatField;
    cdsPedido_Ref_AcumVLR_FATURADO: TFloatField;
    cdsPedido_Ref_AcumVLR_CANCELADO: TFloatField;
    cdsPedido_Ref_AcumNOME_PRODUTO: TStringField;
    cdsPedido_Ref_AcumREFERENCIA: TStringField;
    cdsPedido_Ref_AcumID_PRODUTO: TIntegerField;
    sdsPedido_Cli: TSQLDataSet;
    dspPedido_Cli: TDataSetProvider;
    cdsPedido_Cli: TClientDataSet;
    dsPedido_Cli: TDataSource;
    cdsPedido_CliQTD: TFloatField;
    cdsPedido_CliQTD_FATURADO: TFloatField;
    cdsPedido_CliQTD_RESTANTE: TFloatField;
    cdsPedido_CliQTD_CANCELADO: TFloatField;
    cdsPedido_CliQTD_PECA: TFMTBCDField;
    cdsPedido_CliVLR_TOTAL: TFloatField;
    cdsPedido_CliVLR_RESTANTE: TFloatField;
    cdsPedido_CliVLR_FATURADO: TFloatField;
    cdsPedido_CliVLR_CANCELADO: TFloatField;
    cdsPedido_CliID_CLIENTE: TIntegerField;
    cdsPedido_CliNOME_CLIENTE: TStringField;
    cdsPedido_CliFANTASIA: TStringField;
    mEtiq_Individual: TClientDataSet;
    mEtiq_IndividualID_Produto: TIntegerField;
    mEtiq_IndividualReferencia: TStringField;
    mEtiq_IndividualNome_Produto: TStringField;
    mEtiq_IndividualTamanho: TStringField;
    mEtiq_IndividualTamanho_USA: TStringField;
    mEtiq_IndividualTamanho_EUR: TStringField;
    mEtiq_IndividualItem_Pedido: TIntegerField;
    mEtiq_IndividualID_Pedido: TIntegerField;
    mEtiq_IndividualNum_Pedido: TIntegerField;
    sdsPedido_Item2: TSQLDataSet;
    dspPedido_Item2: TDataSetProvider;
    cdsPedido_Item2: TClientDataSet;
    dsPedido_Item2: TDataSource;
    cdsPedido_Item2ID: TIntegerField;
    cdsPedido_Item2NUM_PEDIDO: TIntegerField;
    cdsPedido_Item2ITEM: TIntegerField;
    cdsPedido_Item2REFERENCIA: TStringField;
    cdsPedido_Item2NOMEPRODUTO: TStringField;
    cdsPedido_Item2TAMANHO: TStringField;
    cdsPedido_Item2ID_GRADE: TIntegerField;
    cdsPedido_Item2TAMANHO_USA: TStringField;
    cdsPedido_Item2TAMANHO_EUR: TStringField;
    cdsPedido_Item2QTD: TFloatField;
    dsmEtiq_Individual: TDataSource;
    cdsPedido_Item2ID_PRODUTO: TIntegerField;
    sdsProduto_Tam: TSQLDataSet;
    dspProduto_Tam: TDataSetProvider;
    cdsProduto_Tam: TClientDataSet;
    dsProduto_Tam: TDataSource;
    cdsProduto_TamID: TIntegerField;
    cdsProduto_TamTAMANHO: TStringField;
    qGradeMarcar: TSQLQuery;
    qGradeMarcarID: TIntegerField;
    qGradeMarcarTAMANHO: TStringField;
    qGradeMarcarTAMANHO_USA: TStringField;
    qGradeMarcarTAMANHO_EUR: TStringField;
    cdsProdutoID_GRADE: TIntegerField;
    frxReport1: TfrxReport;
    frxDBDataset1: TfrxDBDataset;
    frxBarCodeObject1: TfrxBarCodeObject;
    mEtiq_IndividualCodBarra: TStringField;
    mEtiq_IndividualCaminhoFoto: TStringField;
    cdsProdutoFOTO: TStringField;
    cdsPedido_Item2FOTO: TStringField;
    sdsPedido_Fut: TSQLDataSet;
    cdsPedido_Fut: TClientDataSet;
    dsPedido_Fut: TDataSource;
    dspPedido_Fut: TDataSetProvider;
    cdsPedido_FutID_NOTA: TIntegerField;
    cdsPedido_FutITEM_NOTA: TIntegerField;
    cdsPedido_FutQTD: TFloatField;
    cdsPedido_FutNUMNOTA: TIntegerField;
    cdsPedido_FutDTEMISSAO: TDateField;
    cdsPedido_FutSERIE: TStringField;
    cdsPedido_FutTIPO_NOTA: TStringField;
    qParametrosUSA_PEDIDO_FUT: TStringField;
    sdsLiberado: TSQLDataSet;
    dspLiberado: TDataSetProvider;
    cdsLiberado: TClientDataSet;
    dsLiberado: TDataSource;
    cdsLiberadoID: TIntegerField;
    cdsLiberadoPEDIDO_CLIENTE: TStringField;
    cdsLiberadoID_CLIENTE: TIntegerField;
    cdsLiberadoDTEMISSAO: TDateField;
    cdsLiberadoID_PRODUTO: TIntegerField;
    cdsLiberadoID_CFOP: TIntegerField;
    cdsLiberadoNUM_PEDIDO: TIntegerField;
    cdsLiberadoVLR_UNITARIO: TFloatField;
    cdsLiberadoQTD: TFloatField;
    cdsLiberadoQTD_FATURADO: TFloatField;
    cdsLiberadoQTD_RESTANTE: TFloatField;
    cdsLiberadoQTD_AFATURAR: TFloatField;
    cdsLiberadoID_NCM_PED: TIntegerField;
    cdsLiberadoREFERENCIA: TStringField;
    cdsLiberadoITEM_CLIENTE: TIntegerField;
    cdsLiberadoNOMECLIENTE: TStringField;
    cdsLiberadoREFERENCIA_PRO: TStringField;
    cdsLiberadoNOMEPRODUTO: TStringField;
    cdsLiberadoCNPJ_CPF: TStringField;
    cdsLiberadoDTENTREGA: TDateField;
    cdsLiberadoITEM: TIntegerField;
    cdsLiberadoVLR_DESCONTO: TFloatField;
    cdsLiberadoID_NCM: TIntegerField;
    cdsLiberadoUNIDADE: TStringField;
    cdsLiberadoPERC_IPI: TFloatField;
    cdsLiberadoOBS_COMPLEMENTAR: TStringField;
    cdsLiberadoNUMOS: TStringField;
    cdsLiberadoTIPO_FRETE: TStringField;
    cdsLiberadoID_CONDPGTO: TIntegerField;
    cdsLiberadoIMP_OC_NOTA: TStringField;
    cdsLiberadoID_VARIACAO: TIntegerField;
    cdsLiberadoQTD_LIBERADA: TFloatField;
    cdsLiberadoQTD_PRODUZIDA: TFloatField;
    cdsLiberadoTIPO_REG: TStringField;
    cdsLiberadoTAMANHO: TStringField;
    cdsLiberadoID_TRANSPORTADORA: TIntegerField;
    cdsLiberadoNUM_DOC: TIntegerField;
    cdsLiberadoNUM_TALAO: TStringField;
    cdsLiberadoVLR_DESCONTORATEIO: TFloatField;
    cdsLiberadoQTD_PECA: TIntegerField;
    cdsLiberadoQTD_FUT: TFloatField;
    qParametrosCONTROLAR_PEDIDO_LIBERACAO: TStringField;
    cdsLiberadoclQtd_Restante: TFloatField;
    qFilial_Relatorios: TSQLQuery;
    qFilial_RelatoriosTIPO: TSmallintField;
    qFilial_RelatoriosCAMINHO: TStringField;
    qFilial_RelatoriosPOSICAO: TSmallintField;
    qParametrosUSA_ETIQUETA_IND: TStringField;
    dsFilialRelatorios: TDataSource;
    cdsFilialRelatorios: TClientDataSet;
    cdsFilialRelatoriosID: TIntegerField;
    cdsFilialRelatoriosITEM: TIntegerField;
    cdsFilialRelatoriosTIPO: TSmallintField;
    cdsFilialRelatoriosCAMINHO: TStringField;
    sdsFilialRelatorios: TSQLDataSet;
    dsmFilial: TDataSource;
    cdsFilialsdsFilialRelatorios: TDataSetField;
    mEtiq_IndividualNomeCombinacao: TStringField;
    cdsPedido_Item2NOME_COMBINACAO: TStringField;
    cdsFilialRelatoriosPOSICAO: TSmallintField;
    sdsCBarra: TSQLDataSet;
    dspCBarra: TDataSetProvider;
    cdsCBarra: TClientDataSet;
    cdsCBarraID_PRODUTO: TIntegerField;
    cdsCBarraID_COR: TIntegerField;
    cdsCBarraTAMANHO: TStringField;
    dscBarra: TDataSource;
    cdsCBarraCOD_BARRA: TStringField;
    cdsProdutoID_COR: TIntegerField;
    cdsPedido_Item2ID_COR: TFMTBCDField;
    sdsPedido_Comb: TSQLDataSet;
    dspPedido_Comb: TDataSetProvider;
    cdsPedido_Comb: TClientDataSet;
    dsPedido_Comb: TDataSource;
    qParametrosINFORMAR_COR_PROD: TStringField;
    qParametrosINFORMAR_COR_MATERIAL: TStringField;
    cdsPedido_RefID_COR: TFMTBCDField;
    cdsPedido_RefNOME_COR_COMBINACAO: TStringField;
    cdsPedido_RefTIPO_REG: TStringField;
    cdsPedido_CombQTD: TFloatField;
    cdsPedido_CombQTD_FATURADO: TFloatField;
    cdsPedido_CombQTD_RESTANTE: TFloatField;
    cdsPedido_CombQTD_CANCELADO: TFloatField;
    cdsPedido_CombQTD_PECA: TFMTBCDField;
    cdsPedido_CombVLR_TOTAL: TFloatField;
    cdsPedido_CombVLR_RESTANTE: TFloatField;
    cdsPedido_CombVLR_FATURADO: TFloatField;
    cdsPedido_CombVLR_CANCELADO: TFloatField;
    cdsPedido_CombNOME_PRODUTO: TStringField;
    cdsPedido_CombREFERENCIA: TStringField;
    cdsPedido_CombID_PRODUTO: TIntegerField;
    cdsPedido_CombID_COR: TFMTBCDField;
    cdsPedido_CombNOME_COR_COMBINACAO: TStringField;
    cdsPedido_FatNOME_CLIENTE: TStringField;
    cdsPedido_FatPedNOME_CLIENTE: TStringField;
    qParametrosEMPRESA_AMBIENTES: TStringField;
    cdsPedido_NotaITEM_PEDIDO: TIntegerField;
    cdsPedido_ValeITEM_PEDIDO: TIntegerField;
    cdsPedido_FutITEM_PEDIDO: TIntegerField;
    qParametrosUSA_APROVACAO_PED: TStringField;
    qParametrosUSA_APROVACAO_OC_FORN: TStringField;
    cdsPedidoAPROVADO_PED: TStringField;
    cdsPedidoDTAPROVACAO: TDateField;
    qParametros_Ped: TSQLQuery;
    qParametros_PedID: TIntegerField;
    qParametros_PedFATURAR_PED_INTEGRAL: TStringField;
    qParametros_PedUSA_DTEXPEDICAO: TStringField;
    cdsPedido_RefDTFATURA: TDateField;
    cdsPedido_RefDTEXPEDICAO: TDateField;
    cdsPedidoDTFATURA: TDateField;
    cdsPedidoDTEXPEDICAO: TDateField;
    cdsPedido_RefDTAPROVACAO: TDateField;
    cdsPedidoID_TRANSPORTADORA: TIntegerField;
    cdsPedidoNOME_TRANSPORTADORA: TStringField;
    frxDBDataset2: TfrxDBDataset;
    frxPDFExport1: TfrxPDFExport;
    frxMailExport1: TfrxMailExport;
    frxRichObject1: TfrxRichObject;
    cdsPedidoUF: TStringField;
    cdsPedidoCIDADE: TStringField;
    sdsProduto_Sem_Venda: TSQLDataSet;
    dspProduto_Sem_Venda: TDataSetProvider;
    cdsProduto_Sem_Venda: TClientDataSet;
    dsProduto_Sem_Venda: TDataSource;
    cdsProduto_Sem_VendaID_PRODUTO: TIntegerField;
    cdsProduto_Sem_VendaREFERENCIA: TStringField;
    cdsProduto_Sem_VendaNOME: TStringField;
    cdsProduto_Sem_VendaDTEMISSAO: TDateField;
    frxDBDataset3: TfrxDBDataset;
    qParametros_Prod: TSQLQuery;
    qParametros_ProdID: TIntegerField;
    qParametros_ProdGERAR_COD_BARRA_INT: TStringField;
    sdsConsPedido_Proc: TSQLDataSet;
    dspConsPedido_Proc: TDataSetProvider;
    cdsConsPedido_Proc: TClientDataSet;
    dsConsPedido_Proc: TDataSource;
    cdsConsPedido_ProcID: TIntegerField;
    cdsConsPedido_ProcID_CLIENTE: TIntegerField;
    cdsConsPedido_ProcNUM_PEDIDO: TIntegerField;
    cdsConsPedido_ProcFILIAL: TIntegerField;
    cdsConsPedido_ProcPEDIDO_CLIENTE: TStringField;
    cdsConsPedido_ProcDTEMISSAO: TDateField;
    cdsConsPedido_ProcDTENTREGA: TDateField;
    cdsConsPedido_ProcVLR_TOTAL: TFloatField;
    cdsConsPedido_ProcVLR_ITENS: TFloatField;
    cdsConsPedido_ProcFATURADO: TStringField;
    cdsConsPedido_ProcQTD: TFloatField;
    cdsConsPedido_ProcCANCELADO: TStringField;
    cdsConsPedido_ProcAPROVADO_ORC: TStringField;
    cdsConsPedido_ProcID_VENDEDOR: TIntegerField;
    cdsConsPedido_ProcID_CFOP: TIntegerField;
    cdsConsPedido_ProcNOMECLIENTE_CAD: TStringField;
    cdsConsPedido_ProcTIPO_REG: TStringField;
    cdsConsPedido_ProcPERC_COMISSAO: TFloatField;
    cdsConsPedido_ProcNOME_CLIENTE: TStringField;
    cdsConsPedido_ProcFANTASIA: TStringField;
    cdsConsPedido_ProcUF: TStringField;
    cdsConsPedido_ProcNOME_TRANSPORTADORA: TStringField;
    cdsConsPedido_ProcVLR_IPI: TFloatField;
    cdsConsPedido_ProcTIPO_STATUS: TStringField;
    cdsConsPedido_ProcDESCRICAO_STATUS: TStringField;
    cdsConsPedido_ProcCOD_RASTREAMENTO: TStringField;
    cdsConsPedido_ProcEMAIL_ENVIADO: TStringField;
    mEtiq_IndividualNome_Cliente: TStringField;
    mEtiq_IndividualDtEntrega: TDateField;
    mEtiq_IndividualQtde: TFloatField;
    mEtiq_IndividualPedido_Cliente: TStringField;
    cdsPedido_Item2DTENTREGA_PED: TDateField;
    cdsPedido_Item2DTENTREGA_ITEM: TDateField;
    cdsPedido_Item2ID_CLIENTE: TIntegerField;
    cdsPedido_Item2PEDIDO_CLIENTE: TStringField;
    mEtiq_IndividualUnidade: TStringField;
    cdsPedido_Item2UNIDADE: TStringField;
    mEtiq_IndividualPreco_Produto: TCurrencyField;
    cdsProdutoPRECO_VENDA: TFloatField;
    mEtiq_IndividualTotalItens: TStringField;
    mEtiq_IndividualCodBarra_Talao: TStringField;
    cdsPedido_Item2CONTADOR_ITENS: TIntegerField;
    mEtiq_IndividualProcessos: TMemoField;
    qParametros_Lote: TSQLQuery;
    qParametros_LoteLOTE_TEXTIL: TStringField;
    qProcesso_Grupo: TSQLQuery;
    qProcesso_GrupoID: TIntegerField;
    qProcesso_GrupoITEM: TIntegerField;
    qProcesso_GrupoID_PROCESSO: TIntegerField;
    cdsPedido_Item2ID_PROCESSO_GRUPO: TIntegerField;
    qProcesso_GrupoNOME: TStringField;
    qProcesso_GrupoTIPO: TStringField;
    sdsPedido_Ref2: TSQLDataSet;
    dspPedido_Ref2: TDataSetProvider;
    cdsPedido_Ref2: TClientDataSet;
    dsPedido_Ref2: TDataSource;
    cdsPedido_Ref2QTD: TFloatField;
    cdsPedido_Ref2QTD_FATURADO: TFloatField;
    cdsPedido_Ref2QTD_RESTANTE: TFloatField;
    cdsPedido_Ref2QTD_CANCELADO: TFloatField;
    cdsPedido_Ref2QTD_PECA: TFMTBCDField;
    cdsPedido_Ref2VLR_TOTAL: TFloatField;
    cdsPedido_Ref2VLR_RESTANTE: TFloatField;
    cdsPedido_Ref2VLR_FATURADO: TFloatField;
    cdsPedido_Ref2VLR_CANCELADO: TFloatField;
    cdsPedido_Ref2ID_CLIENTE: TIntegerField;
    cdsPedido_Ref2NOME_FILIAL: TStringField;
    cdsPedido_Ref2NOME_FILIAL_INT: TStringField;
    cdsPedido_Ref2NOME_CLIENTE: TStringField;
    cdsPedido_Ref2NOME_VENDEDOR: TStringField;
    cdsPedido_Ref2REFERENCIA: TStringField;
    cdsPedido_Ref2PEDIDO_CLIENTE: TStringField;
    cdsPedido_Ref2DTEMISSAO: TDateField;
    cdsPedido_Ref2DTENTREGA_PED: TDateField;
    cdsPedido_Ref2DTENTREGA_ITEM: TDateField;
    cdsPedido_Ref2NUM_PEDIDO: TIntegerField;
    cdsPedido_Ref2FILIAL: TIntegerField;
    cdsPedido_Ref2FANTASIA: TStringField;
    frxPedido_Ref2: TfrxDBDataset;
    cdsFilialNOME_INTERNO: TStringField;
    mUnidade: TClientDataSet;
    dsmUnidade: TDataSource;
    mUnidadeUnidade: TStringField;
    mUnidadeQtd: TFloatField;
    mUnidadeQtd_Fat: TFloatField;
    mUnidadeQtd_Rest: TFloatField;
    qParametros_PedIMP_RESUMO_UNID: TStringField;
    frxmUnidade: TfrxDBDataset;
    cdsPedido_Ref2UNIDADE: TStringField;
    qParametros_Etiq: TSQLQuery;
    qParametros_EtiqID: TIntegerField;
    qParametros_EtiqOFFSET_BORDA: TIntegerField;
    qParametros_EtiqBACKFEED: TIntegerField;
    qParametros_EtiqTEMPERATURA: TIntegerField;
    qParametros_EtiqVELOCIDADE: TStringField;
    qParametros_EtiqENDERECO: TStringField;
    cdsFilialNOME_ETIQUETA: TStringField;
    qParametrosUSA_GRADE: TStringField;
    sdsParametros_Etiq: TSQLDataSet;
    sdsParametros_EtiqID: TIntegerField;
    sdsParametros_EtiqOFFSET_BORDA: TIntegerField;
    sdsParametros_EtiqBACKFEED: TIntegerField;
    sdsParametros_EtiqTEMPERATURA: TIntegerField;
    sdsParametros_EtiqVELOCIDADE: TStringField;
    sdsParametros_EtiqENDERECO: TStringField;
    cdsParametros_Etiq: TClientDataSet;
    cdsParametros_EtiqID: TIntegerField;
    cdsParametros_EtiqOFFSET_BORDA: TIntegerField;
    cdsParametros_EtiqBACKFEED: TIntegerField;
    cdsParametros_EtiqTEMPERATURA: TIntegerField;
    cdsParametros_EtiqVELOCIDADE: TStringField;
    cdsParametros_EtiqENDERECO: TStringField;
    dsParametros_Etiq: TDataSource;
    dspParametros_Etiq: TDataSetProvider;
    qParametros_PedUSA_OPERACAO_SERV: TStringField;
    qParametros_PedUSA_OS_REMESSA: TStringField;
    frxPedido_Item: TfrxDBDataset;
    ClientDataSet1: TClientDataSet;
    mNotas_Ped: TClientDataSet;
    mNotas_PedID_Pedido: TIntegerField;
    mNotas_PedItem_Pedido: TIntegerField;
    mNotas_PedNum_Nota: TIntegerField;
    mNotas_PedItem_Nota: TIntegerField;
    mNotas_PedDtEmissao: TDateField;
    mNotas_PedQtd: TFloatField;
    dsmNota_Ped: TDataSource;
    frxmNota_ped: TfrxDBDataset;
    qParametros_PedUSA_NUM_TALAO: TStringField;
    sdsParametros_EtiqTIPO_CLIENTE: TStringField;
    sdsParametros_EtiqTIPO_IMPRESSORA: TStringField;
    cdsParametros_EtiqTIPO_CLIENTE: TStringField;
    cdsParametros_EtiqTIPO_IMPRESSORA: TStringField;
    qParametros_EtiqTIPO_CLIENTE: TStringField;
    qParametros_EtiqTIPO_IMPRESSORA: TStringField;
    qParametros_EtiqDESLOCAMENTO_LATERAL: TStringField;
    sdsParametros_EtiqDESLOCAMENTO_LATERAL: TStringField;
    cdsParametros_EtiqDESLOCAMENTO_LATERAL: TStringField;
    cdsProdutoCOD_BARRA: TStringField;
    mEtiq_IndividualNumOS: TStringField;
    cdsPedido_Item2NUMOS: TStringField;
    mEtiq_IndividualEncerado: TStringField;
    cdsPedido_Item2ENCERADO: TStringField;
    qParametros_ProdUSA_TAM_INDIVIDUAL: TStringField;
    cdsPedido_Item2TAM_INDIVIDUAL: TStringField;
    qProcesso_GrupoORDEM: TIntegerField;
    cdsPedido_Item2TALAO_IMPRESSO: TStringField;
    mEtiq_IndividualObs_Etiqueta: TStringField;
    cdsPedido_Item2OBS_ETIQUETA: TStringField;
    sdsPedidoFaturas: TSQLDataSet;
    cdsPedidoFaturas: TClientDataSet;
    dsPedidoFaturas: TDataSource;
    dspPedidoFaturas: TDataSetProvider;
    cdsPedidoFaturasPEDIDO_CLIENTE: TStringField;
    cdsPedidoFaturasNOME_CLIENTE: TStringField;
    cdsPedidoFaturasNUMNOTA: TIntegerField;
    cdsPedidoFaturasDTEMISSAO: TDateField;
    cdsPedidoFaturasITEM: TIntegerField;
    cdsPedidoFaturasDTVENCIMENTO: TDateField;
    cdsPedidoFaturasVLR_VENCIMENTO: TFloatField;
    qParametros_EtiqTIPO_IMP_ETIQ_INDIV: TStringField;
    qParametrosUSA_COD_BARRAS: TStringField;
    qParametrosUSA_COD_BARRAS_PROPRIO: TStringField;
    cdsPedido_Item2COD_BARRA: TStringField;
    sdsParametros_EtiqMARGEM: TSmallintField;
    cdsParametros_EtiqMARGEM: TSmallintField;
    qParametros_EtiqMARGEM: TSmallintField;
    qParametros_EtiqINF_ENTER: TStringField;
    sdsParametros_EtiqINF_ENTER: TStringField;
    cdsParametros_EtiqINF_ENTER: TStringField;
    qPedidoItem: TSQLQuery;
    frxqPedidoItem: TfrxDBDataset;
    cdsPedidoNOME_PRODUTO_PROPOSTA: TStringField;
    qParametros_PedCONCATENA_PROD_COR_TAM: TStringField;
    frxXLSExport1: TfrxXLSExport;
    cdsPedido_FatNOME_COR_COMBINACAO: TStringField;
    cdsPedido_ItemID_CLIENTE: TIntegerField;
    cdsPedido_ItemID: TIntegerField;
    cdsPedido_ItemPEDIDO_CLIENTE: TStringField;
    cdsPedido_ItemDTEMISSAO: TDateField;
    cdsPedido_ItemDTENTREGA_PED: TDateField;
    cdsPedido_ItemNUM_PEDIDO: TIntegerField;
    cdsPedido_ItemID_VENDEDOR: TIntegerField;
    cdsPedido_ItemFILIAL: TIntegerField;
    cdsPedido_ItemNOME_FILIAL: TStringField;
    cdsPedido_ItemNOME_FILIAL_INT: TStringField;
    cdsPedido_ItemNOME_CLIENTE: TStringField;
    cdsPedido_ItemCLIENTE_ESTOQUE: TStringField;
    cdsPedido_ItemNOME_PRODUTO: TStringField;
    cdsPedido_ItemREFERENCIA: TStringField;
    cdsPedido_ItemITEM: TIntegerField;
    cdsPedido_ItemID_PRODUTO: TIntegerField;
    cdsPedido_ItemDTENTREGA_ITEM: TDateField;
    cdsPedido_ItemQTD: TFloatField;
    cdsPedido_ItemQTD_FATURADO: TFloatField;
    cdsPedido_ItemQTD_RESTANTE: TFloatField;
    cdsPedido_ItemQTD_CANCELADO: TFloatField;
    cdsPedido_ItemNOME_VENDEDOR: TStringField;
    cdsPedido_ItemVLR_UNITARIO: TFloatField;
    cdsPedido_ItemVLR_DESCONTO: TFloatField;
    cdsPedido_ItemVLR_TOTAL: TFloatField;
    cdsPedido_ItemNUMOS: TStringField;
    cdsPedido_ItemFANTASIA: TStringField;
    cdsPedido_ItemNUM_DOC: TIntegerField;
    cdsPedido_ItemNUM_TALAO: TStringField;
    cdsPedido_ItemNOME_PRODUTO_PED: TStringField;
    cdsPedido_ItemQTD_PECA: TIntegerField;
    cdsPedido_ItemQTD_FUT: TFloatField;
    cdsPedido_ItemID_COR: TFMTBCDField;
    cdsPedido_ItemNOME_COR_COMBINACAO: TStringField;
    cdsPedido_ItemTIPO_REG: TStringField;
    cdsPedido_ItemTAMANHO: TStringField;
    cdsPedido_ItemNOME_GRUPO: TStringField;
    cdsPedido_ItemAPROVADO_PED: TStringField;
    cdsPedido_ItemDTFATURA: TDateField;
    cdsPedido_ItemDTEXPEDICAO: TDateField;
    cdsPedido_ItemDTAPROVADO: TDateField;
    cdsPedido_ItemUNIDADE: TStringField;
    cdsPedido_ItemOBS_ETIQUETA: TStringField;
    cdsPedido_ItemMONT_COMBINACAO: TStringField;
    cdsPedido_ItemVLR_RESTANTE: TFloatField;
    cdsPedido_ItemVLR_FATURADO: TFloatField;
    cdsPedido_ItemVLR_CANCELADO: TFloatField;
    qParametros_EtiqIMPRIME_PRECO: TStringField;
    sdsParametros_EtiqIMPRIME_PRECO: TStringField;
    cdsParametros_EtiqIMPRIME_PRECO: TStringField;
    sdsPedidoTipo: TSQLDataSet;
    dspPedidoTipo: TDataSetProvider;
    cdsPedidoTipo: TClientDataSet;
    dsPedidoTipo: TDataSource;
    cdsPedidoTipoID: TIntegerField;
    cdsPedidoTipoNUM_PEDIDO: TIntegerField;
    cdsPedidoTipoID_CLIENTE: TIntegerField;
    cdsPedidoTipoQTD: TFloatField;
    cdsPedidoTipoCOMPRIMENTO: TFloatField;
    cdsPedidoTipoLARGURA: TFloatField;
    cdsPedidoTipoESPESSURA: TFloatField;
    cdsPedidoTipoDENSIDADE: TFloatField;
    cdsPedidoTipoPESO: TFloatField;
    cdsPedidoTipoID_TIPO_MATERIAL: TIntegerField;
    cdsPedidoTipoNOME_TIPO_MATERIAL: TStringField;
    frxPedidoTipo: TfrxDBDataset;
    cdsPedidoTipoDTEMISSAO: TDateField;
    cdsPedidoTipoNOMEPRODUTO: TStringField;
    cdsPedidoTipoITEM: TIntegerField;
    cdsPedidoTipoDTENTREGA: TDateField;
    cdsPedidoTipoOBS: TMemoField;
    cdsPedidoTipoNOME_CLIENTE: TStringField;
    cdsPedidoTipoFOTO: TStringField;
    frxPedido_Fat: TfrxDBDataset;
    cdsPedido_FatCODCFOP: TStringField;
    cdsPedido_FatDTEMISSAO_PED: TDateField;
    cdsPedido_FatDESC_NOTA: TStringField;
    mEtiqueta_Nav: TClientDataSet;
    mEtiqueta_NavNome_Empresa: TStringField;
    mEtiqueta_NavFone: TStringField;
    mEtiqueta_NavNome_Etiqueta: TStringField;
    mEtiqueta_NavTamanho: TStringField;
    mEtiqueta_NavReferencia: TStringField;
    mEtiqueta_NavNome_Produto: TStringField;
    mEtiqueta_NavNome_Cliente: TStringField;
    mEtiqueta_NavQtd: TIntegerField;
    mEtiqueta_NavPedido_Cliente: TStringField;
    mEtiqueta_NavFantasia_Cli: TStringField;
    mEtiqueta_NavDtEmissao: TDateField;
    mEtiqueta_NavProd_Cliente: TStringField;
    mEtiqueta_NavNumOS: TStringField;
    mEtiqueta_NavEncerado: TStringField;
    mEtiqueta_NavItem_Ped: TIntegerField;
    mEtiqueta_NavUnidade: TStringField;
    dsmEtiqueta_Nav: TDataSource;
    cdsPedido_Item2COD_COR_CLIENTE: TStringField;
    cdsPedido_Item2NOME_COR_CLIENTE: TStringField;
    cdsPedido_Item2TAMANHO_CLIENTE: TStringField;
    cdsPedido_Item2COD_PRODUTO_CLIENTE: TStringField;
    frxmEtiqueta_Nav: TfrxDBDataset;
    cdsPedidoTipoFANTASIA_CLIENTE: TStringField;
    cdsPedidoTipoNOME_CLIENTE2: TStringField;
    cdsPedidoTipoTEMPO: TFloatField;
    sdsPedido_RefComb: TSQLDataSet;
    dspPedido_RefComb: TDataSetProvider;
    cdsPedido_RefComb: TClientDataSet;
    dsPedido_RefComb: TDataSource;
    cdsPedido_RefCombQTD: TFloatField;
    cdsPedido_RefCombQTD_FATURADO: TFloatField;
    cdsPedido_RefCombQTD_RESTANTE: TFloatField;
    cdsPedido_RefCombQTD_CANCELADO: TFloatField;
    cdsPedido_RefCombQTD_PECA: TFMTBCDField;
    cdsPedido_RefCombVLR_TOTAL: TFloatField;
    cdsPedido_RefCombVLR_RESTANTE: TFloatField;
    cdsPedido_RefCombVLR_FATURADO: TFloatField;
    cdsPedido_RefCombVLR_CANCELADO: TFloatField;
    cdsPedido_RefCombREFERENCIA: TStringField;
    cdsPedido_RefCombNOME_COR_COMBINACAO: TStringField;
    cdsPedido_RefCombQTD_METRO: TFloatField;
    frxPedido_RefComb: TfrxDBDataset;
    cdsPedido_RefCombQTD_METRO_REST: TFloatField;
    sdsPedido_RefComb_DtEntrega: TSQLDataSet;
    dspPedido_RefComb_DtEntrega: TDataSetProvider;
    cdsPedido_RefComb_DtEntrega: TClientDataSet;
    dsPedido_RefComb_DtEntrega: TDataSource;
    cdsPedido_RefComb_DtEntregaQTD: TFloatField;
    cdsPedido_RefComb_DtEntregaQTD_FATURADO: TFloatField;
    cdsPedido_RefComb_DtEntregaQTD_RESTANTE: TFloatField;
    cdsPedido_RefComb_DtEntregaQTD_CANCELADO: TFloatField;
    cdsPedido_RefComb_DtEntregaQTD_PECA: TFMTBCDField;
    cdsPedido_RefComb_DtEntregaVLR_TOTAL: TFloatField;
    cdsPedido_RefComb_DtEntregaVLR_RESTANTE: TFloatField;
    cdsPedido_RefComb_DtEntregaVLR_FATURADO: TFloatField;
    cdsPedido_RefComb_DtEntregaVLR_CANCELADO: TFloatField;
    cdsPedido_RefComb_DtEntregaREFERENCIA: TStringField;
    cdsPedido_RefComb_DtEntregaNOME_COR_COMBINACAO: TStringField;
    cdsPedido_RefComb_DtEntregaDTENTREGA_ITEM: TDateField;
    cdsPedido_RefComb_DtEntregaQTD_METRO: TFloatField;
    cdsPedido_RefComb_DtEntregaQTD_METRO_REST: TFloatField;
    frxPedido_RefComb_DtEntrega: TfrxDBDataset;
    cdsPedido_ItemTAM_CALC: TFloatField;
    qParametros_ProdMOSTRAR_TAM_CALC: TStringField;
    cdsPedido_RefTAM_CALC: TFloatField;
    cdsPedido_CombTAM_CALC: TFloatField;
    sdsBaixa_PedidoID: TIntegerField;
    sdsBaixa_PedidoID_PEDIDO: TIntegerField;
    sdsBaixa_PedidoITEM_PEDIDO: TIntegerField;
    sdsBaixa_PedidoDTBAIXA: TDateField;
    sdsBaixa_PedidoQTD: TFloatField;
    sdsBaixa_PedidoNUM_PEDIDO: TIntegerField;
    sdsBaixa_PedidoPEDIDO_CLIENTE: TStringField;
    sdsBaixa_PedidoID_MOVESTOQUE: TIntegerField;
    sdsBaixa_PedidoTIPO_REG: TStringField;
    sdsBaixa_PedidoTIPO_MOV: TStringField;
    sdsBaixa_PedidoTIPO_BAIXA: TStringField;
    sdsPedido_RefComb_DtECliente: TSQLDataSet;
    dspPedido_RefComb_DtECliente: TDataSetProvider;
    cdsPedido_RefComb_DtECliente: TClientDataSet;
    dsPedido_RefComb_DtECliente: TDataSource;
    cdsPedido_RefComb_DtEClienteQTD: TFloatField;
    cdsPedido_RefComb_DtEClienteQTD_FATURADO: TFloatField;
    cdsPedido_RefComb_DtEClienteQTD_RESTANTE: TFloatField;
    cdsPedido_RefComb_DtEClienteQTD_CANCELADO: TFloatField;
    cdsPedido_RefComb_DtEClienteQTD_PECA: TFMTBCDField;
    cdsPedido_RefComb_DtEClienteVLR_TOTAL: TFloatField;
    cdsPedido_RefComb_DtEClienteVLR_RESTANTE: TFloatField;
    cdsPedido_RefComb_DtEClienteVLR_FATURADO: TFloatField;
    cdsPedido_RefComb_DtEClienteVLR_CANCELADO: TFloatField;
    cdsPedido_RefComb_DtEClienteREFERENCIA: TStringField;
    cdsPedido_RefComb_DtEClienteNOME_COR_COMBINACAO: TStringField;
    cdsPedido_RefComb_DtEClienteNOME_CLIENTE: TStringField;
    cdsPedido_RefComb_DtEClienteDTENTREGA_ITEM: TDateField;
    cdsPedido_RefComb_DtEClienteQTD_METRO: TFloatField;
    cdsPedido_RefComb_DtEClienteQTD_METRO_REST: TFloatField;
    frxPedido_RefComb_DtECliente: TfrxDBDataset;
    sdsBaixa_PedidoNUM_OS: TIntegerField;
    cdsBaixa_PedidoNUM_OS: TIntegerField;
    qParametros_Ser: TSQLQuery;
    qParametros_SerLIB_QTD_PEDIDO: TStringField;
    mEtiq_IndividualParcela3X: TCurrencyField;
    mEtiq_IndividualParcela2X: TCurrencyField;
    mEtiq_IndividualDtEmissao: TDateField;
    cdsPedido_Item2DTEMISSAO: TDateField;
    mEtiq_IndividualMarca: TStringField;
    sdsMarca: TSQLDataSet;
    dspMarca: TDataSetProvider;
    cdsMarca: TClientDataSet;
    cdsMarcaID: TIntegerField;
    cdsMarcaNOME: TStringField;
    cdsPedido_FatPESOBRUTO: TFloatField;
    cdsProdutoMARCA: TStringField;
    qParametros_ProdATUALIZA_PESO_ENG: TStringField;
    cdsPedido_FatDESC_TIPO_PRODUCAO: TStringField;
    cdsPedido_FatUNIDADE: TStringField;
    cdsPedido_FatUNIDADE_PRODUTO: TStringField;
    cdsPedido_FatID_PRODUTO: TIntegerField;
    cdsPedido_FatQTD_CONVERSOR: TFloatField;
    sdsTipoMat: TSQLDataSet;
    dspTipomat: TDataSetProvider;
    cdsTipoMat: TClientDataSet;
    cdsTipoMatDESC_TIPO_MATERIAL: TStringField;
    cdsTipoMatPESOBRUTO: TFloatField;
    dsTipoMaterial: TDataSource;
    qParametros_EtiqETIQ_TAG_NOVO_LAYOUT: TStringField;
    sdsParametros_EtiqETIQ_TAG_NOVO_LAYOUT: TStringField;
    cdsParametros_EtiqETIQ_TAG_NOVO_LAYOUT: TStringField;
    sdsParametros_EtiqNAO_IMP_MSG_TROCA: TStringField;
    cdsParametros_EtiqNAO_IMP_MSG_TROCA: TStringField;
    cdsPedidoDTENTREGA_PED: TDateField;
    procedure DataModuleCreate(Sender: TObject);
    procedure mConsumoNewRecord(DataSet: TDataSet);
    procedure cdsPedido_MatCalcFields(DataSet: TDataSet);
    procedure frxReport1Preview(Sender: TObject);
    procedure cdsLiberadoCalcFields(DataSet: TDataSet);
    procedure mUnidadeNewRecord(DataSet: TDataSet);
    procedure frxDBDataset2First(Sender: TObject);
    procedure frxDBDataset2Next(Sender: TObject);
    procedure frxReport1BeforePrint(Sender: TfrxReportComponent);
  private
    { Private declarations }
  public
    { Public declarations }
    controla_Impressao : String;
    ctPedido_Item: String;
    ctPedido_Ref: String;
    ctPedido_Ref2: String;
    ctPedido_Ref_Acum: String;
    ctPedido_Comb: String;
    ctPedido_RefComb: String;
    ctPedido_RefComb_DTEntrega: String;
    ctPedido_RefComb_DTECliente: String;
    ctPedido_Mat: String;
    ctPedido: String;
    ctPedido_Fat: String;
    ctPedido_FatPed: String;
    ctPedido_Cli: String;
    ctPedido_Item2: String;
    ctLiberado: String;
    ctConsPedido_Proc: String;
    ctConsPedido_Alt: String;
    ctPedFaturas: String;
    ctTipoMat : String;
    vDataIni, vDataFim : String;

    ctPedido_Nota, ctPedido_Vale, ctBaixa_Pedido, ctPedido_Fut: String;
    ctPedidoTipo : String;

    procedure prc_Consultar_Pedido_Nota(ID, Item: Integer);
    procedure prc_Abre_Pedido_Item(ID : Integer);
    procedure prc_Abre_Baixar_Pedido(ID, Item:Integer);

  end;

var
  DMConsPedido: TDMConsPedido;

implementation

uses DmdDatabase;

{$R *.dfm}

procedure TDMConsPedido.DataModuleCreate(Sender: TObject);
begin
  cdsPedido_Item.Close;
  cdsPedido_Ref.Close;
  ctPedido_Item     := sdsPedido_Item.CommandText;
  ctPedido_Ref      := sdsPedido_Ref.CommandText;
  ctPedido_Ref2     := sdsPedido_Ref2.CommandText;
  ctPedido_Ref_Acum := sdsPedido_Ref_Acum.CommandText;
  ctPedido_Comb     := sdsPedido_Comb.CommandText;
  ctPedido_RefComb  := sdsPedido_RefComb.CommandText;
  ctPedido_RefComb_DTEntrega  := sdsPedido_RefComb_DtEntrega.CommandText;
  ctPedido_RefComb_DTECliente := sdsPedido_RefComb_DtECliente.CommandText;
  ctPedido_Cli      := sdsPedido_Cli.CommandText;
  ctPedido          := sdsPedido.CommandText;
  ctPedido_Fat      := sdsPedido_Fat.CommandText;
  ctPedido_FatPed   := sdsPedido_FatPed.CommandText;
  ctPedido_Item2    := sdsPedido_Item2.CommandText;
  ctLiberado        := sdsLiberado.CommandText;
  ctConsPedido_Proc := sdsConsPedido_Proc.CommandText;

  ctPedido_Nota     := sdsPedido_Nota.CommandText;
  ctPedido_Vale     := sdsPedido_Vale.CommandText;
  ctBaixa_Pedido    := sdsBaixa_Pedido.CommandText;
  ctPedido_Fut      := sdsPedido_Fut.CommandText;
  ctPedFaturas      := sdsPedidoFaturas.CommandText;

  ctPedidoTipo      := sdsPedidoTipo.CommandText;

  ctTipoMat         := sdsTipoMat.CommandText;

  cdsFilial.Open;
  cdsProduto.Open;
  cdsCliente.Open;
  cdsVendedor.Open;
  qParametros.Open;
  qParametros_Ped.Open;
  qParametros_Prod.Close;
  qParametros_Prod.Open;
  qParametros_Lote.Close;
  qParametros_Lote.Open;
  qParametros_Etiq.Open;
  qParametros_Ser.Open;
end;

procedure TDMConsPedido.mConsumoNewRecord(DataSet: TDataSet);
begin
  mConsumoQtd_ConsumoCalc.AsFloat  := StrToFloat(FormatFloat('0.00',0));
  mConsumoQtd_MaterialTerc.AsFloat := StrToFloat(FormatFloat('0.00',0));
  mConsumoSaldo.AsFloat            := StrToFloat(FormatFloat('0.00',0));
  mConsumoQtdProduto.AsFloat       := StrToFloat(FormatFloat('0.00',0));
end;

procedure TDMConsPedido.cdsPedido_MatCalcFields(DataSet: TDataSet);
begin
  if cdsPedido_MatTIPO_CONSUMO.AsString = 'T' then
    cdsPedido_MatclConsumo.AsFloat := StrToFloat(FormatFloat('0.00000',cdsPedido_MatCONSUMO_TOTAL_TAM.AsFloat))
  else
    cdsPedido_MatclConsumo.AsFloat := StrToFloat(FormatFloat('0.00000',cdsPedido_MatCONSUMO_TOTAL.AsFloat));
end;

procedure TDMConsPedido.frxReport1Preview(Sender: TObject);
begin
  if FileExists(mEtiq_IndividualCaminhoFoto.AsString) then
  begin
    if frxReport1.FindComponent('Picture1')<> nil then
      TfrxPictureView(frxReport1.FindComponent('Picture1')).Picture.LoadFromFile(mEtiq_IndividualCaminhoFoto.AsString);
  end;
end;

procedure TDMConsPedido.cdsLiberadoCalcFields(DataSet: TDataSet);
begin
  if qParametrosCONTROLAR_PEDIDO_LIBERACAO.AsString = 'S' then
    cdsLiberadoclQtd_Restante.AsFloat := StrToFloat(FormatFloat('0.000000',cdsLiberadoQTD_LIBERADA.AsFloat))
  else
    cdsLiberadoclQtd_Restante.AsFloat := StrToFloat(FormatFloat('0.000000',cdsLiberadoQTD_RESTANTE.AsFloat));
end;

procedure TDMConsPedido.mUnidadeNewRecord(DataSet: TDataSet);
begin
  mUnidadeQtd.AsFloat      := 0;
  mUnidadeQtd_Fat.AsFloat  := 0;
  mUnidadeQtd_Rest.AsFloat := 0;
end;

procedure TDMConsPedido.prc_Consultar_Pedido_Nota(ID, Item: Integer);

    procedure prc_Montar_cdsPedido_Nota;
    var
      vComandoAux, vComandoAux2: String;
      i: Integer;
    begin
      vComandoAux := sdsPedido_Nota.CommandText;
      i := PosEx('UNION',sdsPedido_Nota.CommandText,0);
      if i > 0 then
        vComandoAux := copy(sdsPedido_Nota.CommandText,1,i-1);
      vComandoAux2 := copy(sdsPedido_Nota.CommandText,i,Length(sdsPedido_Nota.CommandText)-i+1);
      if Item > 0 then
      begin
        vComandoAux  := vComandoAux + ' AND NP.ITEM_PEDIDO = :ITEM ';
        vComandoAux2 := vComandoAux2 + ' AND NPT.ITEM_PEDIDO = :ITEM ';
        sdsPedido_Nota.CommandText := vComandoAux + vComandoAux2;
        sdsPedido_Nota.ParamByName('ITEM').AsInteger := Item;
      end;
    end;

begin
  cdsPedido_Nota.Close;
  sdsPedido_Nota.CommandText := ctPedido_Nota;
  if Item > 0 then
    prc_Montar_cdsPedido_Nota;

  sdsPedido_Nota.ParamByName('ID').AsInteger := ID;
  //fDMConsPedido.sdsPedido_Nota.ParamByName('ITEM').AsInteger := vItem_Pedido_Cons;
  cdsPedido_Nota.Open;
end;

procedure TDMConsPedido.prc_Abre_Pedido_Item(ID: Integer);
begin
  qPedidoItem.Close;
  qPedidoItem.ParamByName('ID').AsInteger := ID;
  qPedidoItem.Open;
end;

procedure TDMConsPedido.frxDBDataset2First(Sender: TObject);
begin
  prc_Abre_Pedido_Item(cdsPedidoID.AsInteger);
end;

procedure TDMConsPedido.frxDBDataset2Next(Sender: TObject);
begin
  prc_Abre_Pedido_Item(cdsPedidoID.AsInteger);
end;

procedure TDMConsPedido.frxReport1BeforePrint(Sender: TfrxReportComponent);
var
  vArq : String;
begin
  vArq := ExtractFilePath(Application.ExeName) + 'Relatorios\Pedido_Item_Consolidado.fr3';
  if frxReport1.FileName <> vArq then
    Exit;
  if  vDataIni <> '' then
    TfrxMemoView(frxReport1.FindComponent('Memo1')).Text := 'Período de ' + vDataIni + ' até ' + vDataFim;
end;

procedure TDMConsPedido.prc_Abre_Baixar_Pedido(ID, Item: Integer);
begin
  cdsBaixa_Pedido.Close;
  sdsBaixa_Pedido.CommandText := ctBaixa_Pedido;
  if Item > 0 then
  begin
    sdsBaixa_Pedido.CommandText := sdsBaixa_Pedido.CommandText + ' AND BX.ITEM_PEDIDO = :ITEM ';
    sdsBaixa_Pedido.ParamByName('ITEM').AsInteger := Item;
  end;
  sdsBaixa_Pedido.ParamByName('ID').AsInteger   := ID;
  cdsBaixa_Pedido.Open;
end;

end.
