unit UDMConsNotaEletronica;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr;

type
  TDMConsNotaEletronica = class(TDataModule)
    sdsNota_Fiscal_Eletronica: TSQLDataSet;
    dspNota_Fiscal_Eletronica: TDataSetProvider;
    cdsNota_Fiscal_Eletronica: TClientDataSet;
    dsNota_Fiscal_Eletronica: TDataSource;
    sdsNota_Fiscal_EletronicaCHAVE_ACESSO: TStringField;
    sdsNota_Fiscal_EletronicaXML_ASSINADO: TMemoField;
    cdsNota_Fiscal_EletronicaCHAVE_ACESSO: TStringField;
    cdsNota_Fiscal_EletronicaXML_ASSINADO: TMemoField;
    sdsNotaFiscal: TSQLDataSet;
    dspNotaFiscal: TDataSetProvider;
    cdsNotaFiscal: TClientDataSet;
    dsNotaFiscal: TDataSource;
    sdsNota_Fiscal_EletronicaSTATUS: TIntegerField;
    cdsNota_Fiscal_EletronicaSTATUS: TIntegerField;
    sdsNotaFiscalID: TIntegerField;
    sdsNotaFiscalTIPO_REG: TStringField;
    sdsNotaFiscalFILIAL: TIntegerField;
    sdsNotaFiscalSERIE: TStringField;
    sdsNotaFiscalNUMNOTA: TIntegerField;
    sdsNotaFiscalDTEMISSAO: TDateField;
    sdsNotaFiscalID_CFOP: TIntegerField;
    sdsNotaFiscalID_CLIENTE: TIntegerField;
    sdsNotaFiscalID_CONDPGTO: TIntegerField;
    sdsNotaFiscalID_VENDEDOR: TIntegerField;
    sdsNotaFiscalBASE_ICMS: TFloatField;
    sdsNotaFiscalVLR_ICMS: TFloatField;
    sdsNotaFiscalVLR_IPI: TFloatField;
    sdsNotaFiscalVLR_NOTA: TFloatField;
    sdsNotaFiscalVLR_ITENS: TFloatField;
    sdsNotaFiscalVLR_DUPLICATA: TFloatField;
    sdsNotaFiscalVLR_ENTRADA: TFloatField;
    sdsNotaFiscalPERC_DESCONTO: TFloatField;
    sdsNotaFiscalVLR_DESCONTO: TFloatField;
    sdsNotaFiscalVLR_FRETE: TFloatField;
    sdsNotaFiscalVLR_SEGURO: TFloatField;
    sdsNotaFiscalVLR_OUTRASDESP: TFloatField;
    sdsNotaFiscalBASE_ICMSTRANSF: TFloatField;
    sdsNotaFiscalPERC_TRANSF: TFloatField;
    sdsNotaFiscalVLR_TRANSF: TFloatField;
    sdsNotaFiscalVLR_PIS: TFloatField;
    sdsNotaFiscalVLR_COFINS: TFloatField;
    sdsNotaFiscalVLR_TAXACISCOMEX: TFloatField;
    sdsNotaFiscalVLR_OUTROS: TFloatField;
    sdsNotaFiscalBASE_ICMSSIMPLES: TFloatField;
    sdsNotaFiscalVLR_ICMSSIMPLES: TFloatField;
    sdsNotaFiscalPERC_ICMSSIMPLES: TFloatField;
    sdsNotaFiscalVLR_IMPORTACAO: TFloatField;
    sdsNotaFiscalBASE_ICMSSUBST: TFloatField;
    sdsNotaFiscalVLR_ICMSSUBST: TFloatField;
    sdsNotaFiscalBASE_ICMSOUTROS: TFloatField;
    sdsNotaFiscalVLR_ICMSOUTROS: TFloatField;
    sdsNotaFiscalVLR_DUPLICATAOUTROS: TFloatField;
    sdsNotaFiscalVLR_ADUANEIRA: TFloatField;
    sdsNotaFiscalPERC_ICMS_PISCOFINS: TFloatField;
    sdsNotaFiscalPERC_ICMS_OUTROSVALORES: TFloatField;
    sdsNotaFiscalPERC_ICMS_FRETE: TFloatField;
    sdsNotaFiscalPERC_DESCONTOORIG: TFloatField;
    sdsNotaFiscalQTDVOLUME: TIntegerField;
    sdsNotaFiscalESPECIE: TStringField;
    sdsNotaFiscalMARCA: TStringField;
    sdsNotaFiscalNUMEROVOLUME: TStringField;
    sdsNotaFiscalPESOBRUTO: TFloatField;
    sdsNotaFiscalPESOLIQUIDO: TFloatField;
    sdsNotaFiscalPLACA: TStringField;
    sdsNotaFiscalUFPLACA: TStringField;
    sdsNotaFiscalTIPO_FRETE: TStringField;
    sdsNotaFiscalID_TRANSPORTADORA: TIntegerField;
    sdsNotaFiscalID_REDESPACHO: TIntegerField;
    sdsNotaFiscalTIPO_NOTA: TStringField;
    sdsNotaFiscalCANCELADA: TStringField;
    sdsNotaFiscalMOTIVO_CANCELADA: TStringField;
    sdsNotaFiscalDTSAIDAENTRADA: TDateField;
    sdsNotaFiscalHRSAIDAENTRADA: TTimeField;
    sdsNotaFiscalID_BANCO: TIntegerField;
    sdsNotaFiscalLOCALENTREGA: TStringField;
    sdsNotaFiscalID_EXTCOMISSAO: TIntegerField;
    sdsNotaFiscalDESCRICAO_DESC: TStringField;
    sdsNotaFiscalID_CLIENTETRIANG: TIntegerField;
    sdsNotaFiscalQTDTOTAL_ITENS: TIntegerField;
    sdsNotaFiscalNFERECIBO: TStringField;
    sdsNotaFiscalNFEPROTOCOLO: TStringField;
    sdsNotaFiscalNFECHAVEACESSO: TStringField;
    sdsNotaFiscalNFEPROTOCOLO_CANCELADA: TStringField;
    sdsNotaFiscalTIPO_ENVIONFE: TStringField;
    sdsNotaFiscalNFECODBARRA_CONTINGENCIA: TStringField;
    sdsNotaFiscalNFEVERSAO: TStringField;
    sdsNotaFiscalNFEFINALIDADE: TStringField;
    sdsNotaFiscalNFEAMBIENTE: TStringField;
    sdsNotaFiscalNUMNOTACOPIADA: TIntegerField;
    sdsNotaFiscalSERIECOPIADA: TStringField;
    sdsNotaFiscalDTCONTINGENCIA: TDateField;
    sdsNotaFiscalHRCONTINGENCIA: TTimeField;
    sdsNotaFiscalMOTIVO_CONTINGENCIA: TStringField;
    sdsNotaFiscalNFEVERSAOEMISSAO: TStringField;
    sdsNotaFiscalID_REGIMETRIB: TIntegerField;
    sdsNotaFiscalRNTC: TStringField;
    sdsNotaFiscalVAGAOBALSA_IDENTIF: TStringField;
    sdsNotaFiscalVAGAOBALSA_TIPOIDENTIF: TStringField;
    sdsNotaFiscalUFEMBEXPORTACAO: TStringField;
    sdsNotaFiscalLOCALEMBEXPORTACAO: TStringField;
    sdsNotaFiscalPISCOFINS_SOMAROUTRASDESP: TStringField;
    sdsNotaFiscalTIPO_DESCONTO: TStringField;
    sdsNotaFiscalGERARDUPL_OUTROSVALORES: TStringField;
    sdsNotaFiscalGERARDUPL_FRETE: TStringField;
    sdsNotaFiscalGERARDUPL_SEGURO: TStringField;
    sdsNotaFiscalINFORMADO_NUMNOTAMANUAL: TStringField;
    sdsNotaFiscalNFEDENEGADA: TStringField;
    sdsNotaFiscalMOTIVO_DENEGADA: TStringField;
    sdsNotaFiscalDADOS_ADICIONAIS: TMemoField;
    sdsNotaFiscalDTINICIO_DUPLICATA: TDateField;
    sdsNotaFiscalTIPO_PRAZO: TStringField;
    sdsNotaFiscalPERC_COMISSAO: TFloatField;
    sdsNotaFiscalSIMPLES_FILIAL: TStringField;
    sdsNotaFiscalID_OPERACAO_NOTA: TIntegerField;
    sdsNotaFiscalFINALIDADE: TStringField;
    sdsNotaFiscalID_VARIACAO: TIntegerField;
    sdsNotaFiscalSTATUS_MANIFESTO: TStringField;
    sdsNotaFiscalID_CONTA: TIntegerField;
    sdsNotaFiscalID_TIPO_COBRANCA: TIntegerField;
    sdsNotaFiscalCALCULAR_IMP_ITEM: TStringField;
    sdsNotaFiscalGRAVOU_DADOSADICIONAIS: TStringField;
    sdsNotaFiscalVLR_TRIBUTOS: TFloatField;
    sdsNotaFiscalUSA_TRANSFICMS: TStringField;
    sdsNotaFiscalID_NOTACOPIADA: TIntegerField;
    sdsNotaFiscalID_CONTA_ORCAMENTO: TIntegerField;
    sdsNotaFiscalNOTA_ESTORNO: TStringField;
    sdsNotaFiscalCOD_MODELO: TStringField;
    sdsNotaFiscalCOD_CONS_EE: TStringField;
    sdsNotaFiscalCOD_CONS_AGUA: TStringField;
    sdsNotaFiscalNOME_CLIENTE: TStringField;
    cdsNotaFiscalID: TIntegerField;
    cdsNotaFiscalTIPO_REG: TStringField;
    cdsNotaFiscalFILIAL: TIntegerField;
    cdsNotaFiscalSERIE: TStringField;
    cdsNotaFiscalNUMNOTA: TIntegerField;
    cdsNotaFiscalDTEMISSAO: TDateField;
    cdsNotaFiscalID_CFOP: TIntegerField;
    cdsNotaFiscalID_CLIENTE: TIntegerField;
    cdsNotaFiscalID_CONDPGTO: TIntegerField;
    cdsNotaFiscalID_VENDEDOR: TIntegerField;
    cdsNotaFiscalBASE_ICMS: TFloatField;
    cdsNotaFiscalVLR_ICMS: TFloatField;
    cdsNotaFiscalVLR_IPI: TFloatField;
    cdsNotaFiscalVLR_NOTA: TFloatField;
    cdsNotaFiscalVLR_ITENS: TFloatField;
    cdsNotaFiscalVLR_DUPLICATA: TFloatField;
    cdsNotaFiscalVLR_ENTRADA: TFloatField;
    cdsNotaFiscalPERC_DESCONTO: TFloatField;
    cdsNotaFiscalVLR_DESCONTO: TFloatField;
    cdsNotaFiscalVLR_FRETE: TFloatField;
    cdsNotaFiscalVLR_SEGURO: TFloatField;
    cdsNotaFiscalVLR_OUTRASDESP: TFloatField;
    cdsNotaFiscalBASE_ICMSTRANSF: TFloatField;
    cdsNotaFiscalPERC_TRANSF: TFloatField;
    cdsNotaFiscalVLR_TRANSF: TFloatField;
    cdsNotaFiscalVLR_PIS: TFloatField;
    cdsNotaFiscalVLR_COFINS: TFloatField;
    cdsNotaFiscalVLR_TAXACISCOMEX: TFloatField;
    cdsNotaFiscalVLR_OUTROS: TFloatField;
    cdsNotaFiscalBASE_ICMSSIMPLES: TFloatField;
    cdsNotaFiscalVLR_ICMSSIMPLES: TFloatField;
    cdsNotaFiscalPERC_ICMSSIMPLES: TFloatField;
    cdsNotaFiscalVLR_IMPORTACAO: TFloatField;
    cdsNotaFiscalBASE_ICMSSUBST: TFloatField;
    cdsNotaFiscalVLR_ICMSSUBST: TFloatField;
    cdsNotaFiscalBASE_ICMSOUTROS: TFloatField;
    cdsNotaFiscalVLR_ICMSOUTROS: TFloatField;
    cdsNotaFiscalVLR_DUPLICATAOUTROS: TFloatField;
    cdsNotaFiscalVLR_ADUANEIRA: TFloatField;
    cdsNotaFiscalPERC_ICMS_PISCOFINS: TFloatField;
    cdsNotaFiscalPERC_ICMS_OUTROSVALORES: TFloatField;
    cdsNotaFiscalPERC_ICMS_FRETE: TFloatField;
    cdsNotaFiscalPERC_DESCONTOORIG: TFloatField;
    cdsNotaFiscalQTDVOLUME: TIntegerField;
    cdsNotaFiscalESPECIE: TStringField;
    cdsNotaFiscalMARCA: TStringField;
    cdsNotaFiscalNUMEROVOLUME: TStringField;
    cdsNotaFiscalPESOBRUTO: TFloatField;
    cdsNotaFiscalPESOLIQUIDO: TFloatField;
    cdsNotaFiscalPLACA: TStringField;
    cdsNotaFiscalUFPLACA: TStringField;
    cdsNotaFiscalTIPO_FRETE: TStringField;
    cdsNotaFiscalID_TRANSPORTADORA: TIntegerField;
    cdsNotaFiscalID_REDESPACHO: TIntegerField;
    cdsNotaFiscalTIPO_NOTA: TStringField;
    cdsNotaFiscalCANCELADA: TStringField;
    cdsNotaFiscalMOTIVO_CANCELADA: TStringField;
    cdsNotaFiscalDTSAIDAENTRADA: TDateField;
    cdsNotaFiscalHRSAIDAENTRADA: TTimeField;
    cdsNotaFiscalID_BANCO: TIntegerField;
    cdsNotaFiscalLOCALENTREGA: TStringField;
    cdsNotaFiscalID_EXTCOMISSAO: TIntegerField;
    cdsNotaFiscalDESCRICAO_DESC: TStringField;
    cdsNotaFiscalID_CLIENTETRIANG: TIntegerField;
    cdsNotaFiscalQTDTOTAL_ITENS: TIntegerField;
    cdsNotaFiscalNFERECIBO: TStringField;
    cdsNotaFiscalNFEPROTOCOLO: TStringField;
    cdsNotaFiscalNFECHAVEACESSO: TStringField;
    cdsNotaFiscalNFEPROTOCOLO_CANCELADA: TStringField;
    cdsNotaFiscalTIPO_ENVIONFE: TStringField;
    cdsNotaFiscalNFECODBARRA_CONTINGENCIA: TStringField;
    cdsNotaFiscalNFEVERSAO: TStringField;
    cdsNotaFiscalNFEFINALIDADE: TStringField;
    cdsNotaFiscalNFEAMBIENTE: TStringField;
    cdsNotaFiscalNUMNOTACOPIADA: TIntegerField;
    cdsNotaFiscalSERIECOPIADA: TStringField;
    cdsNotaFiscalDTCONTINGENCIA: TDateField;
    cdsNotaFiscalHRCONTINGENCIA: TTimeField;
    cdsNotaFiscalMOTIVO_CONTINGENCIA: TStringField;
    cdsNotaFiscalNFEVERSAOEMISSAO: TStringField;
    cdsNotaFiscalID_REGIMETRIB: TIntegerField;
    cdsNotaFiscalRNTC: TStringField;
    cdsNotaFiscalVAGAOBALSA_IDENTIF: TStringField;
    cdsNotaFiscalVAGAOBALSA_TIPOIDENTIF: TStringField;
    cdsNotaFiscalUFEMBEXPORTACAO: TStringField;
    cdsNotaFiscalLOCALEMBEXPORTACAO: TStringField;
    cdsNotaFiscalPISCOFINS_SOMAROUTRASDESP: TStringField;
    cdsNotaFiscalTIPO_DESCONTO: TStringField;
    cdsNotaFiscalGERARDUPL_OUTROSVALORES: TStringField;
    cdsNotaFiscalGERARDUPL_FRETE: TStringField;
    cdsNotaFiscalGERARDUPL_SEGURO: TStringField;
    cdsNotaFiscalINFORMADO_NUMNOTAMANUAL: TStringField;
    cdsNotaFiscalNFEDENEGADA: TStringField;
    cdsNotaFiscalMOTIVO_DENEGADA: TStringField;
    cdsNotaFiscalDADOS_ADICIONAIS: TMemoField;
    cdsNotaFiscalDTINICIO_DUPLICATA: TDateField;
    cdsNotaFiscalTIPO_PRAZO: TStringField;
    cdsNotaFiscalPERC_COMISSAO: TFloatField;
    cdsNotaFiscalSIMPLES_FILIAL: TStringField;
    cdsNotaFiscalID_OPERACAO_NOTA: TIntegerField;
    cdsNotaFiscalFINALIDADE: TStringField;
    cdsNotaFiscalID_VARIACAO: TIntegerField;
    cdsNotaFiscalSTATUS_MANIFESTO: TStringField;
    cdsNotaFiscalID_CONTA: TIntegerField;
    cdsNotaFiscalID_TIPO_COBRANCA: TIntegerField;
    cdsNotaFiscalCALCULAR_IMP_ITEM: TStringField;
    cdsNotaFiscalGRAVOU_DADOSADICIONAIS: TStringField;
    cdsNotaFiscalVLR_TRIBUTOS: TFloatField;
    cdsNotaFiscalUSA_TRANSFICMS: TStringField;
    cdsNotaFiscalID_NOTACOPIADA: TIntegerField;
    cdsNotaFiscalID_CONTA_ORCAMENTO: TIntegerField;
    cdsNotaFiscalNOTA_ESTORNO: TStringField;
    cdsNotaFiscalCOD_MODELO: TStringField;
    cdsNotaFiscalCOD_CONS_EE: TStringField;
    cdsNotaFiscalCOD_CONS_AGUA: TStringField;
    cdsNotaFiscalNOME_CLIENTE: TStringField;
    sdsNotaFiscalCODCFOP: TStringField;
    cdsNotaFiscalCODCFOP: TStringField;
    sdsFilial: TSQLDataSet;
    sdsFilialID: TIntegerField;
    sdsFilialNOME: TStringField;
    dspFilial: TDataSetProvider;
    cdsFilial: TClientDataSet;
    cdsFilialID: TIntegerField;
    cdsFilialNOME: TStringField;
    dsFilial: TDataSource;
    qParametros: TSQLQuery;
    qParametrosENDXMLNFE: TStringField;
    qParametrosENDPDFNFE: TStringField;
    sdsNota_Fiscal_EletronicaXML_ASSINADO_PROC: TMemoField;
    cdsNota_Fiscal_EletronicaXML_ASSINADO_PROC: TMemoField;
    sdsCupom: TSQLDataSet;
    dspCupom: TDataSetProvider;
    cdsCupom: TClientDataSet;
    dsCupom: TDataSource;
    cdsCupomID: TIntegerField;
    cdsCupomNUMCUPOM: TIntegerField;
    cdsCupomDTEMISSAO: TDateField;
    cdsCupomHREMISSAO: TTimeField;
    cdsCupomID_CLIENTE: TIntegerField;
    cdsCupomTIPO_PGTO: TStringField;
    cdsCupomID_CONDPGTO: TIntegerField;
    cdsCupomID_VENDEDOR: TIntegerField;
    cdsCupomPERC_VENDEDOR: TFloatField;
    cdsCupomBASE_ICMS: TFloatField;
    cdsCupomVLR_ICMS: TFloatField;
    cdsCupomVLR_PRODUTOS: TFloatField;
    cdsCupomVLR_DESCONTO: TFloatField;
    cdsCupomVLR_TOTAL: TFloatField;
    cdsCupomCANCELADO: TStringField;
    cdsCupomVLR_RECEBIDO: TFloatField;
    cdsCupomVLR_TROCO: TFloatField;
    cdsCupomID_CONTA: TIntegerField;
    cdsCupomFILIAL: TIntegerField;
    cdsCupomID_TIPOCOBRANCA: TIntegerField;
    cdsCupomCPF: TStringField;
    cdsCupomTIPO: TStringField;
    cdsCupomTERMINAL_ID: TSmallintField;
    cdsCupomVLR_TRIBUTO: TFloatField;
    cdsCupomVLR_TRIBUTO_FEDERAL: TFloatField;
    cdsCupomVLR_TRIBUTO_ESTADUAL: TFloatField;
    cdsCupomVLR_TRIBUTO_MUNICIPAL: TFloatField;
    cdsCupomNUM_CARTAO: TSmallintField;
    cdsCupomCLIENTE_NOME: TStringField;
    cdsCupomNFEAMBIENTE: TStringField;
    cdsCupomNFECHAVEACESSO: TStringField;
    cdsCupomNFEPROTOCOLO: TStringField;
    cdsCupomNFERECIBO: TStringField;
    cdsCupomNFEVERSAO: TStringField;
    cdsCupomTIPO_ATENDIMENTO: TSmallintField;
    cdsCupomTIPO_IMPRESSAO_NFCE: TSmallintField;
    cdsCupomTIPO_ENVIONFE: TStringField;
    cdsCupomNFEPROTOCOLO_CANCELADA: TStringField;
    cdsCupomID_CFOP: TIntegerField;
    cdsCupomTIPO_DESCONTO: TStringField;
    cdsCupomVLR_IPI: TFloatField;
    cdsCupomVLR_PIS: TFloatField;
    cdsCupomVLR_COFINS: TFloatField;
    cdsCupomMOTIVO_CANCELADA: TStringField;
    cdsCupomDADOS_ADICIONAIS: TMemoField;
    cdsCupomFONTE_TRIBUTOS: TStringField;
    cdsCupomNFEDENEGADA: TStringField;
    cdsCupomNFEFINALIDADE: TStringField;
    cdsCupomSERIE: TStringField;
    cdsCupomTIPO_DESTINO_OPERACAO: TSmallintField;
    cdsCupomMOTIVO_DENEGADO: TStringField;
    cdsCupomQTD_PESSOA: TIntegerField;
    cdsCupomID_FECHAMENTO: TIntegerField;
    cdsCupomCLIENTE_FONE: TStringField;
    cdsCupomCLIENTE_ENDERECO: TStringField;
    cdsCupomCLIENTE_OBS: TStringField;
    cdsCupomID_TRANSPORTADORA: TIntegerField;
    cdsCupomID_LOCALESTOQUE: TIntegerField;
    cdsCupomESTOQUE_OK: TStringField;
    cdsCupomFINANCEIRO_OK: TStringField;
    cdsCupomNOME_CLIENTE: TStringField;
    cdsCupomCODCFOP: TStringField;
    qParametrosENDXMLNFCE: TStringField;
    qParametrosENDPDFNFCE: TStringField;
    procedure dspNota_Fiscal_EletronicaUpdateError(Sender: TObject;
      DataSet: TCustomClientDataSet; E: EUpdateError;
      UpdateKind: TUpdateKind; var Response: TResolverResponse);
    procedure DataModuleCreate(Sender: TObject);
    procedure DataModuleDestroy(Sender: TObject);
  private
    { Private declarations }

  public
    { Public declarations }
    ctNotaEletronica : String;
    ctNotaFiscal : String;
    ctCupom : String;

  end;

var
  DMConsNotaEletronica: TDMConsNotaEletronica;

implementation

uses DmdDatabase_NFeBD, DmdDatabase, SyncObjs;

{$R *.dfm}


procedure TDMConsNotaEletronica.dspNota_Fiscal_EletronicaUpdateError(Sender: TObject;
  DataSet: TCustomClientDataSet; E: EUpdateError; UpdateKind: TUpdateKind;
  var Response: TResolverResponse);
begin
  dmDatabase_NFeBD.prc_UpdateError(DataSet.Name,UpdateKind,E);
end;

procedure TDMConsNotaEletronica.DataModuleCreate(Sender: TObject);
begin
  dmDatabase_NFeBD := TdmDatabase_NFeBD.Create(Self);
  ctNotaFiscal := sdsNotaFiscal.CommandText;
  ctCupom      := sdsCupom.CommandText;
  cdsFilial.Open;
  qParametros.Open;
end;

procedure TDMConsNotaEletronica.DataModuleDestroy(Sender: TObject);
begin
  FreeAndNil(dmDatabase_NFeBD);
end;

end.
