unit UDMCopiarProduto;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr, dbXPress;

type
  TDMCopiarProduto = class(TDataModule)
    sdsProduto: TSQLDataSet;
    dspProduto: TDataSetProvider;
    cdsProduto: TClientDataSet;
    dsProduto: TDataSource;
    sdsProdutoID: TIntegerField;
    sdsProdutoREFERENCIA: TStringField;
    sdsProdutoNOME: TStringField;
    sdsProdutoPESOLIQUIDO: TFloatField;
    sdsProdutoPESOBRUTO: TFloatField;
    sdsProdutoINATIVO: TStringField;
    sdsProdutoID_CSTIPI: TIntegerField;
    sdsProdutoPERC_IPI: TFloatField;
    sdsProdutoPRECO_CUSTO: TFloatField;
    sdsProdutoPRECO_VENDA: TFloatField;
    sdsProdutoTIPO_REG: TStringField;
    sdsProdutoPOSSE_MATERIAL: TStringField;
    sdsProdutoESTOQUE: TStringField;
    sdsProdutoMATERIAL_OUTROS: TStringField;
    sdsProdutoUSUARIO: TStringField;
    sdsProdutoDTCAD: TDateField;
    sdsProdutoHRCAD: TTimeField;
    sdsProdutoCA: TStringField;
    sdsProdutoCOMPLEMENTO: TStringField;
    sdsProdutoID_NCM: TIntegerField;
    sdsProdutoORIGEM_PROD: TStringField;
    sdsProdutoOBS: TMemoField;
    sdsProdutoCODSITCF: TStringField;
    cdsProdutoID: TIntegerField;
    cdsProdutoREFERENCIA: TStringField;
    cdsProdutoNOME: TStringField;
    cdsProdutoPESOLIQUIDO: TFloatField;
    cdsProdutoPESOBRUTO: TFloatField;
    cdsProdutoINATIVO: TStringField;
    cdsProdutoID_CSTIPI: TIntegerField;
    cdsProdutoPERC_IPI: TFloatField;
    cdsProdutoPRECO_CUSTO: TFloatField;
    cdsProdutoPRECO_VENDA: TFloatField;
    cdsProdutoTIPO_REG: TStringField;
    cdsProdutoPOSSE_MATERIAL: TStringField;
    cdsProdutoESTOQUE: TStringField;
    cdsProdutoMATERIAL_OUTROS: TStringField;
    cdsProdutoUSUARIO: TStringField;
    cdsProdutoDTCAD: TDateField;
    cdsProdutoHRCAD: TTimeField;
    cdsProdutoCA: TStringField;
    cdsProdutoCOMPLEMENTO: TStringField;
    cdsProdutoID_NCM: TIntegerField;
    cdsProdutoORIGEM_PROD: TStringField;
    cdsProdutoOBS: TMemoField;
    cdsProdutoCODSITCF: TStringField;
    sdsProdutoPERC_REDUCAOICMS: TFloatField;
    sdsProdutoTIPO_VENDA: TStringField;
    cdsProdutoPERC_REDUCAOICMS: TFloatField;
    cdsProdutoTIPO_VENDA: TStringField;
    sdsProdutoPERC_MARGEMLUCRO: TFloatField;
    cdsProdutoPERC_MARGEMLUCRO: TFloatField;
    sdsProdutoUNIDADE: TStringField;
    cdsProdutoUNIDADE: TStringField;
    dsProduto_Mestre: TDataSource;
    sdsProdutoDT_ALTPRECO: TDateField;
    cdsProdutoDT_ALTPRECO: TDateField;
    sdsProduto_Consumo: TSQLDataSet;
    cdsProduto_Consumo: TClientDataSet;
    dsProduto_Consumo: TDataSource;
    sdsProduto_ConsumoID: TIntegerField;
    sdsProduto_ConsumoITEM: TIntegerField;
    sdsProduto_ConsumoID_MATERIAL: TIntegerField;
    sdsProduto_ConsumoQTD_CONSUMO: TFloatField;
    sdsProduto_ConsumoQTD_UNIDADE: TFloatField;
    sdsProduto_ConsumoUNIDADE: TStringField;
    sdsProduto_ConsumoNOMEMATERIAL: TStringField;
    cdsProdutosdsProduto_Consumo: TDataSetField;
    cdsProduto_ConsumoID: TIntegerField;
    cdsProduto_ConsumoITEM: TIntegerField;
    cdsProduto_ConsumoID_MATERIAL: TIntegerField;
    cdsProduto_ConsumoQTD_CONSUMO: TFloatField;
    cdsProduto_ConsumoQTD_UNIDADE: TFloatField;
    cdsProduto_ConsumoUNIDADE: TStringField;
    cdsProduto_ConsumoNOMEMATERIAL: TStringField;
    sdsProduto_ConsumoREFERENCIA: TStringField;
    cdsProduto_ConsumoREFERENCIA: TStringField;
    sdsProdutoLOCALIZACAO: TStringField;
    cdsProdutoLOCALIZACAO: TStringField;
    sdsProdutoID_GRUPO: TIntegerField;
    sdsProdutoID_SUBGRUPO: TIntegerField;
    sdsProdutoID_MARCA: TIntegerField;
    cdsProdutoID_GRUPO: TIntegerField;
    cdsProdutoID_SUBGRUPO: TIntegerField;
    cdsProdutoID_MARCA: TIntegerField;
    sdsProdutoID_FORNECEDOR: TIntegerField;
    cdsProdutoID_FORNECEDOR: TIntegerField;
    sdsProdutoCOD_BARRA: TStringField;
    cdsProdutoCOD_BARRA: TStringField;
    sdsProdutoPERC_IMPORTACAO: TFloatField;
    cdsProdutoPERC_IMPORTACAO: TFloatField;
    sdsProduto_ConsumoPRECO_CUSTO: TFloatField;
    cdsProduto_ConsumoPRECO_CUSTO: TFloatField;
    cdsProduto_ConsumoclVlr_Total: TFloatField;
    sdsProdutoPERC_REDUCAOICMSSUBST: TFloatField;
    cdsProdutoPERC_REDUCAOICMSSUBST: TFloatField;
    sdsProdutoUSA_GRADE: TStringField;
    cdsProdutoUSA_GRADE: TStringField;
    sdsProduto_Tam: TSQLDataSet;
    cdsProduto_Tam: TClientDataSet;
    dsProduto_Tam: TDataSource;
    sdsProduto_TamID: TIntegerField;
    sdsProduto_TamTAMANHO: TStringField;
    cdsProdutosdsProduto_Tam: TDataSetField;
    cdsProduto_TamID: TIntegerField;
    cdsProduto_TamTAMANHO: TStringField;
    sdsProdutoID_GRADE: TIntegerField;
    cdsProdutoID_GRADE: TIntegerField;
    sdsProdutoUSA_PERC_IMP_INTERESTADUAL: TStringField;
    cdsProdutoUSA_PERC_IMP_INTERESTADUAL: TStringField;
    sdsProdutoIMPRIMIR_ETIQUETA_NAV: TStringField;
    cdsProdutoIMPRIMIR_ETIQUETA_NAV: TStringField;
    sdsProduto_ConsumoID_POSICAO: TIntegerField;
    cdsProduto_ConsumoID_POSICAO: TIntegerField;
    sdsProduto_ConsumoNOME_POSICAO: TStringField;
    cdsProduto_ConsumoNOME_POSICAO: TStringField;
    sdsProduto_Consumo_Tam: TSQLDataSet;
    cdsProduto_Consumo_Tam: TClientDataSet;
    dsProduto_Consumo_Tam: TDataSource;
    dsProduto_Consumo_Mestre: TDataSource;
    sdsProduto_Consumo_TamID: TIntegerField;
    sdsProduto_Consumo_TamITEM: TIntegerField;
    sdsProduto_Consumo_TamTAMANHO: TStringField;
    sdsProduto_Consumo_TamQTD_CONSUMO: TFloatField;
    cdsProduto_ConsumosdsProduto_Consumo_Tam: TDataSetField;
    cdsProduto_Consumo_TamID: TIntegerField;
    cdsProduto_Consumo_TamITEM: TIntegerField;
    cdsProduto_Consumo_TamTAMANHO: TStringField;
    cdsProduto_Consumo_TamQTD_CONSUMO: TFloatField;
    sdsProduto_ConsumoTIPO_CONSUMO: TStringField;
    cdsProduto_ConsumoTIPO_CONSUMO: TStringField;
    sdsProdutoCARIMBO: TStringField;
    sdsProdutoPERC_QUEBRAMAT: TFloatField;
    cdsProdutoCARIMBO: TStringField;
    cdsProdutoPERC_QUEBRAMAT: TFloatField;
    sdsProdutoSPED_TIPO_ITEM: TStringField;
    sdsProdutoQTD_ESTOQUE_MIN: TFloatField;
    sdsProdutoPERC_PIS: TFloatField;
    sdsProdutoPERC_COFINS: TFloatField;
    sdsProdutoPERC_ICMS_IMP: TFloatField;
    sdsProdutoPERC_IPI_IMP: TFloatField;
    cdsProdutoSPED_TIPO_ITEM: TStringField;
    cdsProdutoQTD_ESTOQUE_MIN: TFloatField;
    cdsProdutoPERC_PIS: TFloatField;
    cdsProdutoPERC_COFINS: TFloatField;
    cdsProdutoPERC_ICMS_IMP: TFloatField;
    cdsProdutoPERC_IPI_IMP: TFloatField;
    sdsProduto_ConsumoIMP_ROTULO: TStringField;
    sdsProduto_ConsumoIMP_TALAO: TStringField;
    cdsProduto_ConsumoIMP_ROTULO: TStringField;
    cdsProduto_ConsumoIMP_TALAO: TStringField;
    sdsProduto_TamPESO_LIQUIDO: TFloatField;
    sdsProduto_TamPESO_BRUTO: TFloatField;
    cdsProduto_TamPESO_LIQUIDO: TFloatField;
    cdsProduto_TamPESO_BRUTO: TFloatField;
    sdsProdutoREFERENCIA_PADRAO: TStringField;
    sdsProdutoNCM_EX: TStringField;
    sdsProdutoID_SITTRIB_CF: TIntegerField;
    cdsProdutoREFERENCIA_PADRAO: TStringField;
    cdsProdutoNCM_EX: TStringField;
    cdsProdutoID_SITTRIB_CF: TIntegerField;
    sdsProduto_Cor: TSQLDataSet;
    sdsProduto_CorID: TIntegerField;
    sdsProduto_CorITEM: TIntegerField;
    sdsProduto_CorID_COR: TIntegerField;
    sdsProduto_CorNOME: TStringField;
    sdsProduto_CorINATIVO: TStringField;
    sdsProduto_CorTIPO_REG: TStringField;
    sdsProduto_CorPRECO_CUSTO: TFloatField;
    sdsProduto_CorPRECO_VENDA: TFloatField;
    sdsProduto_CorPERC_MARGEMLUCRO: TFloatField;
    sdsProduto_CorID_COR_COMBINACAO: TIntegerField;
    dspProduto_Cor: TDataSetProvider;
    cdsProduto_Cor: TClientDataSet;
    cdsProduto_CorID: TIntegerField;
    cdsProduto_CorITEM: TIntegerField;
    cdsProduto_CorID_COR: TIntegerField;
    cdsProduto_CorNOME: TStringField;
    cdsProduto_CorINATIVO: TStringField;
    cdsProduto_CorTIPO_REG: TStringField;
    cdsProduto_CorPRECO_CUSTO: TFloatField;
    cdsProduto_CorPRECO_VENDA: TFloatField;
    cdsProduto_CorPERC_MARGEMLUCRO: TFloatField;
    cdsProduto_CorID_COR_COMBINACAO: TIntegerField;
    dsProduto_Cor: TDataSource;
    sdsProduto_Comb: TSQLDataSet;
    sdsProduto_CombID: TIntegerField;
    sdsProduto_CombITEM: TIntegerField;
    sdsProduto_CombID_COR: TIntegerField;
    sdsProduto_CombNOME: TStringField;
    sdsProduto_CombINATIVO: TStringField;
    sdsProduto_CombTIPO_REG: TStringField;
    sdsProduto_CombPRECO_CUSTO: TFloatField;
    sdsProduto_CombPRECO_VENDA: TFloatField;
    sdsProduto_CombPERC_MARGEMLUCRO: TFloatField;
    sdsProduto_CombID_COR_COMBINACAO: TIntegerField;
    dspProduto_Comb: TDataSetProvider;
    cdsProduto_Comb: TClientDataSet;
    cdsProduto_CombID: TIntegerField;
    cdsProduto_CombITEM: TIntegerField;
    cdsProduto_CombID_COR: TIntegerField;
    cdsProduto_CombNOME: TStringField;
    cdsProduto_CombINATIVO: TStringField;
    cdsProduto_CombTIPO_REG: TStringField;
    cdsProduto_CombPRECO_CUSTO: TFloatField;
    cdsProduto_CombPRECO_VENDA: TFloatField;
    cdsProduto_CombPERC_MARGEMLUCRO: TFloatField;
    cdsProduto_CombsdsProduto_Comb_Mat: TDataSetField;
    cdsProduto_CombID_COR_COMBINACAO: TIntegerField;
    dsProduto_Comb: TDataSource;
    dsProduto_Comb_Mestre: TDataSource;
    sdsProduto_Comb_Mat: TSQLDataSet;
    sdsProduto_Comb_MatID: TIntegerField;
    sdsProduto_Comb_MatITEM: TIntegerField;
    sdsProduto_Comb_MatITEM_MAT: TIntegerField;
    sdsProduto_Comb_MatID_POSICAO: TIntegerField;
    sdsProduto_Comb_MatID_MATERIAL: TIntegerField;
    sdsProduto_Comb_MatID_COR: TIntegerField;
    sdsProduto_Comb_MatQTD_CONSUMO: TFloatField;
    sdsProduto_Comb_MatQTD_UNIDADE: TFloatField;
    sdsProduto_Comb_MatUNIDADE: TStringField;
    sdsProduto_Comb_MatTINGIMENTO: TStringField;
    sdsProduto_Comb_MatIMP_TALAO: TStringField;
    cdsProduto_Comb_Mat: TClientDataSet;
    cdsProduto_Comb_MatID: TIntegerField;
    cdsProduto_Comb_MatITEM: TIntegerField;
    cdsProduto_Comb_MatITEM_MAT: TIntegerField;
    cdsProduto_Comb_MatID_POSICAO: TIntegerField;
    cdsProduto_Comb_MatID_MATERIAL: TIntegerField;
    cdsProduto_Comb_MatID_COR: TIntegerField;
    cdsProduto_Comb_MatclNome_Material: TStringField;
    cdsProduto_Comb_MatclNome_Posicao: TStringField;
    cdsProduto_Comb_MatNOME_COR_COMBINACAO: TStringField;
    cdsProduto_Comb_MatQTD_CONSUMO: TFloatField;
    cdsProduto_Comb_MatQTD_UNIDADE: TFloatField;
    cdsProduto_Comb_MatUNIDADE: TStringField;
    cdsProduto_Comb_MatTINGIMENTO: TStringField;
    cdsProduto_Comb_MatIMP_TALAO: TStringField;
    dsProduto_Comb_Mat: TDataSource;
    sdsSel_Produto: TSQLDataSet;
    dspSel_Produto: TDataSetProvider;
    cdsSel_Produto: TClientDataSet;
    cdsSel_ProdutoID: TIntegerField;
    cdsSel_ProdutoREFERENCIA: TStringField;
    cdsSel_ProdutoNOME: TStringField;
    dsSel_Produto: TDataSource;
    sdsProduto_ConsumoID_SETOR: TIntegerField;
    sdsProduto_ConsumoTINGIMENTO: TStringField;
    cdsProduto_ConsumoID_SETOR: TIntegerField;
    cdsProduto_ConsumoTINGIMENTO: TStringField;
    sdsCopia_Produto_Agrupado: TSQLDataSet;
    dspCopia_Produto_Agrupado: TDataSetProvider;
    cdsCopia_Produto_Agrupado: TClientDataSet;
    dsCopia_Produto_Agrupado: TDataSource;
    sdsCopia_Produto_AgrupadoID: TIntegerField;
    sdsCopia_Produto_AgrupadoREFERENCIA: TStringField;
    sdsCopia_Produto_AgrupadoNOME: TStringField;
    cdsCopia_Produto_AgrupadoID: TIntegerField;
    cdsCopia_Produto_AgrupadoREFERENCIA: TStringField;
    sdsCopia_Produto_Comb: TSQLDataSet;
    cdsCopia_Produto_Comb: TClientDataSet;
    dsCopia_Produto_Comb: TDataSource;
    dspCopia_Produto_Comb: TDataSetProvider;
    sdsCopia_Produto_CombID: TIntegerField;
    sdsCopia_Produto_CombITEM: TIntegerField;
    sdsCopia_Produto_CombID_COR: TIntegerField;
    sdsCopia_Produto_CombNOME: TStringField;
    sdsCopia_Produto_CombINATIVO: TStringField;
    sdsCopia_Produto_CombTIPO_REG: TStringField;
    sdsCopia_Produto_CombPRECO_CUSTO: TFloatField;
    sdsCopia_Produto_CombPRECO_VENDA: TFloatField;
    sdsCopia_Produto_CombPERC_MARGEMLUCRO: TFloatField;
    sdsCopia_Produto_CombID_COR_COMBINACAO: TIntegerField;
    cdsCopia_Produto_CombID: TIntegerField;
    cdsCopia_Produto_CombITEM: TIntegerField;
    cdsCopia_Produto_CombID_COR: TIntegerField;
    cdsCopia_Produto_CombNOME: TStringField;
    cdsCopia_Produto_CombINATIVO: TStringField;
    cdsCopia_Produto_CombTIPO_REG: TStringField;
    cdsCopia_Produto_CombPRECO_CUSTO: TFloatField;
    cdsCopia_Produto_CombPRECO_VENDA: TFloatField;
    cdsCopia_Produto_CombPERC_MARGEMLUCRO: TFloatField;
    cdsCopia_Produto_CombID_COR_COMBINACAO: TIntegerField;
    sdsCopia_Comb_Agrupado: TSQLDataSet;
    cdsCopia_Comb_Agrupado: TClientDataSet;
    dsCopia_Comb_Agrupado: TDataSource;
    dsCopia_Agrupado_Mestre: TDataSource;
    sdsCopia_Comb_AgrupadoID: TIntegerField;
    sdsCopia_Comb_AgrupadoITEM: TIntegerField;
    sdsCopia_Comb_AgrupadoID_COR: TIntegerField;
    sdsCopia_Comb_AgrupadoNOME: TStringField;
    sdsCopia_Comb_AgrupadoINATIVO: TStringField;
    sdsCopia_Comb_AgrupadoTIPO_REG: TStringField;
    sdsCopia_Comb_AgrupadoPRECO_CUSTO: TFloatField;
    sdsCopia_Comb_AgrupadoPRECO_VENDA: TFloatField;
    sdsCopia_Comb_AgrupadoPERC_MARGEMLUCRO: TFloatField;
    sdsCopia_Comb_AgrupadoID_COR_COMBINACAO: TIntegerField;
    cdsCopia_Produto_AgrupadoNOME: TStringField;
    cdsCopia_Produto_AgrupadosdsCopia_Comb_Agrupado: TDataSetField;
    cdsCopia_Comb_AgrupadoID: TIntegerField;
    cdsCopia_Comb_AgrupadoITEM: TIntegerField;
    cdsCopia_Comb_AgrupadoID_COR: TIntegerField;
    cdsCopia_Comb_AgrupadoNOME: TStringField;
    cdsCopia_Comb_AgrupadoINATIVO: TStringField;
    cdsCopia_Comb_AgrupadoTIPO_REG: TStringField;
    cdsCopia_Comb_AgrupadoPRECO_CUSTO: TFloatField;
    cdsCopia_Comb_AgrupadoPRECO_VENDA: TFloatField;
    cdsCopia_Comb_AgrupadoPERC_MARGEMLUCRO: TFloatField;
    cdsCopia_Comb_AgrupadoID_COR_COMBINACAO: TIntegerField;
    qSemi: TSQLQuery;
    qSemiID_MATERIAL: TIntegerField;
    qSemiQTD_CONSUMO: TFloatField;
    sdsProduto_Consumo_Proc: TSQLDataSet;
    sdsProduto_Consumo_ProcID: TIntegerField;
    sdsProduto_Consumo_ProcITEM: TIntegerField;
    sdsProduto_Consumo_ProcITEM_PROC: TIntegerField;
    sdsProduto_Consumo_ProcID_PROCESSO: TIntegerField;
    dspProduto_Consumo_Proc: TDataSetProvider;
    cdsProduto_Consumo_Proc: TClientDataSet;
    cdsProduto_ConsumosdsProduto_Consumo_Proc: TDataSetField;
    cdsProduto_Consumo_ProcID: TIntegerField;
    cdsProduto_Consumo_ProcITEM: TIntegerField;
    cdsProduto_Consumo_ProcITEM_PROC: TIntegerField;
    cdsProduto_Consumo_ProcID_PROCESSO: TIntegerField;
    dsProduto_Consumo_Proc: TDataSource;
    procedure dspProdutoUpdateError(Sender: TObject;
      DataSet: TCustomClientDataSet; E: EUpdateError;
      UpdateKind: TUpdateKind; var Response: TResolverResponse);
  private
    { Private declarations }

  public
    { Public declarations }
    vMsgErro: String;

    procedure prc_Localizar(ID: Integer); //-1 = Inclusão

  end;

var
  DMCopiarProduto: TDMCopiarProduto;

implementation

uses DmdDatabase;

{$R *.dfm}

{ TDMCadPais }

procedure TDMCopiarProduto.prc_Localizar(ID: Integer);
begin
  cdsProduto.Close;
  sdsProduto.ParamByName('ID').AsInteger := ID;
  cdsProduto.Open;
end;

procedure TDMCopiarProduto.dspProdutoUpdateError(Sender: TObject;
  DataSet: TCustomClientDataSet; E: EUpdateError; UpdateKind: TUpdateKind;
  var Response: TResolverResponse);
begin
  dmDatabase.prc_UpdateError(DataSet.Name,UpdateKind,E);
end;

end.
