unit UDMNFe;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr,
  IdBaseComponent, IdCoder, IdCoder3to4, IdCoderMIME, StrUtils;

type
  TDMNFe = class(TDataModule)
    sdsNFe_Email: TSQLDataSet;
    cdsNFe_Email: TClientDataSet;
    dspNFe_Email: TDataSetProvider;
    sdsNFe_EmailID: TIntegerField;
    sdsNFe_EmailNOME: TStringField;
    sdsNFe_EmailEMAIL: TStringField;
    cdsNFe_EmailID: TIntegerField;
    cdsNFe_EmailNOME: TStringField;
    cdsNFe_EmailEMAIL: TStringField;
    qCidade: TSQLQuery;
    qCidadeID: TIntegerField;
    qCidadeNOME: TStringField;
    qCidadeUF: TStringField;
    qCidadeCODMUNICIPIO: TStringField;
    qFilial: TSQLQuery;
    qFilialID: TIntegerField;
    qFilialNOME: TStringField;
    qFilialNOME_INTERNO: TStringField;
    qFilialENDERECO: TStringField;
    qFilialCOMPLEMENTO_END: TStringField;
    qFilialNUM_END: TStringField;
    qFilialBAIRRO: TStringField;
    qFilialCEP: TStringField;
    qFilialID_CIDADE: TIntegerField;
    qFilialCIDADE: TStringField;
    qFilialUF: TStringField;
    qFilialDDD1: TIntegerField;
    qFilialFONE1: TStringField;
    qFilialDDD2: TIntegerField;
    qFilialFONE: TStringField;
    qFilialDDDFAX: TIntegerField;
    qFilialFAX: TStringField;
    qFilialPESSOA: TStringField;
    qFilialCNPJ_CPF: TStringField;
    qFilialINSCR_EST: TStringField;
    qFilialSIMPLES: TStringField;
    qFilialENDLOGO: TStringField;
    qFilialCALCULAR_IPI: TStringField;
    qFilialINATIVO: TStringField;
    qFilialINSCMUNICIPAL: TStringField;
    qFilialCNAE: TStringField;
    qFilialHOMEPAGE: TStringField;
    qFilialUSARICMSSIMPLES: TStringField;
    qFilialID_REGIME_TRIB: TIntegerField;
    qFilialID_PIS: TIntegerField;
    qFilialID_COFINS: TIntegerField;
    qFilialTIPO_PIS: TStringField;
    qFilialTIPO_COFINS: TStringField;
    qFilialPERC_PIS: TFloatField;
    qFilialPERC_COFINS: TFloatField;
    qFilialID_CSTICMS: TIntegerField;
    qFilialID_CSTIPI: TIntegerField;
    qFilialEMAIL_NFE: TStringField;
    qFilialDTESTOQUE: TDateField;
    qUF: TSQLQuery;
    qUFUF: TStringField;
    qUFPERC_ICMS: TFloatField;
    qUFIDPAIS: TIntegerField;
    qUFCODUF: TStringField;
    qUFPERC_ICMS_INTERNO: TFloatField;
    qPais: TSQLQuery;
    qPaisID: TIntegerField;
    qPaisNOME: TStringField;
    qPaisCODPAIS: TStringField;
    qParametros: TSQLQuery;
    qParametrosID: TIntegerField;
    qParametrosENDXMLNFE: TStringField;
    qParametrosENDPDFNFE: TStringField;
    qParametrosSERIENORMAL: TStringField;
    qParametrosSERIECONTINGENCIA: TStringField;
    qParametrosLOCALSERVIDORNFE: TStringField;
    qParametrosEMAILRESPONSAVELSISTEMA: TStringField;
    qParametrosNFEPRODUCAO: TStringField;
    qParametrosANEXARDANFE: TStringField;
    qParametrosVERSAONFE: TStringField;
    qParametrosVERSAOEMISSAONFE: TStringField;
    qParametrosTIPOLOGONFE: TStringField;
    qParametrosAPLICARDESCONTONOICMS: TStringField;
    qParametrosAPLICARDESCONTONOIPI: TStringField;
    qParametrosSOMARNOPROD_FRETE: TStringField;
    qParametrosSOMARNOPROD_OUTRASDESP: TStringField;
    qParametrosSOMARNOPROD_SEGURO: TStringField;
    qParametrosAJUSTELOGONFEAUTOMATICO: TStringField;
    qParametrosINFNUMNOTAMANUAL: TStringField;
    qParametrosOPCAO_DTENTREGAPEDIDO: TStringField;
    qTransportadora: TSQLQuery;
    qTransportadoraCODIGO: TIntegerField;
    qTransportadoraNOME: TStringField;
    qTransportadoraEMAIL_NFE: TStringField;
    qTransportadoraENDERECO: TStringField;
    qTransportadoraNUM_END: TStringField;
    qTransportadoraCOMPLEMENTO_END: TStringField;
    qTransportadoraBAIRRO: TStringField;
    qTransportadoraID_CIDADE: TIntegerField;
    qTransportadoraUF: TStringField;
    qTransportadoraCNPJ_CPF: TStringField;
    qTransportadoraINSCR_EST: TStringField;
    qTransportadoraPESSOA: TStringField;
    qTab_CSTICMS: TSQLQuery;
    qTab_CSTICMSID: TIntegerField;
    qTab_CSTICMSPERCENTUAL: TFloatField;
    qTab_CSTICMSHISTORICO: TMemoField;
    qTab_CSTICMSCOD_CST: TStringField;
    qTab_CSTICMSTIPO: TStringField;
    qTab_CSTICMSNOME: TStringField;
    qTab_CFOP: TSQLQuery;
    qTab_CFOPID: TIntegerField;
    qTab_CFOPCODCFOP: TStringField;
    qTab_CFOPNOME: TStringField;
    qTab_CFOPENTRADASAIDA: TStringField;
    qTab_CFOPGERAR_IPI: TStringField;
    qTab_CFOPGERAR_ICMS: TStringField;
    qTab_CFOPGERAR_DUPLICATA: TStringField;
    qTab_CFOPSOMAR_VLRTOTALPRODUTO: TStringField;
    qTab_CFOPNOME_INTERNO: TStringField;
    qTab_CFOPID_CSTICMS: TIntegerField;
    qTab_CFOPID_CSTIPI: TIntegerField;
    qTab_CFOPCOPIARNOTATRIANGULAR: TStringField;
    qTab_CFOPID_PIS: TIntegerField;
    qTab_CFOPID_COFINS: TIntegerField;
    qTab_CFOPTIPO_PIS: TStringField;
    qTab_CFOPTIPO_COFINS: TStringField;
    qTab_CFOPGERAR_ICMS_SIMPLES: TStringField;
    qTab_CFOPTIPO_EMPRESA: TStringField;
    qTab_CFOPSUBSTITUICAO_TRIB: TStringField;
    qTab_CFOPMVA: TStringField;
    qTab_CFOPPERC_COFINS: TFloatField;
    qTab_CFOPPERC_PIS: TFloatField;
    qTab_CFOPLEI: TMemoField;
    qParametrosOBS_SIMPLES: TStringField;
    qParametrosIMP_OBSSIMPLES: TStringField;
    qCliente: TSQLQuery;
    qClienteCODIGO: TIntegerField;
    qClienteNOME: TStringField;
    qClienteFANTASIA: TStringField;
    qClienteENDERECO: TStringField;
    qClienteCOMPLEMENTO_END: TStringField;
    qClienteNUM_END: TStringField;
    qClienteBAIRRO: TStringField;
    qClienteID_CIDADE: TIntegerField;
    qClienteCIDADE: TStringField;
    qClienteUF: TStringField;
    qClienteCEP: TStringField;
    qClienteDDDFONE1: TIntegerField;
    qClienteTELEFONE1: TStringField;
    qClienteDDDFONE2: TIntegerField;
    qClienteTELEFONE2: TStringField;
    qClienteDDDFAX: TIntegerField;
    qClienteFAX: TStringField;
    qClientePESSOA: TStringField;
    qClienteCNPJ_CPF: TStringField;
    qClienteINSCR_EST: TStringField;
    qClienteENDERECO_ENT: TStringField;
    qClienteCOMPLEMENTO_END_ENT: TStringField;
    qClienteNUM_END_ENT: TStringField;
    qClienteBAIRRO_ENT: TStringField;
    qClienteID_CIDADE_ENT: TIntegerField;
    qClienteCIDADE_ENT: TStringField;
    qClienteCEP_ENT: TStringField;
    qClienteUF_ENT: TStringField;
    qClientePESSOA_ENT: TStringField;
    qClienteCNPJ_CPF_ENT: TStringField;
    qClienteINSC_EST_ENT: TStringField;
    qClienteENDERECO_PGTO: TStringField;
    qClienteCOMPLEMENTO_END_PGTO: TStringField;
    qClienteNUM_END_PGTO: TStringField;
    qClienteBAIRRO_PGTO: TStringField;
    qClienteID_CIDADE_PGTO: TIntegerField;
    qClienteCIDADE_PGTO: TStringField;
    qClienteCEP_PGTO: TStringField;
    qClienteUF_PGTO: TStringField;
    qClienteUSUARIO: TStringField;
    qClienteDTCADASTRO: TDateField;
    qClienteHRCADASTRO: TTimeField;
    qClienteOBS: TMemoField;
    qClienteCAIXAPOSTAL: TStringField;
    qClienteRG: TStringField;
    qClienteID_VENDEDOR: TIntegerField;
    qClienteID_CONDPGTO: TIntegerField;
    qClienteID_CONTABOLETO: TIntegerField;
    qClienteID_TRANSPORTADORA: TIntegerField;
    qClienteID_TIPOCOBRANCA: TIntegerField;
    qClienteID_REDESPACHO: TIntegerField;
    qClienteID_PAIS: TIntegerField;
    qClientePERC_COMISSAO: TFloatField;
    qClienteDDD_ENT: TIntegerField;
    qClienteFONE_ENT: TStringField;
    qClienteDDD_PGTO: TIntegerField;
    qClienteFONE_PGTO: TStringField;
    qClienteINATIVO: TStringField;
    qClienteHOMEPAGE: TStringField;
    qClienteTIPO_FRETE: TStringField;
    qClienteNOME_ENTREGA: TStringField;
    qClienteEMAIL_NFE: TStringField;
    qClienteEMAIL_PGTO: TStringField;
    qClienteEMAIL_NFE2: TStringField;
    qClientePESSOA_PGTO: TStringField;
    qClienteCNPJ_CPG_PGTO: TStringField;
    qClienteINSC_EST_PGTO: TStringField;
    qClienteUF_PLACA: TStringField;
    qClientePLACA: TStringField;
    qClienteTP_CLIENTE: TStringField;
    qClienteTP_FORNECEDOR: TStringField;
    qClienteTP_TRANSPORTADORA: TStringField;
    qClienteTP_VENDEDOR: TStringField;
    qTipoCobranca: TSQLQuery;
    qTipoCobrancaID: TIntegerField;
    qTipoCobrancaNOME: TStringField;
    qTipoCobrancaDESCONTADO: TStringField;
    qTipoCobrancaDEPOSITO: TStringField;
    qTipoCobrancaGERARBOLETO: TStringField;
    qTipoCobrancaQTDDIAS: TIntegerField;
    qTipoCobrancaCARTAOCREDITO: TStringField;
    qTipoCobrancaCHEQUE: TStringField;
    qTipoCobrancaDINHEIRO: TStringField;
    qTipoCobrancaMOSTRARNOCUPOM: TStringField;
    qContas: TSQLQuery;
    qParametrosIMP_REFERENCIANANOTA: TStringField;
    qNotaEntrada_Itens: TSQLQuery;
    qParametrosENVIARNOTABENEF_NANFE: TStringField;
    qNotaFiscal: TSQLQuery;
    qNotaFiscalID: TIntegerField;
    qNotaFiscalNUMNOTA: TIntegerField;
    qNotaFiscalSERIE: TStringField;
    qNotaFiscalNFECHAVEACESSO: TStringField;
    qNotaFiscalDTEMISSAO: TDateField;
    mParcelaNFe: TClientDataSet;
    mParcelaNFeNumNota: TIntegerField;
    mParcelaNFeParcela: TIntegerField;
    mParcelaNFeValor: TFloatField;
    mParcelaNFeDtVencimento: TStringField;
    dsmiItensNFe: TDataSource;
    mItensNFe: TClientDataSet;
    mItensNFeFilial: TIntegerField;
    mItensNFeNumNota: TIntegerField;
    mItensNFeItemNota: TIntegerField;
    mItensNFeCodProduto: TStringField;
    mItensNFeCodNatOper: TStringField;
    mItensNFeNomeProduto: TStringField;
    mItensNFeQtd: TFloatField;
    mItensNFeUnidade: TStringField;
    mItensNFeVlrUnitario: TFloatField;
    mItensNFeVlrTotal: TFloatField;
    mItensNFeAliqIcms: TFloatField;
    mItensNFeAliqIpi: TFloatField;
    mItensNFeVlrIcms: TFloatField;
    mItensNFeVlrIpi: TFloatField;
    mItensNFeAliqSitTrib: TFloatField;
    mItensNFeClasFiscalRed: TStringField;
    mItensNFeClasFiscal: TStringField;
    mItensNFeInfAdicionais: TMemoField;
    mItensNFeVlrDesconto: TFloatField;
    mItensNFePercRedICMS: TFloatField;
    mItensNFeVlrBaseICMS: TFloatField;
    mItensNFeBaseICMS: TFloatField;
    mItensNFeCodCSTIPI: TStringField;
    mItensNFeTipoReg: TStringField;
    mItensNFeAliqPis: TFloatField;
    mItensNFeAliqCofins: TFloatField;
    mItensNFeVlrPis: TFloatField;
    mItensNFeVlrCofins: TFloatField;
    mItensNFeIcmsBaseSubst: TFloatField;
    mItensNFeIcmsVlrSubst: TFloatField;
    mItensNFeCodPis: TStringField;
    mItensNFeCodCofins: TStringField;
    mItensNFeTipoPis: TStringField;
    mItensNFeTipoCofins: TStringField;
    mItensNFeCodSitTrib: TStringField;
    mItensNFePedidoCliente: TStringField;
    mItensNFeItemPedido: TIntegerField;
    mItensNFeVlrIcmsSimples: TFloatField;
    mItensNFeBaseIcmsSimples: TFloatField;
    mItensNFeMVA: TFloatField;
    mItensNFeSomaVlrTotalProd: TBooleanField;
    mItensNFeVlrFrete: TFloatField;
    mItensNFeVlrSeguro: TFloatField;
    mItensNFeVlrOutrasDespesas: TFloatField;
    mItensNFeCodBarra: TStringField;
    mItensNFeVlrBaseImportacao: TFloatField;
    mItensNFeVlrImportacao: TFloatField;
    mItensNFeVlrIOF: TFloatField;
    mItensNFeVlrDespAduaneira: TFloatField;
    mAuxDadosNFe: TClientDataSet;
    mAuxDadosNFeTipo: TStringField;
    mAuxDadosNFeCodigo: TStringField;
    mDadosAdicionaisNFe: TClientDataSet;
    mDadosAdicionaisNFeID: TIntegerField;
    mDadosAdicionaisNFeObs: TMemoField;
    mDadosAdicionaisNFeObsAux: TMemoField;
    mNotaDevolvidaNFe: TClientDataSet;
    mNotaDevolvidaNFeTipo: TStringField;
    mNotaDevolvidaNFeItem: TIntegerField;
    mNotaDevolvidaNFeNumNota: TIntegerField;
    mNotaDevolvidaNFeParcialTotal: TStringField;
    mNotaDevolvidaNFeQtd: TFloatField;
    mNotaDevolvidaNFeUnidade: TStringField;
    mNotaDevolvidaNFeCodForn: TIntegerField;
    mNotaDevolvidaNFeNomeForn: TStringField;
    mNotaDevolvidaNFeTriangular: TBooleanField;
    mNotaDevolvidaNFeCNPJ: TStringField;
    mNotaDevolvidaNFeCodUF: TStringField;
    mNotaDevolvidaNFeSerie: TStringField;
    mNotaDevolvidaNFeModelo: TStringField;
    mNotaDevolvidaNFeNFeChaveAcesso: TStringField;
    mNotaDevolvidaNFeCupomNumECF: TIntegerField;
    mNotaDevolvidaNFeCupomNumCOO: TIntegerField;
    mNotaDevolvidaNFeCupomModelo: TStringField;
    mNotaDevolvidaNFeAnoEmissao: TIntegerField;
    mNotaDevolvidaNFeMesEmissao: TIntegerField;
    mNotaDevolvidaNFeIE: TStringField;
    sdsNotaFiscal: TSQLDataSet;
    dspNotaFiscal: TDataSetProvider;
    cdsNotaFiscal: TClientDataSet;
    dsNotaFiscal: TDataSource;
    sdsNotaFiscalID: TIntegerField;
    sdsNotaFiscalFILIAL: TIntegerField;
    sdsNotaFiscalSERIE: TStringField;
    sdsNotaFiscalNUMNOTA: TIntegerField;
    sdsNotaFiscalDTEMISSAO: TDateField;
    sdsNotaFiscalID_CFOP: TIntegerField;
    sdsNotaFiscalID_CLIENTE: TIntegerField;
    sdsNotaFiscalID_CONDPGTO: TIntegerField;
    sdsNotaFiscalID_VENDEDOR: TIntegerField;
    sdsNotaFiscalBASE_ICMS: TFloatField;
    sdsNotaFiscalVLR_ICMS: TFloatField;
    sdsNotaFiscalVLR_IPI: TFloatField;
    sdsNotaFiscalVLR_NOTA: TFloatField;
    sdsNotaFiscalVLR_ITENS: TFloatField;
    sdsNotaFiscalVLR_DUPLICATA: TFloatField;
    sdsNotaFiscalVLR_ENTRADA: TFloatField;
    sdsNotaFiscalPERC_DESCONTO: TFloatField;
    sdsNotaFiscalVLR_DESCONTO: TFloatField;
    sdsNotaFiscalVLR_FRETE: TFloatField;
    sdsNotaFiscalVLR_SEGURO: TFloatField;
    sdsNotaFiscalVLR_OUTRASDESP: TFloatField;
    sdsNotaFiscalBASE_ICMSTRANSF: TFloatField;
    sdsNotaFiscalPERC_TRANSF: TFloatField;
    sdsNotaFiscalVLR_TRANSF: TFloatField;
    sdsNotaFiscalVLR_PIS: TFloatField;
    sdsNotaFiscalVLR_COFINS: TFloatField;
    sdsNotaFiscalVLR_TAXACISCOMEX: TFloatField;
    sdsNotaFiscalVLR_OUTROS: TFloatField;
    sdsNotaFiscalBASE_ICMSSIMPLES: TFloatField;
    sdsNotaFiscalVLR_ICMSSIMPLES: TFloatField;
    sdsNotaFiscalPERC_ICMSSIMPLES: TFloatField;
    sdsNotaFiscalVLR_IMPORTACAO: TFloatField;
    sdsNotaFiscalBASE_ICMSSUBST: TFloatField;
    sdsNotaFiscalVLR_ICMSSUBST: TFloatField;
    sdsNotaFiscalBASE_ICMSOUTROS: TFloatField;
    sdsNotaFiscalVLR_ICMSOUTROS: TFloatField;
    sdsNotaFiscalVLR_DUPLICATAOUTROS: TFloatField;
    sdsNotaFiscalVLR_ADUANEIRA: TFloatField;
    sdsNotaFiscalPERC_ICMS_PISCOFINS: TFloatField;
    sdsNotaFiscalPERC_ICMS_OUTROSVALORES: TFloatField;
    sdsNotaFiscalPERC_ICMS_FRETE: TFloatField;
    sdsNotaFiscalPERC_DESCONTOORIG: TFloatField;
    sdsNotaFiscalQTDVOLUME: TIntegerField;
    sdsNotaFiscalESPECIE: TStringField;
    sdsNotaFiscalMARCA: TStringField;
    sdsNotaFiscalNUMEROVOLUME: TStringField;
    sdsNotaFiscalPESOBRUTO: TFloatField;
    sdsNotaFiscalPESOLIQUIDO: TFloatField;
    sdsNotaFiscalPLACA: TStringField;
    sdsNotaFiscalUFPLACA: TStringField;
    sdsNotaFiscalTIPO_FRETE: TStringField;
    sdsNotaFiscalID_TRANSPORTADORA: TIntegerField;
    sdsNotaFiscalID_REDESPACHO: TIntegerField;
    sdsNotaFiscalTIPO_NOTA: TStringField;
    sdsNotaFiscalCANCELADA: TStringField;
    sdsNotaFiscalMOTIVO_CANCELADA: TStringField;
    sdsNotaFiscalDTSAIDAENTRADA: TDateField;
    sdsNotaFiscalHRSAIDAENTRADA: TTimeField;
    sdsNotaFiscalID_BANCO: TIntegerField;
    sdsNotaFiscalLOCALENTREGA: TStringField;
    sdsNotaFiscalID_EXTCOMISSAO: TIntegerField;
    sdsNotaFiscalDESCRICAO_DESC: TStringField;
    sdsNotaFiscalID_CLIENTETRIANG: TIntegerField;
    sdsNotaFiscalQTDTOTAL_ITENS: TIntegerField;
    sdsNotaFiscalNFERECIBO: TStringField;
    sdsNotaFiscalNFEPROTOCOLO: TStringField;
    sdsNotaFiscalNFECHAVEACESSO: TStringField;
    sdsNotaFiscalNFEPROTOCOLO_CANCELADA: TStringField;
    sdsNotaFiscalTIPO_ENVIONFE: TStringField;
    sdsNotaFiscalNFECODBARRA_CONTINGENCIA: TStringField;
    sdsNotaFiscalNFEVERSAO: TStringField;
    sdsNotaFiscalNFEFINALIDADE: TStringField;
    sdsNotaFiscalNFEAMBIENTE: TStringField;
    sdsNotaFiscalNUMNOTACOPIADA: TIntegerField;
    sdsNotaFiscalSERIECOPIADA: TStringField;
    sdsNotaFiscalDTCONTINGENCIA: TDateField;
    sdsNotaFiscalHRCONTINGENCIA: TTimeField;
    sdsNotaFiscalMOTIVO_CONTINGENCIA: TStringField;
    sdsNotaFiscalNFEVERSAOEMISSAO: TStringField;
    sdsNotaFiscalID_REGIMETRIB: TIntegerField;
    sdsNotaFiscalRNTC: TStringField;
    sdsNotaFiscalVAGAOBALSA_IDENTIF: TStringField;
    sdsNotaFiscalVAGAOBALSA_TIPOIDENTIF: TStringField;
    sdsNotaFiscalUFEMBEXPORTACAO: TStringField;
    sdsNotaFiscalLOCALEMBEXPORTACAO: TStringField;
    sdsNotaFiscalPISCOFINS_SOMAROUTRASDESP: TStringField;
    sdsNotaFiscalTIPO_DESCONTO: TStringField;
    sdsNotaFiscalGERARDUPL_OUTROSVALORES: TStringField;
    sdsNotaFiscalGERARDUPL_FRETE: TStringField;
    sdsNotaFiscalGERARDUPL_SEGURO: TStringField;
    sdsNotaFiscalINFORMADO_NUMNOTAMANUAL: TStringField;
    sdsNotaFiscalNFEDENEGADA: TStringField;
    sdsNotaFiscalMOTIVO_DENEGADA: TStringField;
    sdsNotaFiscalDADOS_ADICIONAIS: TMemoField;
    sdsNotaFiscalDTINICIO_DUPLICATA: TDateField;
    sdsNotaFiscalTIPO_PRAZO: TStringField;
    sdsNotaFiscalPERC_COMISSAO: TFloatField;
    sdsNotaFiscalNOME_CLI: TStringField;
    sdsNotaFiscalEMAIL_NFE_CLI: TStringField;
    sdsNotaFiscalENDERECO_CLI: TStringField;
    sdsNotaFiscalNUM_END_CLI: TStringField;
    sdsNotaFiscalCOMPLEMENTO_END_CLI: TStringField;
    sdsNotaFiscalBAIRRO_CLI: TStringField;
    sdsNotaFiscalID_CIDADE_CLI: TIntegerField;
    sdsNotaFiscalUF_CLI: TStringField;
    sdsNotaFiscalCNPJ_CPF_CLI: TStringField;
    sdsNotaFiscalINSCR_EST_CLI: TStringField;
    sdsNotaFiscalCIDADE_CLI: TStringField;
    sdsNotaFiscalNOME_TRANSP: TStringField;
    sdsNotaFiscalEMAIL_NFE_TRANSP: TStringField;
    sdsNotaFiscalENDERECO_TRANSP: TStringField;
    sdsNotaFiscalNUM_END_TRANSP: TStringField;
    sdsNotaFiscalCOMPLEMENTO_END_TRANSP: TStringField;
    sdsNotaFiscalBAIRRO_TRANSP: TStringField;
    sdsNotaFiscalID_CIDADE_TRANSP: TIntegerField;
    sdsNotaFiscalUF_TRANSP: TStringField;
    sdsNotaFiscalCNPJ_CPF_TRANSP: TStringField;
    sdsNotaFiscalINSCR_EST_TRANSP: TStringField;
    sdsNotaFiscalCIDADE_TRANSP: TStringField;
    cdsNotaFiscalID: TIntegerField;
    cdsNotaFiscalFILIAL: TIntegerField;
    cdsNotaFiscalSERIE: TStringField;
    cdsNotaFiscalNUMNOTA: TIntegerField;
    cdsNotaFiscalDTEMISSAO: TDateField;
    cdsNotaFiscalID_CFOP: TIntegerField;
    cdsNotaFiscalID_CLIENTE: TIntegerField;
    cdsNotaFiscalID_CONDPGTO: TIntegerField;
    cdsNotaFiscalID_VENDEDOR: TIntegerField;
    cdsNotaFiscalBASE_ICMS: TFloatField;
    cdsNotaFiscalVLR_ICMS: TFloatField;
    cdsNotaFiscalVLR_IPI: TFloatField;
    cdsNotaFiscalVLR_NOTA: TFloatField;
    cdsNotaFiscalVLR_ITENS: TFloatField;
    cdsNotaFiscalVLR_DUPLICATA: TFloatField;
    cdsNotaFiscalVLR_ENTRADA: TFloatField;
    cdsNotaFiscalPERC_DESCONTO: TFloatField;
    cdsNotaFiscalVLR_DESCONTO: TFloatField;
    cdsNotaFiscalVLR_FRETE: TFloatField;
    cdsNotaFiscalVLR_SEGURO: TFloatField;
    cdsNotaFiscalVLR_OUTRASDESP: TFloatField;
    cdsNotaFiscalBASE_ICMSTRANSF: TFloatField;
    cdsNotaFiscalPERC_TRANSF: TFloatField;
    cdsNotaFiscalVLR_TRANSF: TFloatField;
    cdsNotaFiscalVLR_PIS: TFloatField;
    cdsNotaFiscalVLR_COFINS: TFloatField;
    cdsNotaFiscalVLR_TAXACISCOMEX: TFloatField;
    cdsNotaFiscalVLR_OUTROS: TFloatField;
    cdsNotaFiscalBASE_ICMSSIMPLES: TFloatField;
    cdsNotaFiscalVLR_ICMSSIMPLES: TFloatField;
    cdsNotaFiscalPERC_ICMSSIMPLES: TFloatField;
    cdsNotaFiscalVLR_IMPORTACAO: TFloatField;
    cdsNotaFiscalBASE_ICMSSUBST: TFloatField;
    cdsNotaFiscalVLR_ICMSSUBST: TFloatField;
    cdsNotaFiscalBASE_ICMSOUTROS: TFloatField;
    cdsNotaFiscalVLR_ICMSOUTROS: TFloatField;
    cdsNotaFiscalVLR_DUPLICATAOUTROS: TFloatField;
    cdsNotaFiscalVLR_ADUANEIRA: TFloatField;
    cdsNotaFiscalPERC_ICMS_PISCOFINS: TFloatField;
    cdsNotaFiscalPERC_ICMS_OUTROSVALORES: TFloatField;
    cdsNotaFiscalPERC_ICMS_FRETE: TFloatField;
    cdsNotaFiscalPERC_DESCONTOORIG: TFloatField;
    cdsNotaFiscalQTDVOLUME: TIntegerField;
    cdsNotaFiscalESPECIE: TStringField;
    cdsNotaFiscalMARCA: TStringField;
    cdsNotaFiscalNUMEROVOLUME: TStringField;
    cdsNotaFiscalPESOBRUTO: TFloatField;
    cdsNotaFiscalPESOLIQUIDO: TFloatField;
    cdsNotaFiscalPLACA: TStringField;
    cdsNotaFiscalUFPLACA: TStringField;
    cdsNotaFiscalTIPO_FRETE: TStringField;
    cdsNotaFiscalID_TRANSPORTADORA: TIntegerField;
    cdsNotaFiscalID_REDESPACHO: TIntegerField;
    cdsNotaFiscalTIPO_NOTA: TStringField;
    cdsNotaFiscalCANCELADA: TStringField;
    cdsNotaFiscalMOTIVO_CANCELADA: TStringField;
    cdsNotaFiscalDTSAIDAENTRADA: TDateField;
    cdsNotaFiscalHRSAIDAENTRADA: TTimeField;
    cdsNotaFiscalID_BANCO: TIntegerField;
    cdsNotaFiscalLOCALENTREGA: TStringField;
    cdsNotaFiscalID_EXTCOMISSAO: TIntegerField;
    cdsNotaFiscalDESCRICAO_DESC: TStringField;
    cdsNotaFiscalID_CLIENTETRIANG: TIntegerField;
    cdsNotaFiscalQTDTOTAL_ITENS: TIntegerField;
    cdsNotaFiscalNFERECIBO: TStringField;
    cdsNotaFiscalNFEPROTOCOLO: TStringField;
    cdsNotaFiscalNFECHAVEACESSO: TStringField;
    cdsNotaFiscalNFEPROTOCOLO_CANCELADA: TStringField;
    cdsNotaFiscalTIPO_ENVIONFE: TStringField;
    cdsNotaFiscalNFECODBARRA_CONTINGENCIA: TStringField;
    cdsNotaFiscalNFEVERSAO: TStringField;
    cdsNotaFiscalNFEFINALIDADE: TStringField;
    cdsNotaFiscalNFEAMBIENTE: TStringField;
    cdsNotaFiscalNUMNOTACOPIADA: TIntegerField;
    cdsNotaFiscalSERIECOPIADA: TStringField;
    cdsNotaFiscalDTCONTINGENCIA: TDateField;
    cdsNotaFiscalHRCONTINGENCIA: TTimeField;
    cdsNotaFiscalMOTIVO_CONTINGENCIA: TStringField;
    cdsNotaFiscalNFEVERSAOEMISSAO: TStringField;
    cdsNotaFiscalID_REGIMETRIB: TIntegerField;
    cdsNotaFiscalRNTC: TStringField;
    cdsNotaFiscalVAGAOBALSA_IDENTIF: TStringField;
    cdsNotaFiscalVAGAOBALSA_TIPOIDENTIF: TStringField;
    cdsNotaFiscalUFEMBEXPORTACAO: TStringField;
    cdsNotaFiscalLOCALEMBEXPORTACAO: TStringField;
    cdsNotaFiscalPISCOFINS_SOMAROUTRASDESP: TStringField;
    cdsNotaFiscalTIPO_DESCONTO: TStringField;
    cdsNotaFiscalGERARDUPL_OUTROSVALORES: TStringField;
    cdsNotaFiscalGERARDUPL_FRETE: TStringField;
    cdsNotaFiscalGERARDUPL_SEGURO: TStringField;
    cdsNotaFiscalINFORMADO_NUMNOTAMANUAL: TStringField;
    cdsNotaFiscalNFEDENEGADA: TStringField;
    cdsNotaFiscalMOTIVO_DENEGADA: TStringField;
    cdsNotaFiscalDADOS_ADICIONAIS: TMemoField;
    cdsNotaFiscalDTINICIO_DUPLICATA: TDateField;
    cdsNotaFiscalTIPO_PRAZO: TStringField;
    cdsNotaFiscalPERC_COMISSAO: TFloatField;
    cdsNotaFiscalNOME_CLI: TStringField;
    cdsNotaFiscalEMAIL_NFE_CLI: TStringField;
    cdsNotaFiscalENDERECO_CLI: TStringField;
    cdsNotaFiscalNUM_END_CLI: TStringField;
    cdsNotaFiscalCOMPLEMENTO_END_CLI: TStringField;
    cdsNotaFiscalBAIRRO_CLI: TStringField;
    cdsNotaFiscalID_CIDADE_CLI: TIntegerField;
    cdsNotaFiscalUF_CLI: TStringField;
    cdsNotaFiscalCNPJ_CPF_CLI: TStringField;
    cdsNotaFiscalINSCR_EST_CLI: TStringField;
    cdsNotaFiscalCIDADE_CLI: TStringField;
    cdsNotaFiscalNOME_TRANSP: TStringField;
    cdsNotaFiscalEMAIL_NFE_TRANSP: TStringField;
    cdsNotaFiscalENDERECO_TRANSP: TStringField;
    cdsNotaFiscalNUM_END_TRANSP: TStringField;
    cdsNotaFiscalCOMPLEMENTO_END_TRANSP: TStringField;
    cdsNotaFiscalBAIRRO_TRANSP: TStringField;
    cdsNotaFiscalID_CIDADE_TRANSP: TIntegerField;
    cdsNotaFiscalUF_TRANSP: TStringField;
    cdsNotaFiscalCNPJ_CPF_TRANSP: TStringField;
    cdsNotaFiscalINSCR_EST_TRANSP: TStringField;
    cdsNotaFiscalCIDADE_TRANSP: TStringField;
    sdsNotaFiscalENDERECO_CLI2: TStringField;
    sdsNotaFiscalENDERECO_TRANSP2: TStringField;
    cdsNotaFiscalENDERECO_CLI2: TStringField;
    cdsNotaFiscalENDERECO_TRANSP2: TStringField;
    sdsNotaFiscalCEP_CLI: TStringField;
    sdsNotaFiscalCEP_TRANSP: TStringField;
    cdsNotaFiscalCEP_CLI: TStringField;
    cdsNotaFiscalCEP_TRANSP: TStringField;
    sdsNotaFiscalDDDFONE1_CLI: TIntegerField;
    sdsNotaFiscalTELEFONE1_CLI: TStringField;
    sdsNotaFiscalDDDFONE2_CLI: TIntegerField;
    sdsNotaFiscalTELEFONE2_CLI: TStringField;
    sdsNotaFiscalDDDFAX_CLI: TIntegerField;
    sdsNotaFiscalFAX_CLI: TStringField;
    cdsNotaFiscalDDDFONE1_CLI: TIntegerField;
    cdsNotaFiscalTELEFONE1_CLI: TStringField;
    cdsNotaFiscalDDDFONE2_CLI: TIntegerField;
    cdsNotaFiscalTELEFONE2_CLI: TStringField;
    cdsNotaFiscalDDDFAX_CLI: TIntegerField;
    cdsNotaFiscalFAX_CLI: TStringField;
    sdsNotaFiscal_NFe: TSQLDataSet;
    dspNotaFiscal_NFe: TDataSetProvider;
    cdsNotaFiscal_NFe: TClientDataSet;
    dsNotaFiscal_NFe: TDataSource;
    sdsNotaFiscal_NFeID: TIntegerField;
    sdsNotaFiscal_NFeFILIAL: TIntegerField;
    sdsNotaFiscal_NFeSERIE: TStringField;
    sdsNotaFiscal_NFeNUMNOTA: TIntegerField;
    sdsNotaFiscal_NFeDTEMISSAO: TDateField;
    sdsNotaFiscal_NFeID_CFOP: TIntegerField;
    sdsNotaFiscal_NFeID_CLIENTE: TIntegerField;
    sdsNotaFiscal_NFeID_CONDPGTO: TIntegerField;
    sdsNotaFiscal_NFeID_VENDEDOR: TIntegerField;
    sdsNotaFiscal_NFeBASE_ICMS: TFloatField;
    sdsNotaFiscal_NFeVLR_ICMS: TFloatField;
    sdsNotaFiscal_NFeVLR_IPI: TFloatField;
    sdsNotaFiscal_NFeVLR_NOTA: TFloatField;
    sdsNotaFiscal_NFeVLR_ITENS: TFloatField;
    sdsNotaFiscal_NFeVLR_DUPLICATA: TFloatField;
    sdsNotaFiscal_NFeVLR_ENTRADA: TFloatField;
    sdsNotaFiscal_NFePERC_DESCONTO: TFloatField;
    sdsNotaFiscal_NFeVLR_DESCONTO: TFloatField;
    sdsNotaFiscal_NFeVLR_FRETE: TFloatField;
    sdsNotaFiscal_NFeVLR_SEGURO: TFloatField;
    sdsNotaFiscal_NFeVLR_OUTRASDESP: TFloatField;
    sdsNotaFiscal_NFeBASE_ICMSTRANSF: TFloatField;
    sdsNotaFiscal_NFePERC_TRANSF: TFloatField;
    sdsNotaFiscal_NFeVLR_TRANSF: TFloatField;
    sdsNotaFiscal_NFeVLR_PIS: TFloatField;
    sdsNotaFiscal_NFeVLR_COFINS: TFloatField;
    sdsNotaFiscal_NFeVLR_TAXACISCOMEX: TFloatField;
    sdsNotaFiscal_NFeVLR_OUTROS: TFloatField;
    sdsNotaFiscal_NFeBASE_ICMSSIMPLES: TFloatField;
    sdsNotaFiscal_NFeVLR_ICMSSIMPLES: TFloatField;
    sdsNotaFiscal_NFePERC_ICMSSIMPLES: TFloatField;
    sdsNotaFiscal_NFeVLR_IMPORTACAO: TFloatField;
    sdsNotaFiscal_NFeBASE_ICMSSUBST: TFloatField;
    sdsNotaFiscal_NFeVLR_ICMSSUBST: TFloatField;
    sdsNotaFiscal_NFeBASE_ICMSOUTROS: TFloatField;
    sdsNotaFiscal_NFeVLR_ICMSOUTROS: TFloatField;
    sdsNotaFiscal_NFeVLR_DUPLICATAOUTROS: TFloatField;
    sdsNotaFiscal_NFeVLR_ADUANEIRA: TFloatField;
    sdsNotaFiscal_NFePERC_ICMS_PISCOFINS: TFloatField;
    sdsNotaFiscal_NFePERC_ICMS_OUTROSVALORES: TFloatField;
    sdsNotaFiscal_NFePERC_ICMS_FRETE: TFloatField;
    sdsNotaFiscal_NFePERC_DESCONTOORIG: TFloatField;
    sdsNotaFiscal_NFeQTDVOLUME: TIntegerField;
    sdsNotaFiscal_NFeESPECIE: TStringField;
    sdsNotaFiscal_NFeMARCA: TStringField;
    sdsNotaFiscal_NFeNUMEROVOLUME: TStringField;
    sdsNotaFiscal_NFePESOBRUTO: TFloatField;
    sdsNotaFiscal_NFePESOLIQUIDO: TFloatField;
    sdsNotaFiscal_NFePLACA: TStringField;
    sdsNotaFiscal_NFeUFPLACA: TStringField;
    sdsNotaFiscal_NFeTIPO_FRETE: TStringField;
    sdsNotaFiscal_NFeID_TRANSPORTADORA: TIntegerField;
    sdsNotaFiscal_NFeID_REDESPACHO: TIntegerField;
    sdsNotaFiscal_NFeTIPO_NOTA: TStringField;
    sdsNotaFiscal_NFeCANCELADA: TStringField;
    sdsNotaFiscal_NFeMOTIVO_CANCELADA: TStringField;
    sdsNotaFiscal_NFeDTSAIDAENTRADA: TDateField;
    sdsNotaFiscal_NFeHRSAIDAENTRADA: TTimeField;
    sdsNotaFiscal_NFeID_BANCO: TIntegerField;
    sdsNotaFiscal_NFeLOCALENTREGA: TStringField;
    sdsNotaFiscal_NFeID_EXTCOMISSAO: TIntegerField;
    sdsNotaFiscal_NFeDESCRICAO_DESC: TStringField;
    sdsNotaFiscal_NFeID_CLIENTETRIANG: TIntegerField;
    sdsNotaFiscal_NFeQTDTOTAL_ITENS: TIntegerField;
    sdsNotaFiscal_NFeNFERECIBO: TStringField;
    sdsNotaFiscal_NFeNFEPROTOCOLO: TStringField;
    sdsNotaFiscal_NFeNFECHAVEACESSO: TStringField;
    sdsNotaFiscal_NFeNFEPROTOCOLO_CANCELADA: TStringField;
    sdsNotaFiscal_NFeTIPO_ENVIONFE: TStringField;
    sdsNotaFiscal_NFeNFECODBARRA_CONTINGENCIA: TStringField;
    sdsNotaFiscal_NFeNFEVERSAO: TStringField;
    sdsNotaFiscal_NFeNFEFINALIDADE: TStringField;
    sdsNotaFiscal_NFeNFEAMBIENTE: TStringField;
    sdsNotaFiscal_NFeNUMNOTACOPIADA: TIntegerField;
    sdsNotaFiscal_NFeSERIECOPIADA: TStringField;
    sdsNotaFiscal_NFeDTCONTINGENCIA: TDateField;
    sdsNotaFiscal_NFeHRCONTINGENCIA: TTimeField;
    sdsNotaFiscal_NFeMOTIVO_CONTINGENCIA: TStringField;
    sdsNotaFiscal_NFeNFEVERSAOEMISSAO: TStringField;
    sdsNotaFiscal_NFeID_REGIMETRIB: TIntegerField;
    sdsNotaFiscal_NFeRNTC: TStringField;
    sdsNotaFiscal_NFeVAGAOBALSA_IDENTIF: TStringField;
    sdsNotaFiscal_NFeVAGAOBALSA_TIPOIDENTIF: TStringField;
    sdsNotaFiscal_NFeUFEMBEXPORTACAO: TStringField;
    sdsNotaFiscal_NFeLOCALEMBEXPORTACAO: TStringField;
    sdsNotaFiscal_NFePISCOFINS_SOMAROUTRASDESP: TStringField;
    sdsNotaFiscal_NFeTIPO_DESCONTO: TStringField;
    sdsNotaFiscal_NFeGERARDUPL_OUTROSVALORES: TStringField;
    sdsNotaFiscal_NFeGERARDUPL_FRETE: TStringField;
    sdsNotaFiscal_NFeGERARDUPL_SEGURO: TStringField;
    sdsNotaFiscal_NFeINFORMADO_NUMNOTAMANUAL: TStringField;
    sdsNotaFiscal_NFeNFEDENEGADA: TStringField;
    sdsNotaFiscal_NFeMOTIVO_DENEGADA: TStringField;
    sdsNotaFiscal_NFeDADOS_ADICIONAIS: TMemoField;
    sdsNotaFiscal_NFeDTINICIO_DUPLICATA: TDateField;
    sdsNotaFiscal_NFeTIPO_PRAZO: TStringField;
    sdsNotaFiscal_NFePERC_COMISSAO: TFloatField;
    sdsNotaFiscal_NFeNOME_CLI: TStringField;
    sdsNotaFiscal_NFeEMAIL_NFE_CLI: TStringField;
    sdsNotaFiscal_NFeENDERECO_CLI: TStringField;
    sdsNotaFiscal_NFeENDERECO_CLI2: TStringField;
    sdsNotaFiscal_NFeNUM_END_CLI: TStringField;
    sdsNotaFiscal_NFeCOMPLEMENTO_END_CLI: TStringField;
    sdsNotaFiscal_NFeBAIRRO_CLI: TStringField;
    sdsNotaFiscal_NFeID_CIDADE_CLI: TIntegerField;
    sdsNotaFiscal_NFeUF_CLI: TStringField;
    sdsNotaFiscal_NFeCNPJ_CPF_CLI: TStringField;
    sdsNotaFiscal_NFeINSCR_EST_CLI: TStringField;
    sdsNotaFiscal_NFeCIDADE_CLI: TStringField;
    sdsNotaFiscal_NFeCEP_CLI: TStringField;
    sdsNotaFiscal_NFeDDDFONE1_CLI: TIntegerField;
    sdsNotaFiscal_NFeTELEFONE1_CLI: TStringField;
    sdsNotaFiscal_NFeDDDFONE2_CLI: TIntegerField;
    sdsNotaFiscal_NFeTELEFONE2_CLI: TStringField;
    sdsNotaFiscal_NFeDDDFAX_CLI: TIntegerField;
    sdsNotaFiscal_NFeFAX_CLI: TStringField;
    sdsNotaFiscal_NFeNFEPROTOCOLO_CCE: TStringField;
    sdsNotaFiscal_NFeNFERECIBO_CCE: TStringField;
    sdsNotaFiscal_NFeITEM: TIntegerField;
    sdsNotaFiscal_NFeITEMTIPO: TIntegerField;
    sdsNotaFiscal_NFeTIPO_CCE: TStringField;
    sdsNotaFiscal_NFeDESCRICAO_CCE: TStringField;
    cdsNotaFiscal_NFeID: TIntegerField;
    cdsNotaFiscal_NFeFILIAL: TIntegerField;
    cdsNotaFiscal_NFeSERIE: TStringField;
    cdsNotaFiscal_NFeNUMNOTA: TIntegerField;
    cdsNotaFiscal_NFeDTEMISSAO: TDateField;
    cdsNotaFiscal_NFeID_CFOP: TIntegerField;
    cdsNotaFiscal_NFeID_CLIENTE: TIntegerField;
    cdsNotaFiscal_NFeID_CONDPGTO: TIntegerField;
    cdsNotaFiscal_NFeID_VENDEDOR: TIntegerField;
    cdsNotaFiscal_NFeBASE_ICMS: TFloatField;
    cdsNotaFiscal_NFeVLR_ICMS: TFloatField;
    cdsNotaFiscal_NFeVLR_IPI: TFloatField;
    cdsNotaFiscal_NFeVLR_NOTA: TFloatField;
    cdsNotaFiscal_NFeVLR_ITENS: TFloatField;
    cdsNotaFiscal_NFeVLR_DUPLICATA: TFloatField;
    cdsNotaFiscal_NFeVLR_ENTRADA: TFloatField;
    cdsNotaFiscal_NFePERC_DESCONTO: TFloatField;
    cdsNotaFiscal_NFeVLR_DESCONTO: TFloatField;
    cdsNotaFiscal_NFeVLR_FRETE: TFloatField;
    cdsNotaFiscal_NFeVLR_SEGURO: TFloatField;
    cdsNotaFiscal_NFeVLR_OUTRASDESP: TFloatField;
    cdsNotaFiscal_NFeBASE_ICMSTRANSF: TFloatField;
    cdsNotaFiscal_NFePERC_TRANSF: TFloatField;
    cdsNotaFiscal_NFeVLR_TRANSF: TFloatField;
    cdsNotaFiscal_NFeVLR_PIS: TFloatField;
    cdsNotaFiscal_NFeVLR_COFINS: TFloatField;
    cdsNotaFiscal_NFeVLR_TAXACISCOMEX: TFloatField;
    cdsNotaFiscal_NFeVLR_OUTROS: TFloatField;
    cdsNotaFiscal_NFeBASE_ICMSSIMPLES: TFloatField;
    cdsNotaFiscal_NFeVLR_ICMSSIMPLES: TFloatField;
    cdsNotaFiscal_NFePERC_ICMSSIMPLES: TFloatField;
    cdsNotaFiscal_NFeVLR_IMPORTACAO: TFloatField;
    cdsNotaFiscal_NFeBASE_ICMSSUBST: TFloatField;
    cdsNotaFiscal_NFeVLR_ICMSSUBST: TFloatField;
    cdsNotaFiscal_NFeBASE_ICMSOUTROS: TFloatField;
    cdsNotaFiscal_NFeVLR_ICMSOUTROS: TFloatField;
    cdsNotaFiscal_NFeVLR_DUPLICATAOUTROS: TFloatField;
    cdsNotaFiscal_NFeVLR_ADUANEIRA: TFloatField;
    cdsNotaFiscal_NFePERC_ICMS_PISCOFINS: TFloatField;
    cdsNotaFiscal_NFePERC_ICMS_OUTROSVALORES: TFloatField;
    cdsNotaFiscal_NFePERC_ICMS_FRETE: TFloatField;
    cdsNotaFiscal_NFePERC_DESCONTOORIG: TFloatField;
    cdsNotaFiscal_NFeQTDVOLUME: TIntegerField;
    cdsNotaFiscal_NFeESPECIE: TStringField;
    cdsNotaFiscal_NFeMARCA: TStringField;
    cdsNotaFiscal_NFeNUMEROVOLUME: TStringField;
    cdsNotaFiscal_NFePESOBRUTO: TFloatField;
    cdsNotaFiscal_NFePESOLIQUIDO: TFloatField;
    cdsNotaFiscal_NFePLACA: TStringField;
    cdsNotaFiscal_NFeUFPLACA: TStringField;
    cdsNotaFiscal_NFeTIPO_FRETE: TStringField;
    cdsNotaFiscal_NFeID_TRANSPORTADORA: TIntegerField;
    cdsNotaFiscal_NFeID_REDESPACHO: TIntegerField;
    cdsNotaFiscal_NFeTIPO_NOTA: TStringField;
    cdsNotaFiscal_NFeCANCELADA: TStringField;
    cdsNotaFiscal_NFeMOTIVO_CANCELADA: TStringField;
    cdsNotaFiscal_NFeDTSAIDAENTRADA: TDateField;
    cdsNotaFiscal_NFeHRSAIDAENTRADA: TTimeField;
    cdsNotaFiscal_NFeID_BANCO: TIntegerField;
    cdsNotaFiscal_NFeLOCALENTREGA: TStringField;
    cdsNotaFiscal_NFeID_EXTCOMISSAO: TIntegerField;
    cdsNotaFiscal_NFeDESCRICAO_DESC: TStringField;
    cdsNotaFiscal_NFeID_CLIENTETRIANG: TIntegerField;
    cdsNotaFiscal_NFeQTDTOTAL_ITENS: TIntegerField;
    cdsNotaFiscal_NFeNFERECIBO: TStringField;
    cdsNotaFiscal_NFeNFEPROTOCOLO: TStringField;
    cdsNotaFiscal_NFeNFECHAVEACESSO: TStringField;
    cdsNotaFiscal_NFeNFEPROTOCOLO_CANCELADA: TStringField;
    cdsNotaFiscal_NFeTIPO_ENVIONFE: TStringField;
    cdsNotaFiscal_NFeNFECODBARRA_CONTINGENCIA: TStringField;
    cdsNotaFiscal_NFeNFEVERSAO: TStringField;
    cdsNotaFiscal_NFeNFEFINALIDADE: TStringField;
    cdsNotaFiscal_NFeNFEAMBIENTE: TStringField;
    cdsNotaFiscal_NFeNUMNOTACOPIADA: TIntegerField;
    cdsNotaFiscal_NFeSERIECOPIADA: TStringField;
    cdsNotaFiscal_NFeDTCONTINGENCIA: TDateField;
    cdsNotaFiscal_NFeHRCONTINGENCIA: TTimeField;
    cdsNotaFiscal_NFeMOTIVO_CONTINGENCIA: TStringField;
    cdsNotaFiscal_NFeNFEVERSAOEMISSAO: TStringField;
    cdsNotaFiscal_NFeID_REGIMETRIB: TIntegerField;
    cdsNotaFiscal_NFeRNTC: TStringField;
    cdsNotaFiscal_NFeVAGAOBALSA_IDENTIF: TStringField;
    cdsNotaFiscal_NFeVAGAOBALSA_TIPOIDENTIF: TStringField;
    cdsNotaFiscal_NFeUFEMBEXPORTACAO: TStringField;
    cdsNotaFiscal_NFeLOCALEMBEXPORTACAO: TStringField;
    cdsNotaFiscal_NFePISCOFINS_SOMAROUTRASDESP: TStringField;
    cdsNotaFiscal_NFeTIPO_DESCONTO: TStringField;
    cdsNotaFiscal_NFeGERARDUPL_OUTROSVALORES: TStringField;
    cdsNotaFiscal_NFeGERARDUPL_FRETE: TStringField;
    cdsNotaFiscal_NFeGERARDUPL_SEGURO: TStringField;
    cdsNotaFiscal_NFeINFORMADO_NUMNOTAMANUAL: TStringField;
    cdsNotaFiscal_NFeNFEDENEGADA: TStringField;
    cdsNotaFiscal_NFeMOTIVO_DENEGADA: TStringField;
    cdsNotaFiscal_NFeDADOS_ADICIONAIS: TMemoField;
    cdsNotaFiscal_NFeDTINICIO_DUPLICATA: TDateField;
    cdsNotaFiscal_NFeTIPO_PRAZO: TStringField;
    cdsNotaFiscal_NFePERC_COMISSAO: TFloatField;
    cdsNotaFiscal_NFeNOME_CLI: TStringField;
    cdsNotaFiscal_NFeEMAIL_NFE_CLI: TStringField;
    cdsNotaFiscal_NFeENDERECO_CLI: TStringField;
    cdsNotaFiscal_NFeENDERECO_CLI2: TStringField;
    cdsNotaFiscal_NFeNUM_END_CLI: TStringField;
    cdsNotaFiscal_NFeCOMPLEMENTO_END_CLI: TStringField;
    cdsNotaFiscal_NFeBAIRRO_CLI: TStringField;
    cdsNotaFiscal_NFeID_CIDADE_CLI: TIntegerField;
    cdsNotaFiscal_NFeUF_CLI: TStringField;
    cdsNotaFiscal_NFeCNPJ_CPF_CLI: TStringField;
    cdsNotaFiscal_NFeINSCR_EST_CLI: TStringField;
    cdsNotaFiscal_NFeCIDADE_CLI: TStringField;
    cdsNotaFiscal_NFeCEP_CLI: TStringField;
    cdsNotaFiscal_NFeDDDFONE1_CLI: TIntegerField;
    cdsNotaFiscal_NFeTELEFONE1_CLI: TStringField;
    cdsNotaFiscal_NFeDDDFONE2_CLI: TIntegerField;
    cdsNotaFiscal_NFeTELEFONE2_CLI: TStringField;
    cdsNotaFiscal_NFeDDDFAX_CLI: TIntegerField;
    cdsNotaFiscal_NFeFAX_CLI: TStringField;
    cdsNotaFiscal_NFeNFEPROTOCOLO_CCE: TStringField;
    cdsNotaFiscal_NFeNFERECIBO_CCE: TStringField;
    cdsNotaFiscal_NFeITEM: TIntegerField;
    cdsNotaFiscal_NFeITEMTIPO: TIntegerField;
    cdsNotaFiscal_NFeTIPO_CCE: TStringField;
    cdsNotaFiscal_NFeDESCRICAO_CCE: TStringField;
    sdsNotaFiscal_NFeMOTIVO_CCE: TMemoField;
    cdsNotaFiscal_NFeMOTIVO_CCE: TMemoField;
    qNotaEntrada_ItensID: TIntegerField;
    qNotaEntrada_ItensITEM: TIntegerField;
    qNotaEntrada_ItensID_PRODUTO: TIntegerField;
    qNotaEntrada_ItensQTD: TFloatField;
    qNotaEntrada_ItensQTDRESTANTE: TFloatField;
    qNotaEntrada_ItensQTDDEVOLVIDA: TFloatField;
    qProduto_Forn: TSQLQuery;
    qProduto_FornCOD_MATERIAL_FORN: TStringField;
    qProduto_FornCOD_BARRA: TStringField;
    mItensNFeItemOriginal: TIntegerField;
    qParametrosIMP_CODPRODCLI_DANFE: TStringField;
    mAuxDadosNFeID_Variacao: TIntegerField;
    qTab_CFOP_Variacao: TSQLQuery;
    qTab_CFOP_VariacaoID: TIntegerField;
    qTab_CFOP_VariacaoITEM: TIntegerField;
    qTab_CFOP_VariacaoLEI: TMemoField;
    mAuxDadosNFeOBS: TWideStringField;
    qProduto_Veiculo: TSQLQuery;
    qProduto_VeiculoID: TIntegerField;
    qProduto_VeiculoPLACA: TStringField;
    qProduto_VeiculoNUM_CHASSI: TStringField;
    qProduto_VeiculoNUM_RENAVAM: TStringField;
    qProduto_VeiculoCOD_COR: TIntegerField;
    qProduto_VeiculoANO_FAB: TIntegerField;
    qProduto_VeiculoANO_MOD: TIntegerField;
    qProduto_VeiculoMOTORIZACAO: TStringField;
    qProduto_VeiculoNOME_COR: TStringField;
    qProduto_VeiculoMARCA: TStringField;
    qProduto_VeiculoMODELO: TStringField;
    qProduto_VeiculoCOMBUSTIVEL: TStringField;
    qProduto_VeiculoESPECIE: TStringField;
    qContasID: TIntegerField;
    qContasNOME: TStringField;
    qContasAGENCIA: TStringField;
    qContasFILIAL: TIntegerField;
    qContasNUMCONTA: TStringField;
    qContasCNAB: TStringField;
    qContasDTENCERRAMENTO: TDateField;
    qContasID_TIPOCOBRANCA: TIntegerField;
    qContasDESCRICAO_NOTA: TStringField;
    qContasTIPO_CONTA: TStringField;
    qContasID_BANCO: TIntegerField;
    qContasDIG_CONTA: TStringField;
    qContasCOD_CEDENTE: TStringField;
    qContasACEITE: TStringField;
    qContasID_OCORRENCIA: TIntegerField;
    qContasDIAS_PROTESTO: TIntegerField;
    qContasID_ESPECIE: TIntegerField;
    qContasID_CARTEIRA: TIntegerField;
    qContasID_INSTRUCAO1: TIntegerField;
    qContasID_INSTRUCAO2: TIntegerField;
    qContasID_TIPO_COBRANCA: TIntegerField;
    qContasMOEDA: TStringField;
    qContasVARIACAO_CARTEIRA: TStringField;
    qContasTIPO_DOCUMENTO: TStringField;
    qContasCOD_TRANSMISSAO: TStringField;
    qContasMENSAGEM_FIXA: TStringField;
    qContasPERC_DESCONTO: TFloatField;
    qContasPERC_JUROS: TFloatField;
    qContasVLR_IOF: TFloatField;
    qContasVLR_TAXA: TFloatField;
    qContasLOCAL_PAGAMENTO: TStringField;
    qContasEND_ARQUIVO_REM: TStringField;
    qContasNOME_ARQ_REM: TStringField;
    qContasEXTENSAO_ARQ_REM: TStringField;
    qContasDT_LIMITE_DESCONTO: TDateField;
    qContasCOMISSAO_PERMANENCIA: TStringField;
    qContasNUM_CONVENIO_LIDER: TStringField;
    qContasDIG_AGENCIA: TStringField;
    qContasDIAS_DEVOLUCAO: TIntegerField;
    qParametrosDESTACAR_IMPOSTO_NOTA: TStringField;
    mItensNFePercPis: TFloatField;
    mItensNFePercCofins: TFloatField;
    mItensNFePercRedICMSSubst: TFloatField;
    sdsNotaFiscalVLR_TRIBUTOS: TFloatField;
    cdsNotaFiscalVLR_TRIBUTOS: TFloatField;
    mItensNFeVlrTributos: TFloatField;
    sdsNotaFiscalGRAVOU_DADOSADICIONAIS: TStringField;
    cdsNotaFiscalGRAVOU_DADOSADICIONAIS: TStringField;
    qNotaEntrada_ItensCONTADOR: TIntegerField;
    qParametrosUSA_TAMANHO_AGRUPADO_NFE: TStringField;
    mItensNFeNumOS: TStringField;
    mItensNFeCodAuxiliar: TStringField;
    mItensNFeObs_Tamanho: TStringField;
    dsmParcelaNFe: TDataSource;
    qParametrosUSA_FCI: TStringField;
    mItensNFeNFCI: TStringField;
    mItensNFeID_Produto: TIntegerField;
    qParametrosTIPO_LEI_TRANSPARENCIA: TStringField;
    qParametrosLEI_TRANSPARENCIA_IMP_ITEM: TStringField;
    qParametrosLEI_TRANSPARENCIA_TEXTO_ITEM: TStringField;
    qParametrosLEI_TRANSPARENCIA_PERC_ADIC: TStringField;
    qOBS_Lei: TSQLQuery;
    qOBS_LeiID: TIntegerField;
    qOBS_LeiNOME: TStringField;
    qOBS_LeiOBS: TStringField;
    qContasNOME_BANCO: TStringField;
    qFilial_Email: TSQLQuery;
    qFilial_EmailID_FILIAL: TIntegerField;
    qFilial_EmailID_CONFIG_EMAIL: TIntegerField;
    qFilial_EmailNOME_CONFIG: TStringField;
    qFilial_EmailREMETENTE_NOME: TStringField;
    qFilial_EmailREMETENTE_EMAIL: TStringField;
    qFilial_EmailSMTP_CLIENTE: TStringField;
    qFilial_EmailSMTP_PORTA: TIntegerField;
    qFilial_EmailSMTP_REQUER_SSL: TStringField;
    qFilial_EmailSMTP_USUARIO: TStringField;
    qFilial_EmailSMTP_SENHA: TStringField;
    qFilial_EmailSOLICITAR_CONFIRMACAO: TStringField;
    qFilial_EmailBASE: TSmallintField;
    qFilial_EmailCNPJ_CPF_FILIAL: TStringField;
    qParametrosUSA_ENVIO_EMAIL_CATEGORIA: TStringField;
    qOperacao_Nota: TSQLQuery;
    qOperacao_NotaID: TIntegerField;
    qOperacao_NotaNOME: TStringField;
    qOperacao_NotaPEDIR_FINALIDADE: TStringField;
    qOperacao_NotaNATUREZA_NOTA: TStringField;
    mNotaDevolvidaNFeCTeChaveAcesso: TStringField;
    qFilial_Download: TSQLQuery;
    qFilial_DownloadID: TIntegerField;
    qFilial_DownloadITEM: TIntegerField;
    qFilial_DownloadPESSOA: TStringField;
    qFilial_DownloadCNPJ_CPF: TStringField;
    mItensNFeNCM_EX: TStringField;
    mItensNFePercIcmsSubstInterno: TFloatField;
    mItensNFeVlrIcmsDesonerado: TFloatField;
    mItensNFeCodMotivoDesonerado: TIntegerField;
    mItensNFeVlrIcmsOperacao: TFloatField;
    mItensNFePercTribIcms: TFloatField;
    qParametrosUSA_DESONERACAO: TStringField;
    qParametrosUSA_ICMSOPERACAO_CST51: TStringField;
    qParametrosUSA_DANFE_FLEXDOCS: TStringField;
    mItensNFeVlrTributos_Federal: TFloatField;
    mItensNFeVlrTributos_Estadual: TFloatField;
    mItensNFeVlrTributos_Municipal: TFloatField;
    mItensNFePercTributos_Federal: TFloatField;
    mItensNFePercTributos_Estadual: TFloatField;
    mItensNFePercTributos_Municipal: TFloatField;
    mItensNFeFonte: TStringField;
    qParametrosIMP_PERC_TRIB_DADOS_ADIC: TStringField;
    qParametrosUSA_ENVIO_NOVO_NFE: TStringField;
    mItensNFePercDiferimento: TFloatField;
    mItensNFeVlrIcmsDiferido: TFloatField;
    qTransportadoraCEP: TStringField;
    qTransportadoraCIDADE: TStringField;
    qParametrosFUSOHORARIO: TStringField;
    qParametrosFUSOHORARIO_VERAO: TStringField;
    mItensNFeNum_Lote_Controle: TStringField;
    qParametrosUSA_ADIANTAMENTO_PEDIDO: TStringField;
    qPedido_Adiant: TSQLQuery;
    qPedido_AdiantID: TIntegerField;
    qPedido_AdiantNUM_PEDIDO: TIntegerField;
    qPedido_AdiantPEDIDO_CLIENTE: TStringField;
    qPedido_AdiantVLR_ADIANTAMENTO: TFloatField;
    qPedido_AdiantID_NOTA: TIntegerField;
    qParametrosMOSTRAR_END_ENTREGA_DADOS_ADI: TStringField;
    qParametrosMSG_PADRAO_NOTA: TMemoField;
    qParametrosUSA_OBS_PEDIDO_NOTA: TStringField;
    qPedido: TSQLQuery;
    qPedidoID: TIntegerField;
    qPedidoNUM_PEDIDO: TIntegerField;
    qPedidoPEDIDO_CLIENTE: TStringField;
    qPedidoOBS_NOTA: TStringField;
    mItensNFeCod_Cest: TStringField;
    mItensNFeCod_EnqIPI: TStringField;
    mItensNFePerc_ICMS_UF_Dest: TFloatField;
    mItensNFePerc_ICMS_FCP: TFloatField;
    mItensNFePerc_ICMS_Partilha: TFloatField;
    mItensNFeVlr_ICMS_FCP: TFloatField;
    mItensNFeVlr_ICMS_UF_Dest: TFloatField;
    mItensNFeVlr_ICMS_UF_Remet: TFloatField;
    mItensNFePerc_ICMS_Inter: TFloatField;
    qParametros_NFe: TSQLQuery;
    qParametros_NFeID: TIntegerField;
    qParametros_NFeSOMAR_IPI_NO_ICMS: TStringField;
    qParametros_NFeOBS_EMAIL_NFE: TMemoField;
    qFilialULTIMO_ACESSO: TStringField;
    Decoder64: TIdDecoderMIME;
    qParametros_NFeIMP_RODAPE_DANFE_CLI: TStringField;
    qFilialLOCALSERVIDORNFE: TStringField;
    qCFOP: TSQLQuery;
    qCFOPID: TIntegerField;
    qCFOPCODCFOP: TStringField;
    qCFOPCOPIARNOTATRIANGULAR: TStringField;
    qParametros_NFeIMP_END_COBRANCA: TStringField;
    qParametrosOPCAO_REL_PED_AGRUPADO: TStringField;
    mItensNFeGRAVOU_TAB_TAMANHO: TStringField;
    mMS: TClientDataSet;
    dsMS: TDataSource;
    mMSNum_MS: TStringField;
    mMS_Ref: TClientDataSet;
    mMS_RefNum_MS: TStringField;
    mMS_RefReferencia: TStringField;
    cdsProduto_Consumo: TClientDataSet;
    cdsProduto_ConsumoID: TIntegerField;
    cdsProduto_ConsumoITEM: TIntegerField;
    cdsProduto_ConsumoID_MATERIAL: TIntegerField;
    cdsProduto_ConsumoQTD_CONSUMO: TFloatField;
    cdsProduto_ConsumoQTD_UNIDADE: TFloatField;
    cdsProduto_ConsumoUNIDADE: TStringField;
    cdsProduto_ConsumoID_POSICAO: TIntegerField;
    cdsProduto_ConsumoTIPO_CONSUMO: TStringField;
    cdsProduto_ConsumoREFERENCIA: TStringField;
    cdsProduto_ConsumoNUM_MS: TStringField;
    dspProduto_Consumo: TDataSetProvider;
    sdsProduto_Consumo: TSQLDataSet;
    sdsNotaFiscal_MP: TSQLDataSet;
    dspNotaFiscal_MP: TDataSetProvider;
    cdsNotaFiscal_MP: TClientDataSet;
    cdsNotaFiscal_MPID: TIntegerField;
    cdsNotaFiscal_MPITEM: TIntegerField;
    cdsNotaFiscal_MPID_MATERIAL: TIntegerField;
    cdsNotaFiscal_MPTAMANHO: TStringField;
    cdsNotaFiscal_MPQTD: TFloatField;
    cdsNotaFiscal_MPID_MOVESTOQUE: TIntegerField;
    cdsNotaFiscal_MPID_MOVESTOQUE_RES: TIntegerField;
    cdsNotaFiscal_MPNUM_ORDEM: TIntegerField;
    cdsNotaFiscal_MPQTD_RESERVA: TFloatField;
    cdsNotaFiscal_MPID_COR: TIntegerField;
    cdsNotaFiscal_MPNUM_LOTE_CONTROLE: TStringField;
    cdsNotaFiscal_MPREFERENCIA: TStringField;
    cdsNotaFiscal_MPNUM_MS: TStringField;
    cdsNotaFiscal_MPITEM_NOTA: TIntegerField;
    qParametros_NFeOBS_DADOS_ADI_DESONERACAO: TStringField;
    qConfig_Nfe: TSQLQuery;
    qConfig_NfeDANFE_CARACTER_SALTAR_LINHA: TStringField;
    qConfig_NfeCNPJ_TITULAR: TStringField;
    qDesoneracao: TSQLQuery;
    qDesoneracaoCOD_CST_ICMS: TStringField;
    qDesoneracaoCOD_DESONERACAO: TSmallintField;
    qDesoneracaoNOME: TStringField;
    mDescSuframa: TClientDataSet;
    mDescSuframaPerc_ICMS: TFloatField;
    qParametros_NFeDESC_ICMS_DESONERADO: TStringField;
    mItensNFeIBPT_Chave: TStringField;
    sdsNota_Eletronica: TSQLDataSet;
    dspNota_Eletronica: TDataSetProvider;
    cdsNota_Eletronica: TClientDataSet;
    cdsNota_EletronicaID: TIntegerField;
    cdsNota_EletronicaCHAVE_ACESSO: TStringField;
    cdsNota_EletronicaUF: TIntegerField;
    cdsNota_EletronicaNATUREZA_OPERACAO: TStringField;
    cdsNota_EletronicaFORMA_PAGAMENTO: TIntegerField;
    cdsNota_EletronicaSERIE: TIntegerField;
    cdsNota_EletronicaNRO_NOTA_FISCAL: TIntegerField;
    cdsNota_EletronicaDATA_EMISSAO: TDateField;
    cdsNota_EletronicaTIPO_NFE: TIntegerField;
    cdsNota_EletronicaCODIGO_MUNICIO: TIntegerField;
    cdsNota_EletronicaTIPO_EMISSAO: TIntegerField;
    cdsNota_EletronicaTIPO_AMBIENTE: TIntegerField;
    cdsNota_EletronicaFINALIDADE: TIntegerField;
    cdsNota_EletronicaEMITENTE_DOCUMENTO: TStringField;
    cdsNota_EletronicaEMITENTE_NOME: TStringField;
    cdsNota_EletronicaDESTINATARIO_DOCUMENTO: TStringField;
    cdsNota_EletronicaDESTINATARIO_NOME: TStringField;
    cdsNota_EletronicaVALOR_TOTAL: TFloatField;
    cdsNota_EletronicaXML_ASSINADO: TMemoField;
    cdsNota_EletronicaXML_ASSINADO_PROC: TMemoField;
    cdsNota_EletronicaNRO_RECIBO: TStringField;
    cdsNota_EletronicaDATA_RECEBIMENTO: TSQLTimeStampField;
    cdsNota_EletronicaPROTOCOLO: TStringField;
    cdsNota_EletronicaSTATUS: TIntegerField;
    cdsNota_EletronicaMOTIVO: TStringField;
    cdsNota_EletronicaXML_STATUS: TMemoField;
    mItensNFeUnidade_Trib: TStringField;
    mItensNFeVlr_Unitario_Trib: TFloatField;
    mItensNFeQtd_Trib: TFloatField;
    sdsNota_EletronicaID: TIntegerField;
    sdsNota_EletronicaCHAVE_ACESSO: TStringField;
    sdsNota_EletronicaUF: TIntegerField;
    sdsNota_EletronicaNATUREZA_OPERACAO: TStringField;
    sdsNota_EletronicaFORMA_PAGAMENTO: TIntegerField;
    sdsNota_EletronicaSERIE: TIntegerField;
    sdsNota_EletronicaNRO_NOTA_FISCAL: TIntegerField;
    sdsNota_EletronicaDATA_EMISSAO: TDateField;
    sdsNota_EletronicaTIPO_NFE: TIntegerField;
    sdsNota_EletronicaCODIGO_MUNICIO: TIntegerField;
    sdsNota_EletronicaTIPO_EMISSAO: TIntegerField;
    sdsNota_EletronicaTIPO_AMBIENTE: TIntegerField;
    sdsNota_EletronicaFINALIDADE: TIntegerField;
    sdsNota_EletronicaEMITENTE_DOCUMENTO: TStringField;
    sdsNota_EletronicaEMITENTE_NOME: TStringField;
    sdsNota_EletronicaDESTINATARIO_DOCUMENTO: TStringField;
    sdsNota_EletronicaDESTINATARIO_NOME: TStringField;
    sdsNota_EletronicaVALOR_TOTAL: TFloatField;
    sdsNota_EletronicaXML_ASSINADO: TMemoField;
    sdsNota_EletronicaXML_ASSINADO_PROC: TMemoField;
    sdsNota_EletronicaNRO_RECIBO: TStringField;
    sdsNota_EletronicaDATA_RECEBIMENTO: TSQLTimeStampField;
    sdsNota_EletronicaPROTOCOLO: TStringField;
    sdsNota_EletronicaSTATUS: TIntegerField;
    sdsNota_EletronicaMOTIVO: TStringField;
    sdsNota_EletronicaXML_STATUS: TMemoField;
    sdsNFe_Log: TSQLDataSet;
    dspNFe_Log: TDataSetProvider;
    cdsNFe_Log: TClientDataSet;
    cdsNFe_LogID: TIntegerField;
    cdsNFe_LogID_NFE: TIntegerField;
    cdsNFe_LogDATA_RECEBIMENTO: TSQLTimeStampField;
    cdsNFe_LogPROTOCOLO: TStringField;
    cdsNFe_LogSTATUS: TIntegerField;
    cdsNFe_LogMOTIVO: TStringField;
    cdsNFe_LogMSGDADOS: TMemoField;
    cdsNFe_LogMSGRETWS: TMemoField;
    cdsNFe_LogMSGRESULTADO: TMemoField;
    cdsNFe_LogCMSG: TMemoField;
    cdsNFe_LogXMSG: TMemoField;
    dsNFe_Log: TDataSource;
    dsNota_Eletronica: TDataSource;
    mNFe_Log: TClientDataSet;
    mNFe_LogID: TIntegerField;
    mNFe_LogID_NFE: TIntegerField;
    mNFe_LogDataRecebimento: TSQLTimeStampField;
    mNFe_LogProtocolo: TStringField;
    mNFe_LogStatus: TIntegerField;
    mNFe_LogMotivo: TStringField;
    mNFe_LogMSGDados: TMemoField;
    mNFe_LogMSGRETWS: TMemoField;
    mNFe_LogMSGRESULTADO: TMemoField;
    mNFe_LogNRecibo: TStringField;
    mNFe_LogNRecibo_Orig: TStringField;
    dsmNFe_Log: TDataSource;
    qPedido_Item: TSQLQuery;
    qPedido_ItemTAMANHO_CLIENTE: TStringField;
    qPedido_ItemNOME_COR_CLIENTE: TStringField;
    qPedido_ItemCOD_PRODUTO_CLIENTE: TStringField;
    qPedido_ItemCOD_COR_CLIENTE: TStringField;
    qParametros_NFeIMP_OC: TStringField;
    qParametros_NFeIMP_USUARIO: TStringField;
    qParametros_NFeENVAR_CODBARRA: TStringField;
    qParametros_NFeMSG_SIMPLES_COMP: TStringField;
    mItensNFeBase_ICMS_FCP: TFloatField;
    mItensNFeBASE_FCP_ST: TFloatField;
    mItensNFeVLR_FCP_ST: TFloatField;
    mItensNFePERC_FCP_ST: TFloatField;
    mItensNFeVLR_ICMS_FCP_DEST: TFloatField;
    mItensNFeBASE_ICMS_FCP_DEST: TFloatField;
    sdsTPag: TSQLDataSet;
    dspTPag: TDataSetProvider;
    cdsTPag: TClientDataSet;
    cdsTPagVLR_VENCIMENTO: TFloatField;
    cdsTPagCOD_IMP_FISCAL: TStringField;
    qCBarra: TSQLQuery;
    qCBarraID: TIntegerField;
    qCBarraCOD_BARRA: TStringField;
    qCBarraID_PRODUTO: TIntegerField;
    qCBarraID_COR: TIntegerField;
    qCBarraTAMANHO: TStringField;
    qCBarraCOD_PRINCIPAL: TStringField;
    qCBarraCOD_SEQUENCIAL: TIntegerField;
    qCBarraFILIAL: TIntegerField;
    qOperacao_NotaMOSTRAR_CLI_TRIANG2: TStringField;
    qItensNte: TSQLQuery;
    qItensNteID_NTE: TIntegerField;
    qItensNteNUMNOTA: TIntegerField;
    qItensNteSERIE: TStringField;
    qItensNteNOME_CLIENTE_TRI: TStringField;
    qItensNteCNPJ_CPF_CLIENTE_TRI: TStringField;
    qItensNteDTEMISSAO: TDateField;
    mItensNFeCodBarra2: TStringField;
    qNFeNota: TSQLQuery;
    qNFeNotaID: TIntegerField;
    qNFeNotaCHAVE_ACESSO: TStringField;
    qNFeNotaNRO_NOTA_FISCAL: TIntegerField;
    mItensNFeVlrIPI_Devol: TFloatField;
    mItensNFePerc_Devol: TFloatField;
    mItensNFeBase_IPI: TFloatField;
    sdsNotaFiscalVLR_IPI_DEVOL: TFloatField;
    sdsNotaFiscalBASE_IPI: TFloatField;
    cdsNotaFiscalVLR_IPI_DEVOL: TFloatField;
    cdsNotaFiscalBASE_IPI: TFloatField;
    procedure DataModuleCreate(Sender: TObject);
    procedure mItensNFeBeforePost(DataSet: TDataSet);
    procedure mDadosAdicionaisNFeBeforePost(DataSet: TDataSet);
    procedure mNotaDevolvidaNFeNewRecord(DataSet: TDataSet);
    procedure mItensNFeNewRecord(DataSet: TDataSet);
    procedure mAuxDadosNFeNewRecord(DataSet: TDataSet);
    procedure DataModuleDestroy(Sender: TObject);

  private
    { Private declarations }

  public
    { Public declarations }

    vMsgErro: String;
    ctCommand: String;
    ctNFe_Log: String;
    ctqProduto_Forn : String;
    vHrEmissaoNFe_Inf : TDateTime;
    vNRec_Log, vNRec_Orig : String;

    //17/12/2013 Novo processo de envio
    vNovoProcesso : Boolean;

    procedure prc_Localizar(ID: Integer);
    procedure prc_Inserir;
    procedure prc_Gravar;
    procedure prc_Excluir;

    procedure Posiciona_CidadeUF(CodCidade, IDPais: Integer);
    procedure Posiciona_Operacao_Nota(ID : Integer);

    procedure prc_Veiculo(ID: Integer);

    procedure prc_Abrir_NFe_Log(Rec : Boolean = False);

    procedure prc_Procurar_Recibo;

  end;

var
  DMNFe: TDMNFe;


implementation

uses DmdDatabase, SendMailOptions, DmdDatabase_NFeBD;

{$R *.dfm}


procedure TDMNFe.prc_Inserir;
var
  vAux: Integer;
begin
  if not cdsNFe_Email.Active then
    prc_Localizar(-1);
  vAux := dmDatabase.ProximaSequencia('NFE_EMAIL',0);

  cdsNFe_Email.Insert;
  cdsNFe_EmailID.AsInteger := vAux;
end;

procedure TDMNFe.prc_Excluir;
begin
  if not(cdsNFe_Email.Active) or (cdsNFe_Email.IsEmpty) then
    exit;
  cdsNFe_Email.Delete;
  cdsNFe_Email.ApplyUpdates(0);
end;

procedure TDMNFe.prc_Gravar;
begin
  vMsgErro := '';
  if trim(cdsNFe_EmailNOME.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Nome não informado!';
  if trim(cdsNFe_EmailEMAIL.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Email não informado!';
  if trim(vMsgErro) <> '' then
    exit;
  cdsNFe_Email.Post;
  cdsNFe_Email.ApplyUpdates(0);
end;

procedure TDMNFe.prc_Localizar(ID: Integer); //-1 é para inclusão
begin
  cdsNFe_Email.Close;
  sdsNFe_Email.CommandText := ctCommand;
  if ID <> 0 then
    sdsNFe_Email.CommandText := sdsNFe_Email.CommandText
                         + ' WHERE ID = ' + IntToStr(ID);
  cdsNFe_Email.Open;
end;

procedure TDMNFe.DataModuleCreate(Sender: TObject);
begin
  ctCommand       := sdsNFe_Email.CommandText;
  ctNFe_Log       := sdsNFe_Log.CommandText;
  ctqProduto_Forn := qProduto_Forn.SQL.Text;

  dmDatabase_NFeBD := TdmDatabase_NFeBD.Create(Self);

  qParametros.Close;
  qParametros.Open;
  qParametros_NFe.Close;
  qParametros_NFe.Open;
end;

procedure TDMNFe.mItensNFeBeforePost(DataSet: TDataSet);
begin
  if mItensNFeInfAdicionais.Value <> '' then
  begin
    mItensNFeInfAdicionais.Value := StringReplace( mItensNFeInfAdicionais.Value, #13, #32, [rfReplaceAll] );
    mItensNFeInfAdicionais.Value := StringReplace( mItensNFeInfAdicionais.Value, #10, '', [rfReplaceAll] );
  end;
end;

procedure TDMNFe.mDadosAdicionaisNFeBeforePost(DataSet: TDataSet);
begin
  if mDadosAdicionaisNFeObs.Value <> '' then
  begin
    mDadosAdicionaisNFeObs.Value := StringReplace( mDadosAdicionaisNFeObs.Value, #13, #32, [rfReplaceAll] );
    mDadosAdicionaisNFeObs.Value := StringReplace( mDadosAdicionaisNFeObs.Value, #10, '', [rfReplaceAll] );
  end;
end;

procedure TDMNFe.mNotaDevolvidaNFeNewRecord(DataSet: TDataSet);
begin
  mNotaDevolvidaNFeQtd.AsFloat := 0;
end;

procedure TDMNFe.mItensNFeNewRecord(DataSet: TDataSet);
begin
  mItensNFeTipoReg.AsString           := 'R';
  mItensNFeMVA.AsFloat                := 0;
  mItensNFeSomaVlrTotalProd.AsBoolean := True;
  mItensNFePercPis.AsFloat            := 0;
  mItensNFePercCofins.AsFloat         := 0;
  mItensNFeVlrBaseImportacao.AsFloat  := 0;
  mItensNFeVlrImportacao.AsFloat      := 0;
  mItensNFeVlrDespAduaneira.AsFloat   := 0;
  mItensNFeQtd.AsFloat                := 0;
  mItensNFeVlrUnitario.AsFloat        := 0;
  mItensNFeVlrTotal.AsFloat           := 0;
  mItensNFeVlrIcms.AsFloat            := 0;
  mItensNFeVlrIpi.AsFloat             := 0;
  mItensNFeBaseIcmsSimples.AsFloat    := 0;
  mItensNFeVlrIcmsSimples.AsFloat     := 0;
  mItensNFeVlrPis.AsFloat             := 0;
  mItensNFeVlrCofins.AsFloat          := 0;
  mItensNFeVlrFrete.AsFloat           := 0;
  mItensNFeVlrSeguro.AsFloat          := 0;
  mItensNFeVlrOutrasDespesas.AsFloat  := 0;
  mItensNFeVlrDesconto.AsFloat        := 0;
  mItensNFeBaseICMS.AsFloat           := 0;
  mItensNFeIcmsBaseSubst.AsFloat      := 0;
  mItensNFeIcmsVlrSubst.AsFloat       := 0;
  mItensNFeVlrTributos.AsFloat        := 0;
  mItensNFeObs_Tamanho.AsString       := '';
  mItensNFeVlrIcmsOperacao.AsFloat    := 0;
  mItensNFePercTribIcms.AsFloat       := 0;
  mItensNFeVlr_ICMS_FCP.AsFloat       := 0;
  mItensNFeVlr_ICMS_UF_Dest.AsFloat   := 0;
  mItensNFeVlr_ICMS_UF_Remet.AsFloat  := 0;
  mItensNFeVlrIcmsDesonerado.AsFloat  := 0;
  mItensNFeVlrIcmsDiferido.AsFloat    := 0;
  mItensNFeVlrIcmsOperacao.AsFloat    := 0;
  mItensNFeVlrIcmsSimples.AsFloat     := 0;
  mItensNFeVlr_Unitario_Trib.AsFloat  := 0;
  mItensNFeQtd_Trib.AsFloat           := 0;
  mItensNFeBase_ICMS_FCP.AsFloat      := 0;
  mItensNFeBASE_FCP_ST.AsFloat        := 0;
  mItensNFeVLR_FCP_ST.AsFloat         := 0;
  mItensNFePERC_FCP_ST.AsFloat        := 0;
  mItensNFeVLR_ICMS_FCP_DEST.AsFloat  := 0;
  mItensNFeBASE_ICMS_FCP_DEST.AsFloat := 0;
  mItensNFeUnidade_Trib.AsString      := '';
  mItensNFeVlrIPI_Devol.AsFloat       := 0;
  mItensNFePerc_Devol.AsFloat         := 0;
end;

procedure TDMNFe.Posiciona_CidadeUF(CodCidade, IDPais: Integer);
begin
  qCidade.Close;
  qCidade.ParamByName('ID').AsInteger := CodCidade;
  qCidade.Open;

  qUF.Close;
  qUF.ParamByName('UF').AsString := qCidadeUF.AsString;
  qUF.Open;

  qPais.Close;
  qPais.ParamByName('ID').AsInteger := IDPais;
  qPais.Open;
end;

procedure TDMNFe.mAuxDadosNFeNewRecord(DataSet: TDataSet);
begin
  mAuxDadosNFeID_Variacao.AsInteger := 0;
end;

procedure TDMNFe.prc_Veiculo(ID: Integer);
begin
  qProduto_Veiculo.Close;
  qProduto_Veiculo.ParamByName('ID').AsInteger := ID;
  qProduto_Veiculo.Open;
  if qProduto_Veiculo.IsEmpty then
    exit;
  if (trim(qProduto_VeiculoPLACA.AsString) <> '') or (trim(qProduto_VeiculoNUM_RENAVAM.AsString) <> '') then
  begin
    mAuxDadosNFe.Insert;
    mAuxDadosNFeTipo.AsString         := 'VEI';
    mAuxDadosNFeCodigo.AsString       := IntToStr(ID);
    mAuxDadosNFeID_Variacao.AsInteger := 0;
    mAuxDadosNFeOBS.Value             := '(';
    if qProduto_VeiculoPLACA.AsString <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + 'Placa: ' + qProduto_VeiculoPLACA.AsString;
    if qProduto_VeiculoNUM_RENAVAM.AsString <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Renavam: ' + qProduto_VeiculoNUM_RENAVAM.AsString;
    if qProduto_VeiculoNUM_CHASSI.AsString <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Chassi: ' + qProduto_VeiculoNUM_CHASSI.AsString;
    if qProduto_VeiculoNOME_COR.AsString <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Cor: ' + qProduto_VeiculoNOME_COR.AsString;
    if qProduto_VeiculoMOTORIZACAO.AsString <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Motor: ' + qProduto_VeiculoMOTORIZACAO.AsString;
    if qProduto_VeiculoANO_FAB.AsInteger > 0 then
    begin
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Ano Fab/Mod: ' + qProduto_VeiculoANO_FAB.AsString;
      if qProduto_VeiculoANO_MOD.AsInteger > 0 then
        mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + '/' + qProduto_VeiculoANO_MOD.AsString;
    end;
    if trim(qProduto_VeiculoCOMBUSTIVEL.AsString) <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Combustivel: ' + qProduto_VeiculoCOMBUSTIVEL.AsString;
    if trim(qProduto_VeiculoESPECIE.AsString) <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Especie: ' + qProduto_VeiculoESPECIE.AsString;
    if trim(qProduto_VeiculoMARCA.AsString) <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Marca: ' + qProduto_VeiculoMARCA.AsString;
    if trim(qProduto_VeiculoMODELO.AsString) <> '' then
      mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ' Modelo: ' + qProduto_VeiculoMODELO.AsString;
    mAuxDadosNFeOBS.Value := mAuxDadosNFeOBS.Value + ')';
    mAuxDadosNFe.Post;
  end;
end;

procedure TDMNFe.Posiciona_Operacao_Nota(ID: Integer);
begin
  qOperacao_Nota.Close;
  qOperacao_Nota.ParamByName('ID').AsInteger := ID;
  qOperacao_Nota.Open;
end;

procedure TDMNFe.DataModuleDestroy(Sender: TObject);
begin
  FreeAndNil(dmDatabase_NFeBD);
end;

procedure TDMNFe.prc_Abrir_NFe_Log(Rec: Boolean);
begin
  cdsNFe_Log.Close;
  sdsNFe_Log.CommandText := ctNFe_Log;
  if Rec then
    sdsNFe_Log.CommandText := sdsNFe_Log.CommandText + ' AND L.MSGRETWS LIKE ' + QuotedStr('%[nRec:%');
  sdsNFe_Log.ParamByName('ID_NFE').AsInteger := cdsNota_EletronicaID.AsInteger;
  cdsNFe_Log.Open;
end;

procedure TDMNFe.prc_Procurar_Recibo;
var
  i : Integer;
  vTexto : String;
begin
  vTexto := '';
  i := posex('<nRec>',cdsNFe_LogMSGRETWS.Value);
  if i > 0 then
    vTexto := copy(cdsNFe_LogMSGRETWS.Value,i+6,15);
  vNRec_Log := vTexto;

  vTexto := '';
  i := posex('[nRec:',cdsNFe_LogMSGRETWS.Value);
  if i > 0 then
    vTexto := copy(cdsNFe_LogMSGRETWS.Value,i+6,15);
  vNRec_Orig := vTexto;
end;

end.
