object fRelPagarReceber: TfRelPagarReceber
  Left = 2
  Top = 175
  Width = 1374
  Height = 563
  Caption = 'fRelPagarReceber'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object RLReport1: TRLReport
    Left = 8
    Top = 8
    Width = 794
    Height = 1123
    DataSource = DMCadDuplicata.dsDuplicata_Consulta
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    Margins.LeftMargin = 6.000000000000000000
    Margins.TopMargin = 5.000000000000000000
    Margins.RightMargin = 6.000000000000000000
    object RLBand1: TRLBand
      Left = 23
      Top = 19
      Width = 748
      Height = 89
      BandType = btHeader
      Borders.Sides = sdCustom
      Borders.DrawLeft = False
      Borders.DrawTop = False
      Borders.DrawRight = False
      Borders.DrawBottom = True
      object RLSystemInfo1: TRLSystemInfo
        Left = 709
        Top = 0
        Width = 39
        Height = 16
        Alignment = taRightJustify
      end
      object RLSystemInfo2: TRLSystemInfo
        Left = 626
        Top = 16
        Width = 122
        Height = 16
        Alignment = taRightJustify
        Info = itPageNumber
        Text = 'P'#225'g.: '
      end
      object RLLabel1: TRLLabel
        Left = 0
        Top = 72
        Width = 57
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'VCTO.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel2: TRLLabel
        Left = 80
        Top = 72
        Width = 200
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'PESSOA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel3: TRLLabel
        Left = 281
        Top = 72
        Width = 50
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'DUPL.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel4: TRLLabel
        Left = 332
        Top = 72
        Width = 50
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'NOTA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel5: TRLLabel
        Left = 383
        Top = 72
        Width = 32
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'S'#201'RIE'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel6: TRLLabel
        Left = 416
        Top = 72
        Width = 50
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = '$ PARC.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel7: TRLLabel
        Left = 467
        Top = 72
        Width = 50
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = '$ REST.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel8: TRLLabel
        Left = 58
        Top = 72
        Width = 21
        Height = 14
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'E/S'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel10: TRLLabel
        Left = 519
        Top = 72
        Width = 100
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'TIPO COB.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel11: TRLLabel
        Left = 620
        Top = 72
        Width = 127
        Height = 14
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'CONTA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
    end
    object RLSubDetail1: TRLSubDetail
      Left = 23
      Top = 108
      Width = 748
      Height = 221
      DataSource = DMCadDuplicata.dsDuplicata_Consulta
      object RLBand2: TRLBand
        Left = 0
        Top = 0
        Width = 748
        Height = 20
        object RLDBText1: TRLDBText
          Left = 0
          Top = 3
          Width = 57
          Height = 14
          AutoSize = False
          DataField = 'DTVENCIMENTO'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText2: TRLDBText
          Left = 80
          Top = 3
          Width = 200
          Height = 14
          AutoSize = False
          DataField = 'NOME_PESSOA'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText3: TRLDBText
          Left = 467
          Top = 3
          Width = 50
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'VLR_RESTANTE'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText4: TRLDBText
          Left = 281
          Top = 3
          Width = 50
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'NUMDUPLICATA'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText5: TRLDBText
          Left = 332
          Top = 3
          Width = 50
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'NUMNOTA'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText6: TRLDBText
          Left = 383
          Top = 3
          Width = 32
          Height = 14
          Alignment = taCenter
          AutoSize = False
          DataField = 'SERIE'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText7: TRLDBText
          Left = 416
          Top = 3
          Width = 50
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'VLR_PARCELA'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText8: TRLDBText
          Left = 58
          Top = 3
          Width = 22
          Height = 14
          Alignment = taCenter
          AutoSize = False
          DataField = 'TIPO_ES'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText9: TRLDBText
          Left = 518
          Top = 3
          Width = 100
          Height = 14
          AutoSize = False
          DataField = 'NOME_TIPOCOBRANCA'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText10: TRLDBText
          Left = 620
          Top = 3
          Width = 127
          Height = 14
          AutoSize = False
          DataField = 'NOME_CONTA'
          DataSource = DMCadDuplicata.dsDuplicata_Consulta
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLBand3: TRLBand
        Left = 0
        Top = 20
        Width = 748
        Height = 165
        BandType = btSummary
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = True
        Borders.DrawRight = False
        Borders.DrawBottom = False
      end
    end
  end
  object RLReport2: TRLReport
    Left = 808
    Top = 8
    Width = 794
    Height = 1123
    DataSource = DMCadDuplicata.dsDuplicata_Consulta
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    Margins.LeftMargin = 6.000000000000000000
    Margins.TopMargin = 5.000000000000000000
    Margins.RightMargin = 6.000000000000000000
    object RLSubDetail2: TRLSubDetail
      Left = 23
      Top = 113
      Width = 748
      Height = 198
      DataSource = DMCadDuplicata.dsDuplicata_Consulta
      object RLGroup1: TRLGroup
        Left = 0
        Top = 0
        Width = 748
        Height = 160
        DataFields = 'DTVENCIMENTO'
        object RLBand4: TRLBand
          Left = 0
          Top = 16
          Width = 748
          Height = 16
          BeforePrint = RLBand4BeforePrint
          object RLDBText12: TRLDBText
            Left = 0
            Top = 1
            Width = 22
            Height = 14
            Alignment = taCenter
            AutoSize = False
            DataField = 'TIPO_ES'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText13: TRLDBText
            Left = 22
            Top = 1
            Width = 200
            Height = 14
            AutoSize = False
            DataField = 'NOME_PESSOA'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText14: TRLDBText
            Left = 223
            Top = 1
            Width = 50
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'NUMDUPLICATA'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            DisplayMask = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText15: TRLDBText
            Left = 274
            Top = 1
            Width = 50
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'NUMNOTA'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            DisplayMask = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText16: TRLDBText
            Left = 325
            Top = 1
            Width = 32
            Height = 14
            Alignment = taCenter
            AutoSize = False
            DataField = 'SERIE'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            DisplayMask = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText17: TRLDBText
            Left = 358
            Top = 1
            Width = 50
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_PARCELA'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            DisplayMask = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText18: TRLDBText
            Left = 409
            Top = 1
            Width = 50
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_RESTANTE'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            DisplayMask = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText19: TRLDBText
            Left = 460
            Top = 1
            Width = 100
            Height = 14
            AutoSize = False
            DataField = 'NOME_TIPOCOBRANCA'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            DisplayMask = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText20: TRLDBText
            Left = 562
            Top = 1
            Width = 127
            Height = 14
            AutoSize = False
            DataField = 'NOME_CONTA'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            DisplayMask = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand5: TRLBand
          Left = 0
          Top = 32
          Width = 748
          Height = 20
          BandType = btColumnFooter
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = True
          Borders.DrawRight = False
          Borders.DrawBottom = False
          BeforePrint = RLBand5BeforePrint
          object RLLabel21: TRLLabel
            Left = 301
            Top = 1
            Width = 52
            Height = 14
            Alignment = taRightJustify
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            Caption = 'RECEBER:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel22: TRLLabel
            Left = 406
            Top = 1
            Width = 43
            Height = 14
            Alignment = taRightJustify
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            Caption = 'PAGAR:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel23: TRLLabel
            Left = 631
            Top = 1
            Width = 42
            Height = 14
            Alignment = taRightJustify
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            Caption = 'SALDO:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLSomaE: TRLLabel
            Left = 354
            Top = 1
            Width = 50
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            Caption = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLSaldo: TRLLabel
            Left = 674
            Top = 1
            Width = 50
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            Caption = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLSomaS: TRLLabel
            Left = 450
            Top = 1
            Width = 50
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            Caption = '0.00'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel9: TRLLabel
            Left = 22
            Top = 1
            Width = 75
            Height = 14
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            Caption = 'TOTAL DO DIA'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand7: TRLBand
          Left = 0
          Top = 0
          Width = 748
          Height = 16
          BandType = btColumnHeader
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = True
          object RLDBText21: TRLDBText
            Left = 0
            Top = 1
            Width = 87
            Height = 14
            DataField = 'DTVENCIMENTO'
            DataSource = DMCadDuplicata.dsDuplicata_Consulta
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
      end
      object RLBand8: TRLBand
        Left = 0
        Top = 160
        Width = 748
        Height = 33
        BandType = btSummary
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = True
        Borders.DrawRight = False
        Borders.DrawBottom = False
        Borders.Width = 2
        BeforePrint = RLBand8BeforePrint
        object RLLabel24: TRLLabel
          Left = 301
          Top = 1
          Width = 52
          Height = 14
          Alignment = taRightJustify
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Caption = 'RECEBER:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel25: TRLLabel
          Left = 406
          Top = 1
          Width = 43
          Height = 14
          Alignment = taRightJustify
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Caption = 'PAGAR:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel26: TRLLabel
          Left = 631
          Top = 1
          Width = 42
          Height = 14
          Alignment = taRightJustify
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Caption = 'SALDO:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLTotalReceber: TRLLabel
          Left = 354
          Top = 1
          Width = 50
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Caption = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLTotalSaldo: TRLLabel
          Left = 674
          Top = 1
          Width = 50
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Caption = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLTotalPagar: TRLLabel
          Left = 450
          Top = 1
          Width = 50
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Caption = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel30: TRLLabel
          Left = 22
          Top = 1
          Width = 102
          Height = 14
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Caption = 'TOTAL DO PER'#205'ODO'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
    end
    object RLBand6: TRLBand
      Left = 23
      Top = 19
      Width = 748
      Height = 94
      BandType = btColumnHeader
      Borders.Sides = sdCustom
      Borders.DrawLeft = False
      Borders.DrawTop = False
      Borders.DrawRight = False
      Borders.DrawBottom = True
      object RLLabel12: TRLLabel
        Left = 22
        Top = 79
        Width = 200
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'PESSOA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel13: TRLLabel
        Left = 223
        Top = 79
        Width = 50
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'DUPL.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel14: TRLLabel
        Left = 274
        Top = 79
        Width = 50
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'NOTA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel15: TRLLabel
        Left = 325
        Top = 79
        Width = 32
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'S'#201'RIE'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel16: TRLLabel
        Left = 358
        Top = 79
        Width = 50
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = '$ PARC.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel17: TRLLabel
        Left = 409
        Top = 79
        Width = 50
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = '$ REST.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel18: TRLLabel
        Left = 0
        Top = 79
        Width = 21
        Height = 14
        Anchors = [fkBottom]
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'E/S'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel19: TRLLabel
        Left = 461
        Top = 79
        Width = 100
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'TIPO COB.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel20: TRLLabel
        Left = 562
        Top = 79
        Width = 127
        Height = 14
        Anchors = [fkBottom]
        AutoSize = False
        Borders.Sides = sdCustom
        Borders.DrawLeft = False
        Borders.DrawTop = False
        Borders.DrawRight = True
        Borders.DrawBottom = False
        Caption = 'CONTA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLSystemInfo3: TRLSystemInfo
        Left = 709
        Top = 0
        Width = 39
        Height = 16
        Alignment = taRightJustify
      end
      object RLSystemInfo4: TRLSystemInfo
        Left = 626
        Top = 16
        Width = 122
        Height = 16
        Alignment = taRightJustify
        Info = itPageNumber
        Text = 'P'#225'g.: '
      end
      object RLTitulo: TRLLabel
        Left = 212
        Top = 2
        Width = 324
        Height = 16
        Alignment = taCenter
        AutoSize = False
        Caption = 'RELA'#199#195'O DE CONTAS A RECEBER E A PAGAR'
      end
      object RLPerEmissao: TRLLabel
        Left = 212
        Top = 18
        Width = 324
        Height = 16
        Alignment = taCenter
        AutoSize = False
        Caption = 'Emis'#227'o de 01/01/2000 a 31/12/3000'
      end
      object RLPerVcto: TRLLabel
        Left = 212
        Top = 34
        Width = 324
        Height = 16
        Alignment = taCenter
        AutoSize = False
        Caption = 'Vencimento de 01/01/2000 a 31/12/3000'
      end
    end
  end
end
