object fRelPedido: TfRelPedido
  Left = 216
  Top = 26
  Width = 987
  Height = 784
  VertScrollBar.Position = 73
  Caption = 'Pedido'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 13
  object RLReport1: TRLReport
    Left = 48
    Top = -65
    Width = 794
    Height = 1123
    DataSource = DMCadPedido.dsPedidoImp
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    Margins.LeftMargin = 7.000000000000000000
    Margins.TopMargin = 9.000000000000000000
    Margins.RightMargin = 7.000000000000000000
    Margins.BottomMargin = 9.000000000000000000
    RecordRange = rrCurrentOnly
    ShowProgress = False
    BeforePrint = RLReport1BeforePrint
    object RLSubDetail1: TRLSubDetail
      Left = 26
      Top = 34
      Width = 742
      Height = 678
      DataSource = DMCadPedido.dsPedidoImp
      object RLBand1: TRLBand
        Left = 0
        Top = 0
        Width = 742
        Height = 105
        BandType = btHeader
        BeforePrint = RLBand1BeforePrint
        object RLDraw11: TRLDraw
          Left = 664
          Top = 26
          Width = 77
          Height = 79
        end
        object RLDraw10: TRLDraw
          Left = 128
          Top = 25
          Width = 537
          Height = 80
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLDraw8: TRLDraw
          Left = 128
          Top = 1
          Width = 613
          Height = 26
        end
        object RLDraw1: TRLDraw
          Left = 0
          Top = 1
          Width = 129
          Height = 104
        end
        object RLImage1: TRLImage
          Left = 4
          Top = 6
          Width = 118
          Height = 95
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Stretch = True
        end
        object RLLabel1: TRLLabel
          Left = 675
          Top = 30
          Width = 47
          Height = 12
          Caption = 'Impress'#227'o'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel2: TRLLabel
          Left = 686
          Top = 45
          Width = 26
          Height = 12
          Caption = 'Data:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel3: TRLLabel
          Left = 686
          Top = 74
          Width = 26
          Height = 12
          Caption = 'Hora:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLSystemInfo1: TRLSystemInfo
          Left = 668
          Top = 58
          Width = 62
          Height = 12
          Alignment = taCenter
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLSystemInfo2: TRLSystemInfo
          Left = 668
          Top = 91
          Width = 62
          Height = 12
          Alignment = taCenter
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          Info = itHour
          ParentFont = False
        end
        object RLLabel4: TRLLabel
          Left = 131
          Top = 9
          Width = 74
          Height = 14
          Caption = 'Pedido Interno:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel7: TRLLabel
          Left = 615
          Top = 9
          Width = 59
          Height = 14
          Caption = 'Dt.Emiss'#227'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel8: TRLLabel
          Left = 287
          Top = 9
          Width = 137
          Height = 16
          Caption = 'Pedido Cliente (O.C):'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText2: TRLDBText
          Left = 675
          Top = 9
          Width = 62
          Height = 14
          DataField = 'DTEMISSAO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText3: TRLDBText
          Left = 427
          Top = 7
          Width = 145
          Height = 19
          DataField = 'PEDIDO_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -16
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText20: TRLDBText
          Left = 206
          Top = 9
          Width = 62
          Height = 16
          AutoSize = False
          DataField = 'NUM_PEDIDO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel6: TRLLabel
          Left = 137
          Top = 55
          Width = 45
          Height = 12
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object rlEndFilial: TRLLabel
          Left = 184
          Top = 55
          Width = 473
          Height = 12
          AutoSize = False
          Caption = 'ENDERE'#199'O, N'#218'MERO, COMPLEMENTO'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText1: TRLDBText
          Left = 184
          Top = 67
          Width = 305
          Height = 12
          AutoSize = False
          DataField = 'BAIRRO_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel16: TRLLabel
          Left = 152
          Top = 67
          Width = 30
          Height = 12
          Caption = 'Bairro:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel17: TRLLabel
          Left = 147
          Top = 79
          Width = 35
          Height = 12
          Caption = 'Cidade:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel57: TRLLabel
          Left = 375
          Top = 91
          Width = 31
          Height = 12
          Caption = 'CNPJ:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText5: TRLDBText
          Left = 408
          Top = 91
          Width = 85
          Height = 12
          DataField = 'CNPJ_CPF_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel58: TRLLabel
          Left = 500
          Top = 91
          Width = 50
          Height = 12
          Caption = 'Inscr. Est.:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText10: TRLDBText
          Left = 551
          Top = 91
          Width = 88
          Height = 12
          DataField = 'INSCR_EST_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel59: TRLLabel
          Left = 515
          Top = 79
          Width = 35
          Height = 12
          Caption = 'Estado:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText19: TRLDBText
          Left = 551
          Top = 79
          Width = 49
          Height = 12
          DataField = 'UF_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel60: TRLLabel
          Left = 137
          Top = 91
          Width = 45
          Height = 12
          Caption = 'Telefone :'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText24: TRLDBText
          Left = 184
          Top = 91
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText30: TRLDBText
          Left = 209
          Top = 91
          Width = 62
          Height = 12
          DataField = 'FONE_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel61: TRLLabel
          Left = 527
          Top = 67
          Width = 23
          Height = 12
          Caption = 'Cep:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText35: TRLDBText
          Left = 551
          Top = 67
          Width = 55
          Height = 12
          DataField = 'CEP_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText36: TRLDBText
          Left = 184
          Top = 79
          Width = 305
          Height = 12
          AutoSize = False
          DataField = 'CIDADE_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText31: TRLDBText
          Left = 184
          Top = 41
          Width = 473
          Height = 14
          AutoSize = False
          DataField = 'NOME_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText57: TRLDBText
          Left = 139
          Top = 28
          Width = 433
          Height = 14
          AutoSize = False
          DataField = 'NOME_INTERNO_FIL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel66: TRLLabel
          Left = 139
          Top = 43
          Width = 43
          Height = 12
          Caption = 'Empresa:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLSubDetail2: TRLSubDetail
        Left = 0
        Top = 343
        Width = 742
        Height = 194
        DataSource = DMCadPedido.dsPedidoImp_Itens
        object RLBand2: TRLBand
          Left = 0
          Top = 0
          Width = 742
          Height = 32
          BeforePrint = RLBand2BeforePrint
          object RLDraw13: TRLDraw
            Left = 88
            Top = 15
            Width = 593
            Height = 15
          end
          object RLDBText18: TRLDBText
            Left = 2
            Top = 7
            Width = 30
            Height = 18
            Alignment = taCenter
            AutoSize = False
            Borders.Sides = sdCustom
            Borders.DrawLeft = True
            Borders.DrawTop = True
            Borders.DrawRight = True
            Borders.DrawBottom = True
            DataField = 'ITEM'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText21: TRLDBText
            Left = 376
            Top = 1
            Width = 70
            Height = 13
            Alignment = taCenter
            AutoSize = False
            DataField = 'DTENTREGA'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText22: TRLDBText
            Left = 319
            Top = 1
            Width = 55
            Height = 13
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'QTD'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText25: TRLDBText
            Left = 182
            Top = 1
            Width = 98
            Height = 13
            Alignment = taCenter
            AutoSize = False
            DataField = 'NUMOS'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText26: TRLDBText
            Left = 94
            Top = 16
            Width = 555
            Height = 13
            AutoSize = False
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            DataField = 'NOMEPRODUTO'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText29: TRLDBText
            Left = 90
            Top = 2
            Width = 91
            Height = 12
            AutoSize = False
            DataField = 'REFERENCIA'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDraw7: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 1
            Align = faTop
            DrawKind = dkLine
          end
          object rlPreco: TRLLabel
            Left = 509
            Top = 1
            Width = 69
            Height = 13
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Pre'#231'o'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object rlVlrTotal: TRLLabel
            Left = 651
            Top = 1
            Width = 89
            Height = 13
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Vlr.Total'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText49: TRLDBText
            Left = 282
            Top = 1
            Width = 36
            Height = 13
            Alignment = taCenter
            AutoSize = False
            DataField = 'UNIDADE'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText51: TRLDBText
            Left = 33
            Top = 2
            Width = 56
            Height = 12
            Alignment = taCenter
            AutoSize = False
            DataField = 'ID_PRODUTO'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText16: TRLDBText
            Left = 578
            Top = 1
            Width = 70
            Height = 13
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_IPI'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText54: TRLDBText
            Left = 447
            Top = 1
            Width = 61
            Height = 13
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_ICMSSUBST'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand4: TRLBand
          Left = 0
          Top = 68
          Width = 742
          Height = 67
          BandType = btSummary
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          BeforePrint = RLBand4BeforePrint
          object RLDraw6: TRLDraw
            Left = 0
            Top = 34
            Width = 742
            Height = 33
            Align = faBottom
          end
          object RLDraw5: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 34
            Align = faTop
          end
          object RLLabel40: TRLLabel
            Left = 30
            Top = 3
            Width = 113
            Height = 14
            Caption = 'Vlr. Total de Mercs.:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText32: TRLDBText
            Left = 146
            Top = 3
            Width = 111
            Height = 14
            AutoSize = False
            DataField = 'VLR_ITENS2'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel41: TRLLabel
            Left = 94
            Top = 36
            Width = 55
            Height = 11
            Caption = 'Qtde. Total:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel44: TRLLabel
            Left = 284
            Top = 3
            Width = 80
            Height = 14
            Caption = 'Vlr. Desconto:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText33: TRLDBText
            Left = 367
            Top = 3
            Width = 89
            Height = 14
            DataField = 'VLR_DESCONTO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel45: TRLLabel
            Left = 496
            Top = 36
            Width = 130
            Height = 14
            Caption = 'Valor Total de Pedidos:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText8: TRLDBText
            Left = 151
            Top = 36
            Width = 22
            Height = 11
            DataField = 'QTD'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel43: TRLLabel
            Left = 585
            Top = 3
            Width = 41
            Height = 14
            Caption = 'Vlr. IPI:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText52: TRLDBText
            Left = 628
            Top = 3
            Width = 111
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_IPI'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel27: TRLLabel
            Left = 9
            Top = 17
            Width = 134
            Height = 14
            Caption = 'Base Icms Substitui'#231#227'o:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText23: TRLDBText
            Left = 146
            Top = 17
            Width = 111
            Height = 14
            AutoSize = False
            DataField = 'BASE_ICMSSUBST'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel32: TRLLabel
            Left = 500
            Top = 17
            Width = 126
            Height = 14
            Alignment = taRightJustify
            Caption = 'Vlr. Icms Substitui'#231#227'o:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText53: TRLDBText
            Left = 628
            Top = 17
            Width = 111
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_ICMSSUBST'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel64: TRLLabel
            Left = 628
            Top = 36
            Width = 111
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Valor Total de Pedidos:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel68: TRLLabel
            Left = 52
            Top = 52
            Width = 54
            Height = 14
            Caption = 'Vendedor:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText58: TRLDBText
            Left = 107
            Top = 52
            Width = 513
            Height = 14
            AutoSize = False
            DataField = 'NOME_VENDEDOR'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel69: TRLLabel
            Left = 248
            Top = 36
            Width = 69
            Height = 14
            Caption = 'Vlr. Entrada:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText59: TRLDBText
            Left = 319
            Top = 36
            Width = 117
            Height = 14
            DataField = 'VLR_ADIANTAMENTO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
        object RLBand3: TRLBand
          Left = 0
          Top = 50
          Width = 742
          Height = 18
          BeforePrint = RLBand3BeforePrint
          object RLLabel38: TRLLabel
            Left = 79
            Top = 2
            Width = 26
            Height = 14
            Caption = 'Obs:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLMemo3: TRLMemo
            Left = 107
            Top = 2
            Width = 605
            Height = 14
            Behavior = [beSiteExpander]
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand5: TRLBand
          Left = 0
          Top = 32
          Width = 742
          Height = 18
          BeforePrint = RLBand5BeforePrint
          object RLLabel56: TRLLabel
            Left = 35
            Top = 2
            Width = 70
            Height = 14
            Caption = 'Complemento:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLMemo2: TRLMemo
            Left = 107
            Top = 2
            Width = 605
            Height = 14
            Behavior = [beSiteExpander]
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand12: TRLBand
          Left = 0
          Top = 135
          Width = 742
          Height = 19
          BandType = btSummary
          BeforePrint = RLBand12BeforePrint
          object RLDraw14: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 18
            Align = faTop
          end
          object RLLabel62: TRLLabel
            Left = 12
            Top = 2
            Width = 56
            Height = 11
            Caption = 'Peso bruto:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel63: TRLLabel
            Left = 176
            Top = 2
            Width = 67
            Height = 11
            Caption = 'Peso L'#237'quido:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText55: TRLDBText
            Left = 247
            Top = 2
            Width = 68
            Height = 11
            DataField = 'PESOLIQUIDO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText56: TRLDBText
            Left = 70
            Top = 2
            Width = 61
            Height = 11
            DataField = 'PESOBRUTO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel65: TRLLabel
            Left = 416
            Top = 2
            Width = 48
            Height = 11
            Caption = 'Vlr. Frete:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText34: TRLDBText
            Left = 469
            Top = 2
            Width = 57
            Height = 11
            DataField = 'VLR_FRETE'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
        object RLBand14: TRLBand
          Left = 0
          Top = 154
          Width = 742
          Height = 19
          BandType = btSummary
          BeforePrint = RLBand14BeforePrint
          object RLDraw16: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 18
            Align = faTop
          end
          object RLLabel70: TRLLabel
            Left = 12
            Top = 2
            Width = 142
            Height = 11
            Caption = 'Vlr. ICMS. Combate a Pobreza:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel71: TRLLabel
            Left = 261
            Top = 2
            Width = 102
            Height = 11
            Caption = 'Vlr. ICMS UF Destino:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText61: TRLDBText
            Left = 155
            Top = 2
            Width = 74
            Height = 11
            DataField = 'VLR_ICMS_FCP'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText60: TRLDBText
            Left = 371
            Top = 2
            Width = 97
            Height = 11
            DataField = 'VLR_ICMS_UF_DEST'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel72: TRLLabel
            Left = 501
            Top = 2
            Width = 95
            Height = 11
            Caption = 'Vlr. ICMS UF Remet:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText62: TRLDBText
            Left = 611
            Top = 2
            Width = 104
            Height = 11
            DataField = 'VLR_ICMS_UF_REMET'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
      end
      object RLBand7: TRLBand
        Left = 0
        Top = 537
        Width = 742
        Height = 36
        BandType = btSummary
        IntegralHeight = False
        BeforePrint = RLBand7BeforePrint
        object RLDraw3: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 36
          Align = faClient
        end
        object RLLabel46: TRLLabel
          Left = 7
          Top = 2
          Width = 79
          Height = 14
          Caption = 'Observa'#231#245'es:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold, fsUnderline]
          ParentFont = False
        end
        object RLMemo1: TRLMemo
          Left = 7
          Top = 17
          Width = 705
          Height = 16
          Behavior = [beSiteExpander]
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          IntegralHeight = True
          ParentFont = False
        end
      end
      object RLBand8: TRLBand
        Left = 0
        Top = 105
        Width = 742
        Height = 74
        BandType = btHeader
        BeforePrint = RLBand8BeforePrint
        object RLDraw2: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 74
          Align = faClient
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel10: TRLLabel
          Left = 15
          Top = 4
          Width = 48
          Height = 16
          Caption = 'Cliente:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel11: TRLLabel
          Left = 18
          Top = 21
          Width = 45
          Height = 12
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel12: TRLLabel
          Left = 33
          Top = 34
          Width = 30
          Height = 12
          Caption = 'Bairro:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel13: TRLLabel
          Left = 28
          Top = 47
          Width = 35
          Height = 12
          Caption = 'Cidade:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText4: TRLDBText
          Left = 65
          Top = 4
          Width = 70
          Height = 16
          DataField = 'NOME_CLI'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText6: TRLDBText
          Left = 65
          Top = 34
          Width = 83
          Height = 12
          DataField = 'BAIRRO_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel19: TRLLabel
          Left = 601
          Top = 21
          Width = 27
          Height = 12
          Caption = 'Fone:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel20: TRLLabel
          Left = 455
          Top = 21
          Width = 23
          Height = 12
          Caption = 'Cep:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel21: TRLLabel
          Left = 443
          Top = 34
          Width = 35
          Height = 12
          Caption = 'Estado:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel23: TRLLabel
          Left = 428
          Top = 60
          Width = 50
          Height = 12
          Caption = 'Inscr. Est.:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel24: TRLLabel
          Left = 447
          Top = 47
          Width = 31
          Height = 12
          Caption = 'CNPJ:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText11: TRLDBText
          Left = 655
          Top = 21
          Width = 73
          Height = 12
          DataField = 'FONE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText12: TRLDBText
          Left = 482
          Top = 21
          Width = 66
          Height = 12
          DataField = 'CEP_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText13: TRLDBText
          Left = 482
          Top = 34
          Width = 16
          Height = 12
          DataField = 'UF'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText14: TRLDBText
          Left = 482
          Top = 47
          Width = 96
          Height = 12
          DataField = 'CNPJ_CPF_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText15: TRLDBText
          Left = 482
          Top = 60
          Width = 99
          Height = 12
          DataField = 'INSCR_EST_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel25: TRLLabel
          Left = 606
          Top = 34
          Width = 22
          Height = 12
          Caption = 'Fax:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText17: TRLDBText
          Left = 656
          Top = 34
          Width = 64
          Height = 12
          DataField = 'FAX_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel18: TRLLabel
          Left = 13
          Top = 60
          Width = 50
          Height = 12
          Alignment = taRightJustify
          Caption = 'Email NFe:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText7: TRLDBText
          Left = 629
          Top = 21
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object rlEndereco: TRLLabel
          Left = 65
          Top = 21
          Width = 368
          Height = 12
          AutoSize = False
          Caption = 'ENDERE'#199'O, N'#218'MERO, COMPLEMENTO'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText37: TRLDBText
          Left = 65
          Top = 47
          Width = 83
          Height = 12
          DataField = 'CIDADE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText38: TRLDBText
          Left = 65
          Top = 60
          Width = 98
          Height = 12
          DataField = 'EMAIL_NFE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText39: TRLDBText
          Left = 630
          Top = 34
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_FAX_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLBand6: TRLBand
        Left = 0
        Top = 179
        Width = 742
        Height = 71
        BandType = btHeader
        BeforePrint = RLBand6BeforePrint
        object RLDraw9: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 71
          Align = faClient
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel31: TRLLabel
          Left = 23
          Top = 58
          Width = 35
          Height = 12
          Alignment = taRightJustify
          Caption = 'Cidade:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel47: TRLLabel
          Left = 28
          Top = 45
          Width = 30
          Height = 12
          Alignment = taRightJustify
          Caption = 'Bairro:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel48: TRLLabel
          Left = 13
          Top = 32
          Width = 45
          Height = 12
          Alignment = taRightJustify
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel49: TRLLabel
          Left = 27
          Top = 19
          Width = 31
          Height = 12
          Alignment = taRightJustify
          Caption = 'Nome:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel51: TRLLabel
          Left = 448
          Top = 32
          Width = 23
          Height = 12
          Caption = 'Cep:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel52: TRLLabel
          Left = 436
          Top = 45
          Width = 35
          Height = 12
          Caption = 'Estado:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel53: TRLLabel
          Left = 440
          Top = 58
          Width = 31
          Height = 12
          Caption = 'CNPJ:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel54: TRLLabel
          Left = 583
          Top = 58
          Width = 50
          Height = 12
          Caption = 'Inscr. Est.:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel55: TRLLabel
          Left = 426
          Top = 19
          Width = 45
          Height = 12
          Caption = 'Telefone :'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel50: TRLLabel
          Left = 4
          Top = 1
          Width = 127
          Height = 18
          Borders.Sides = sdCustom
          Borders.DrawLeft = True
          Borders.DrawTop = True
          Borders.DrawRight = True
          Borders.DrawBottom = True
          Caption = ' Endere'#231'o de Entrega '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object rlEndEntrega: TRLLabel
          Left = 60
          Top = 32
          Width = 362
          Height = 12
          AutoSize = False
          Caption = 'ENDERE'#199'O, N'#218'MERO, COMPLEMENTO'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText40: TRLDBText
          Left = 60
          Top = 45
          Width = 62
          Height = 12
          DataField = 'BAIRRO_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText41: TRLDBText
          Left = 60
          Top = 19
          Width = 64
          Height = 11
          DataField = 'NOMECLIENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText42: TRLDBText
          Left = 60
          Top = 58
          Width = 62
          Height = 12
          DataField = 'CIDADE_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText43: TRLDBText
          Left = 472
          Top = 19
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText44: TRLDBText
          Left = 498
          Top = 19
          Width = 52
          Height = 12
          DataField = 'FONE_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText45: TRLDBText
          Left = 472
          Top = 32
          Width = 45
          Height = 12
          DataField = 'CEP_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText46: TRLDBText
          Left = 472
          Top = 45
          Width = 39
          Height = 12
          DataField = 'UF_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText47: TRLDBText
          Left = 472
          Top = 58
          Width = 75
          Height = 12
          DataField = 'CNPJ_CPF_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText48: TRLDBText
          Left = 634
          Top = 58
          Width = 71
          Height = 12
          DataField = 'INSC_EST_ENT'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLBand9: TRLBand
        Left = 0
        Top = 250
        Width = 742
        Height = 28
        BandType = btHeader
        BeforePrint = RLBand9BeforePrint
        object RLDraw4: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 28
          Align = faClient
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel15: TRLLabel
          Left = 16
          Top = 2
          Width = 48
          Height = 12
          Caption = 'Transport.:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText9: TRLDBText
          Left = 65
          Top = 2
          Width = 53
          Height = 12
          DataField = 'NOME_TRA'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel5: TRLLabel
          Left = 6
          Top = 15
          Width = 58
          Height = 12
          Caption = 'Redespacho:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText27: TRLDBText
          Left = 65
          Top = 15
          Width = 55
          Height = 12
          DataField = 'NOME_RED'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLBand10: TRLBand
        Left = 0
        Top = 278
        Width = 742
        Height = 31
        BandType = btHeader
        BeforePrint = RLBand10BeforePrint
        object RLDraw12: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 31
          Align = faClient
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel9: TRLLabel
          Left = 23
          Top = 15
          Width = 108
          Height = 12
          Caption = 'Condi'#231#227'o de Pagamento:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText28: TRLDBText
          Left = 134
          Top = 15
          Width = 547
          Height = 12
          AutoSize = False
          DataField = 'NOME_CONDPGTO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel39: TRLLabel
          Left = 559
          Top = 2
          Width = 80
          Height = 12
          Caption = 'Vlr. Adiantamento:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText50: TRLDBText
          Left = 640
          Top = 2
          Width = 98
          Height = 12
          DataField = 'VLR_ADIANTAMENTO'
          DataSource = DMCadPedido.dsPedidoImp
          DisplayMask = '0.00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel14: TRLLabel
          Left = 83
          Top = 2
          Width = 48
          Height = 12
          Caption = 'Tipo Frete:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object rlTipoFrete: TRLLabel
          Left = 134
          Top = 2
          Width = 57
          Height = 12
          Caption = 'TIPO FRETE'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLBand11: TRLBand
        Left = 0
        Top = 309
        Width = 742
        Height = 34
        BandType = btHeader
        object RLLabel26: TRLLabel
          Left = 284
          Top = 1
          Width = 107
          Height = 20
          Borders.Sides = sdCustom
          Borders.DrawLeft = True
          Borders.DrawTop = True
          Borders.DrawRight = True
          Borders.DrawBottom = True
          Caption = 'Itens do Pedido'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel29: TRLLabel
          Left = 206
          Top = 23
          Width = 35
          Height = 11
          Caption = 'No. OS'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel30: TRLLabel
          Left = 88
          Top = 22
          Width = 40
          Height = 11
          Caption = 'Produto'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel33: TRLLabel
          Left = 6
          Top = 22
          Width = 22
          Height = 11
          Caption = 'Item'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel34: TRLLabel
          Left = 686
          Top = 22
          Width = 54
          Height = 11
          Alignment = taCenter
          AutoSize = False
          Caption = 'Pr.Total'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel35: TRLLabel
          Left = 517
          Top = 22
          Width = 54
          Height = 11
          Alignment = taCenter
          Caption = 'Pr.Unit'#225'rio'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel36: TRLLabel
          Left = 393
          Top = 22
          Width = 52
          Height = 11
          Alignment = taCenter
          Caption = 'Dt.Entrega'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel37: TRLLabel
          Left = 346
          Top = 22
          Width = 28
          Height = 11
          Alignment = taCenter
          Caption = 'Qtde.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel28: TRLLabel
          Left = 293
          Top = 23
          Width = 22
          Height = 11
          Alignment = taCenter
          Caption = 'Uni.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel42: TRLLabel
          Left = 36
          Top = 23
          Width = 41
          Height = 11
          Caption = 'ID Prod.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel22: TRLLabel
          Left = 614
          Top = 21
          Width = 32
          Height = 11
          Alignment = taCenter
          Caption = 'Vlr.IPI'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object rlVlrST: TRLLabel
          Left = 472
          Top = 21
          Width = 36
          Height = 11
          Alignment = taCenter
          Caption = 'Vlr. ST.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
      object RLBand13: TRLBand
        Left = 0
        Top = 573
        Width = 742
        Height = 34
        BandType = btFooter
        object RLDraw15: TRLDraw
          Left = 440
          Top = 31
          Width = 300
          Height = 2
          DrawKind = dkLine
        end
        object RLLabel67: TRLLabel
          Left = 378
          Top = 22
          Width = 59
          Height = 11
          Alignment = taRightJustify
          Caption = 'Ass. Cliente:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
    end
  end
end
