object fRelOrcamento: TfRelOrcamento
  Left = 235
  Top = 30
  Width = 924
  Height = 666
  VertScrollBar.Position = 326
  Caption = 'Relat'#243'rio Or'#231'amento'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 13
  object RLReport1: TRLReport
    Left = 56
    Top = -302
    Width = 794
    Height = 1123
    DataSource = DMCadPedido.dsPedidoImp
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    Margins.LeftMargin = 7.000000000000000000
    Margins.TopMargin = 9.000000000000000000
    Margins.RightMargin = 7.000000000000000000
    Margins.BottomMargin = 9.000000000000000000
    RecordRange = rrCurrentOnly
    ShowProgress = False
    BeforePrint = RLReport1BeforePrint
    object RLSubDetail1: TRLSubDetail
      Left = 26
      Top = 34
      Width = 742
      Height = 815
      DataSource = DMCadPedido.dsPedidoImp
      object RLBand1: TRLBand
        Left = 0
        Top = 0
        Width = 742
        Height = 224
        BandType = btTitle
        BeforePrint = RLBand1BeforePrint
        object RLDraw11: TRLDraw
          Left = 664
          Top = 26
          Width = 77
          Height = 79
        end
        object RLDraw10: TRLDraw
          Left = 128
          Top = 25
          Width = 537
          Height = 80
        end
        object RLDraw8: TRLDraw
          Left = 128
          Top = 1
          Width = 613
          Height = 26
        end
        object RLDraw1: TRLDraw
          Left = 0
          Top = 1
          Width = 129
          Height = 104
        end
        object RLImage1: TRLImage
          Left = 4
          Top = 6
          Width = 118
          Height = 95
          Borders.Sides = sdCustom
          Borders.DrawLeft = False
          Borders.DrawTop = False
          Borders.DrawRight = False
          Borders.DrawBottom = False
          Stretch = True
        end
        object RLLabel1: TRLLabel
          Left = 675
          Top = 30
          Width = 47
          Height = 12
          Caption = 'Impress'#227'o'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel2: TRLLabel
          Left = 686
          Top = 45
          Width = 26
          Height = 12
          Caption = 'Data:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel3: TRLLabel
          Left = 686
          Top = 74
          Width = 26
          Height = 12
          Caption = 'Hora:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLSystemInfo1: TRLSystemInfo
          Left = 668
          Top = 58
          Width = 62
          Height = 12
          Alignment = taCenter
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLSystemInfo2: TRLSystemInfo
          Left = 668
          Top = 90
          Width = 62
          Height = 12
          Alignment = taCenter
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          Info = itHour
          ParentFont = False
        end
        object RLLabel4: TRLLabel
          Left = 131
          Top = 9
          Width = 96
          Height = 16
          Caption = 'N'#186' Or'#231'amento:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel7: TRLLabel
          Left = 599
          Top = 9
          Width = 67
          Height = 14
          Caption = 'Dt.Emiss'#227'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText2: TRLDBText
          Left = 667
          Top = 9
          Width = 66
          Height = 14
          DataField = 'DTEMISSAO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDraw2: TRLDraw
          Left = 0
          Top = 107
          Width = 741
          Height = 65
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel10: TRLLabel
          Left = 26
          Top = 110
          Width = 35
          Height = 12
          Alignment = taRightJustify
          Caption = 'Cliente:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel11: TRLLabel
          Left = 16
          Top = 122
          Width = 45
          Height = 12
          Alignment = taRightJustify
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel12: TRLLabel
          Left = 31
          Top = 134
          Width = 30
          Height = 12
          Alignment = taRightJustify
          Caption = 'Bairro:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel13: TRLLabel
          Left = 26
          Top = 146
          Width = 35
          Height = 12
          Alignment = taRightJustify
          Caption = 'Cidade:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText4: TRLDBText
          Left = 65
          Top = 111
          Width = 75
          Height = 11
          DataField = 'NOME_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText6: TRLDBText
          Left = 65
          Top = 134
          Width = 83
          Height = 12
          DataField = 'BAIRRO_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel19: TRLLabel
          Left = 433
          Top = 110
          Width = 45
          Height = 12
          Alignment = taRightJustify
          Caption = 'Telefone :'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel20: TRLLabel
          Left = 455
          Top = 122
          Width = 23
          Height = 12
          Alignment = taRightJustify
          Caption = 'Cep:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel21: TRLLabel
          Left = 443
          Top = 134
          Width = 35
          Height = 12
          Alignment = taRightJustify
          Caption = 'Estado:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel23: TRLLabel
          Left = 428
          Top = 158
          Width = 50
          Height = 12
          Alignment = taRightJustify
          Caption = 'Inscr. Est.:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel24: TRLLabel
          Left = 447
          Top = 146
          Width = 31
          Height = 12
          Alignment = taRightJustify
          Caption = 'CNPJ:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText11: TRLDBText
          Left = 508
          Top = 110
          Width = 73
          Height = 12
          DataField = 'FONE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText12: TRLDBText
          Left = 482
          Top = 122
          Width = 66
          Height = 12
          DataField = 'CEP_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText13: TRLDBText
          Left = 482
          Top = 134
          Width = 16
          Height = 12
          DataField = 'UF'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText14: TRLDBText
          Left = 482
          Top = 146
          Width = 96
          Height = 12
          DataField = 'CNPJ_CPF_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText15: TRLDBText
          Left = 482
          Top = 158
          Width = 99
          Height = 12
          DataField = 'INSCR_EST_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel25: TRLLabel
          Left = 598
          Top = 110
          Width = 22
          Height = 12
          Caption = 'Fax:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText17: TRLDBText
          Left = 648
          Top = 110
          Width = 64
          Height = 12
          DataField = 'FAX_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText20: TRLDBText
          Left = 232
          Top = 9
          Width = 123
          Height = 16
          DataField = 'NUM_ORCAMENTO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel18: TRLLabel
          Left = 11
          Top = 158
          Width = 50
          Height = 12
          Alignment = taRightJustify
          Caption = 'Email NFe:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText7: TRLDBText
          Left = 482
          Top = 110
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object rlEndereco: TRLLabel
          Left = 65
          Top = 122
          Width = 368
          Height = 12
          AutoSize = False
          Caption = 'Endere'#231'o'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel6: TRLLabel
          Left = 137
          Top = 52
          Width = 45
          Height = 12
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object rlEndFilial: TRLLabel
          Left = 184
          Top = 52
          Width = 473
          Height = 12
          AutoSize = False
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText1: TRLDBText
          Left = 184
          Top = 65
          Width = 305
          Height = 12
          AutoSize = False
          DataField = 'BAIRRO_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel16: TRLLabel
          Left = 152
          Top = 65
          Width = 30
          Height = 12
          Caption = 'Bairro:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel17: TRLLabel
          Left = 147
          Top = 78
          Width = 35
          Height = 12
          Caption = 'Cidade:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel57: TRLLabel
          Left = 375
          Top = 91
          Width = 31
          Height = 12
          Caption = 'CNPJ:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText5: TRLDBText
          Left = 408
          Top = 91
          Width = 85
          Height = 12
          DataField = 'CNPJ_CPF_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel58: TRLLabel
          Left = 500
          Top = 91
          Width = 50
          Height = 12
          Caption = 'Inscr. Est.:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText10: TRLDBText
          Left = 551
          Top = 91
          Width = 88
          Height = 12
          DataField = 'INSCR_EST_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel59: TRLLabel
          Left = 515
          Top = 78
          Width = 35
          Height = 12
          Caption = 'Estado:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText19: TRLDBText
          Left = 551
          Top = 78
          Width = 49
          Height = 12
          DataField = 'UF_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel60: TRLLabel
          Left = 138
          Top = 91
          Width = 45
          Height = 12
          Caption = 'Telefone :'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText24: TRLDBText
          Left = 184
          Top = 91
          Width = 24
          Height = 11
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText30: TRLDBText
          Left = 209
          Top = 91
          Width = 62
          Height = 12
          DataField = 'FONE_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel61: TRLLabel
          Left = 527
          Top = 65
          Width = 23
          Height = 12
          Caption = 'Cep:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText35: TRLDBText
          Left = 551
          Top = 65
          Width = 55
          Height = 12
          DataField = 'CEP_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText36: TRLDBText
          Left = 184
          Top = 78
          Width = 305
          Height = 12
          AutoSize = False
          DataField = 'CIDADE_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText31: TRLDBText
          Left = 136
          Top = 32
          Width = 521
          Height = 14
          AutoSize = False
          DataField = 'NOME_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText37: TRLDBText
          Left = 65
          Top = 146
          Width = 83
          Height = 12
          DataField = 'CIDADE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText38: TRLDBText
          Left = 65
          Top = 158
          Width = 98
          Height = 12
          DataField = 'EMAIL_NFE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText39: TRLDBText
          Left = 622
          Top = 110
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_FAX_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw12: TRLDraw
          Left = 1
          Top = 174
          Width = 740
          Height = 23
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel9: TRLLabel
          Left = 9
          Top = 179
          Width = 122
          Height = 14
          Caption = 'Condi'#231#227'o de Pagamento:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText28: TRLDBText
          Left = 134
          Top = 180
          Width = 513
          Height = 12
          AutoSize = False
          DataField = 'NOME_CONDPGTO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw4: TRLDraw
          Left = 1
          Top = 199
          Width = 740
          Height = 23
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel5: TRLLabel
          Left = 9
          Top = 203
          Width = 48
          Height = 14
          Caption = 'Validade:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText3: TRLDBText
          Left = 59
          Top = 204
          Width = 513
          Height = 12
          AutoSize = False
          DataField = 'VALIDADE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLSubDetail2: TRLSubDetail
        Left = 0
        Top = 224
        Width = 742
        Height = 193
        DataSource = DMCadPedido.dsPedidoImp_Itens
        object RLBand2: TRLBand
          Left = 0
          Top = 48
          Width = 742
          Height = 32
          BeforePrint = RLBand2BeforePrint
          object RLDBText18: TRLDBText
            Left = 2
            Top = 7
            Width = 30
            Height = 18
            Alignment = taCenter
            AutoSize = False
            Borders.Sides = sdCustom
            Borders.DrawLeft = True
            Borders.DrawTop = True
            Borders.DrawRight = True
            Borders.DrawBottom = True
            DataField = 'ITEM'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText21: TRLDBText
            Left = 362
            Top = 16
            Width = 74
            Height = 13
            Alignment = taCenter
            AutoSize = False
            DataField = 'DTENTREGA'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText22: TRLDBText
            Left = 299
            Top = 15
            Width = 24
            Height = 14
            Alignment = taRightJustify
            DataField = 'QTD'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText26: TRLDBText
            Left = 126
            Top = 2
            Width = 595
            Height = 12
            AutoSize = False
            DataField = 'NOMEPRODUTO'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText29: TRLDBText
            Left = 35
            Top = 2
            Width = 90
            Height = 12
            AutoSize = False
            DataField = 'REFERENCIA'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDraw7: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 1
            Align = faTop
            DrawKind = dkLine
          end
          object RLDBText49: TRLDBText
            Left = 231
            Top = 18
            Width = 36
            Height = 11
            Alignment = taCenter
            AutoSize = False
            DataField = 'UNIDADE'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText16: TRLDBText
            Left = 515
            Top = 15
            Width = 77
            Height = 14
            Alignment = taRightJustify
            DataField = 'VLR_UNITARIO'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText23: TRLDBText
            Left = 675
            Top = 15
            Width = 64
            Height = 14
            Alignment = taRightJustify
            DataField = 'VLR_TOTAL'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText25: TRLDBText
            Left = 456
            Top = 15
            Width = 40
            Height = 14
            Alignment = taRightJustify
            DataField = 'VLR_IPI'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText33: TRLDBText
            Left = 595
            Top = 14
            Width = 74
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_DESCONTO_CALC'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand4: TRLBand
          Left = 0
          Top = 98
          Width = 742
          Height = 20
          BandType = btSummary
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          BeforePrint = RLBand4BeforePrint
          object RLDraw5: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 19
            Align = faTop
          end
          object RLLabel40: TRLLabel
            Left = 8
            Top = 3
            Width = 113
            Height = 14
            Caption = 'Vlr. Total de Mercs.:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText32: TRLDBText
            Left = 124
            Top = 3
            Width = 111
            Height = 13
            AutoSize = False
            DataField = 'VLR_ITENS'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel8: TRLLabel
            Left = 566
            Top = 3
            Width = 51
            Height = 14
            Caption = 'Valor IPI:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText9: TRLDBText
            Left = 621
            Top = 4
            Width = 113
            Height = 13
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_IPI'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel29: TRLLabel
            Left = 264
            Top = 3
            Width = 80
            Height = 14
            Caption = 'Vlr. Desconto:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText40: TRLDBText
            Left = 348
            Top = 3
            Width = 111
            Height = 13
            AutoSize = False
            DataField = 'VLR_DESCONTO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
        object RLBand5: TRLBand
          Left = 0
          Top = 80
          Width = 742
          Height = 18
          BeforePrint = RLBand5BeforePrint
          object RLLabel56: TRLLabel
            Left = 35
            Top = 2
            Width = 70
            Height = 14
            Caption = 'Complemento:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLMemo2: TRLMemo
            Left = 107
            Top = 2
            Width = 605
            Height = 14
            Behavior = [beSiteExpander]
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand3: TRLBand
          Left = 0
          Top = 0
          Width = 742
          Height = 48
          BandType = btColumnHeader
          object RLLabel26: TRLLabel
            Left = 284
            Top = 1
            Width = 158
            Height = 20
            Borders.Sides = sdCustom
            Borders.DrawLeft = True
            Borders.DrawTop = True
            Borders.DrawRight = True
            Borders.DrawBottom = True
            Caption = 'Produtos do Or'#231'amento'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel30: TRLLabel
            Left = 130
            Top = 36
            Width = 40
            Height = 11
            Caption = 'Produto'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel32: TRLLabel
            Left = 34
            Top = 36
            Width = 51
            Height = 11
            Caption = 'Refer'#234'ncia'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel33: TRLLabel
            Left = 6
            Top = 36
            Width = 22
            Height = 11
            Caption = 'Item'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel34: TRLLabel
            Left = 682
            Top = 36
            Width = 54
            Height = 11
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Pr.Total'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel35: TRLLabel
            Left = 536
            Top = 36
            Width = 54
            Height = 11
            Alignment = taRightJustify
            Caption = 'Pr.Unit'#225'rio'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel36: TRLLabel
            Left = 371
            Top = 36
            Width = 52
            Height = 11
            Alignment = taCenter
            Caption = 'Dt.Entrega'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel37: TRLLabel
            Left = 297
            Top = 36
            Width = 28
            Height = 11
            Alignment = taCenter
            Caption = 'Qtde.'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel28: TRLLabel
            Left = 237
            Top = 36
            Width = 22
            Height = 11
            Alignment = taCenter
            Caption = 'Uni.'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel14: TRLLabel
            Left = 460
            Top = 36
            Width = 34
            Height = 11
            Alignment = taRightJustify
            Caption = 'Vlr. IPI'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel27: TRLLabel
            Left = 629
            Top = 37
            Width = 37
            Height = 11
            Alignment = taRightJustify
            Caption = 'V.Desc.'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
      end
      object RLBand7: TRLBand
        Left = 0
        Top = 594
        Width = 742
        Height = 37
        BandType = btSummary
        IntegralHeight = False
        BeforePrint = RLBand7BeforePrint
        object RLDraw3: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 37
          Align = faClient
        end
        object RLLabel46: TRLLabel
          Left = 7
          Top = 2
          Width = 79
          Height = 14
          Caption = 'Observa'#231#245'es:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold, fsUnderline]
          ParentFont = False
        end
        object RLMemo1: TRLMemo
          Left = 7
          Top = 17
          Width = 705
          Height = 16
          Behavior = [beSiteExpander]
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          IntegralHeight = True
          ParentFont = False
        end
      end
      object RLSubDetail3: TRLSubDetail
        Left = 0
        Top = 417
        Width = 742
        Height = 144
        DataSource = DMCadPedido.dsPedidoImp_Serv
        object RLBand8: TRLBand
          Left = 0
          Top = 0
          Width = 742
          Height = 47
          BandType = btColumnHeader
          BeforePrint = RLBand8BeforePrint
          object RLLabel31: TRLLabel
            Left = 284
            Top = 12
            Width = 156
            Height = 20
            Borders.Sides = sdCustom
            Borders.DrawLeft = True
            Borders.DrawTop = True
            Borders.DrawRight = True
            Borders.DrawBottom = True
            Caption = 'Servi'#231'os do Or'#231'amento'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel39: TRLLabel
            Left = 42
            Top = 35
            Width = 37
            Height = 11
            Caption = 'Servi'#231'o'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel41: TRLLabel
            Left = 6
            Top = 35
            Width = 22
            Height = 11
            Caption = 'Item'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel42: TRLLabel
            Left = 685
            Top = 35
            Width = 54
            Height = 11
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Pr.Total'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel43: TRLLabel
            Left = 608
            Top = 35
            Width = 54
            Height = 11
            Alignment = taRightJustify
            Caption = 'Pr.Unit'#225'rio'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel47: TRLLabel
            Left = 562
            Top = 35
            Width = 28
            Height = 11
            Alignment = taCenter
            Caption = 'Qtde.'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
        object RLBand9: TRLBand
          Left = 0
          Top = 47
          Width = 742
          Height = 18
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          BeforePrint = RLBand9BeforePrint
          object RLDBText41: TRLDBText
            Left = 4
            Top = 1
            Width = 24
            Height = 12
            DataField = 'ITEM'
            DataSource = DMCadPedido.dsPedidoImp_Serv
          end
          object RLMemo3: TRLMemo
            Left = 37
            Top = 0
            Width = 511
            Height = 12
            Behavior = [beSiteExpander]
          end
          object RLDBText42: TRLDBText
            Left = 549
            Top = 1
            Width = 42
            Height = 12
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'QTD'
            DataSource = DMCadPedido.dsPedidoImp_Serv
          end
          object RLDBText43: TRLDBText
            Left = 596
            Top = 1
            Width = 66
            Height = 12
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_UNITARIO'
            DataSource = DMCadPedido.dsPedidoImp_Serv
          end
          object RLDBText44: TRLDBText
            Left = 664
            Top = 1
            Width = 75
            Height = 12
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_TOTAL'
            DataSource = DMCadPedido.dsPedidoImp_Serv
          end
        end
        object RLBand10: TRLBand
          Left = 0
          Top = 65
          Width = 742
          Height = 18
          BandType = btSummary
          BeforePrint = RLBand10BeforePrint
          object RLLabel38: TRLLabel
            Left = 477
            Top = 1
            Width = 109
            Height = 14
            Caption = 'Valor Total Servi'#231'o:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText45: TRLDBText
            Left = 627
            Top = 1
            Width = 113
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_SERVICO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
      end
      object RLBand6: TRLBand
        Left = 0
        Top = 561
        Width = 742
        Height = 33
        BandType = btSummary
        BeforePrint = RLBand6BeforePrint
        object RLDraw6: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 33
          Align = faClient
        end
        object RLLabel45: TRLLabel
          Left = 471
          Top = 17
          Width = 146
          Height = 14
          Caption = 'Valor Total do Or'#231'amento:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel22: TRLLabel
          Left = 47
          Top = 2
          Width = 74
          Height = 14
          Alignment = taRightJustify
          Caption = 'Vlr. do Frete:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText27: TRLDBText
          Left = 124
          Top = 2
          Width = 111
          Height = 13
          AutoSize = False
          DataField = 'VLR_FRETE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel15: TRLLabel
          Left = 481
          Top = 2
          Width = 136
          Height = 14
          Alignment = taRightJustify
          Caption = 'Valor Icms Substitui'#231#227'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel44: TRLLabel
          Left = 623
          Top = 17
          Width = 116
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = '0,00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel48: TRLLabel
          Left = 623
          Top = 2
          Width = 116
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = '0,00'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
      object RLBand11: TRLBand
        Left = 0
        Top = 631
        Width = 742
        Height = 82
        BandType = btFooter
        Borders.Sides = sdCustom
        Borders.DrawLeft = True
        Borders.DrawTop = True
        Borders.DrawRight = True
        Borders.DrawBottom = True
        BeforePrint = RLBand6BeforePrint
        object RLLabel51: TRLLabel
          Left = 238
          Top = 63
          Width = 118
          Height = 12
          Caption = 'Assinatura do Respons'#225'vel'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw9: TRLDraw
          Left = 176
          Top = 60
          Width = 257
          Height = 4
          DrawKind = dkLine
        end
        object RLLabel52: TRLLabel
          Left = 566
          Top = 63
          Width = 92
          Height = 12
          Caption = 'Assinatura do Cliente'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw13: TRLDraw
          Left = 480
          Top = 60
          Width = 257
          Height = 4
          DrawKind = dkLine
        end
        object RLLabel133: TRLLabel
          Left = 62
          Top = 63
          Width = 23
          Height = 12
          Caption = 'Data'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw14: TRLDraw
          Left = 8
          Top = 58
          Width = 129
          Height = 7
          DrawKind = dkLine
        end
        object RLImage2: TRLImage
          Left = 181
          Top = 12
          Width = 244
          Height = 42
          Stretch = True
        end
      end
    end
  end
end
