object fRelNotaBeneficiamento: TfRelNotaBeneficiamento
  Left = 82
  Top = 154
  Width = 1221
  Height = 532
  Caption = 'fRelNotaBeneficiamento'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 13
  object RLReport1: TRLReport
    Left = 24
    Top = 16
    Width = 1123
    Height = 794
    DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'Arial'
    Font.Style = []
    Margins.LeftMargin = 7.000000000000000000
    Margins.TopMargin = 7.000000000000000000
    Margins.RightMargin = 7.000000000000000000
    Margins.BottomMargin = 7.000000000000000000
    PageSetup.Orientation = poLandscape
    ShowProgress = False
    BeforePrint = RLReport1BeforePrint
    object RLBand1: TRLBand
      Left = 26
      Top = 26
      Width = 1071
      Height = 69
      BandType = btHeader
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      BeforePrint = RLBand1BeforePrint
      object RLLabel1: TRLLabel
        Left = 440
        Top = 4
        Width = 149
        Height = 16
        Caption = 'RELAT'#211'RIO DE NOTAS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold, fsUnderline]
        ParentFont = False
      end
      object RLLabel21: TRLLabel
        Left = 969
        Top = 2
        Width = 22
        Height = 12
        Caption = 'Pag:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLSystemInfo1: TRLSystemInfo
        Left = 995
        Top = 3
        Width = 32
        Height = 12
        Alignment = taCenter
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        Info = itPageNumber
        ParentFont = False
      end
      object RLLabel22: TRLLabel
        Left = 949
        Top = 18
        Width = 42
        Height = 12
        Caption = 'Emiss'#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLSystemInfo2: TRLSystemInfo
        Left = 995
        Top = 19
        Width = 64
        Height = 12
        Alignment = taCenter
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel2: TRLLabel
        Left = 0
        Top = 39
        Width = 33
        Height = 12
        Caption = 'Op'#231#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object rllbOpcao: TRLLabel
        Left = 35
        Top = 39
        Width = 33
        Height = 12
        Caption = 'Op'#231#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object RLLabel7: TRLLabel
        Left = 255
        Top = 53
        Width = 40
        Height = 14
        Caption = 'Material'
      end
      object RLLabel8: TRLLabel
        Left = 718
        Top = 53
        Width = 23
        Height = 14
        Caption = 'Qtd.'
      end
      object RLDraw1: TRLDraw
        Left = 0
        Top = 67
        Width = 1071
        Height = 2
        Align = faBottom
        DrawKind = dkLine
      end
      object RLLabel9: TRLLabel
        Left = 3
        Top = 54
        Width = 39
        Height = 12
        Caption = 'N'#186' Nota:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel10: TRLLabel
        Left = 57
        Top = 54
        Width = 24
        Height = 12
        Caption = 'S'#233'rie'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel11: TRLLabel
        Left = 85
        Top = 54
        Width = 13
        Height = 12
        Caption = 'Fil'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel12: TRLLabel
        Left = 159
        Top = 53
        Width = 29
        Height = 12
        Caption = 'CFOP'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel6: TRLLabel
        Left = 851
        Top = 53
        Width = 70
        Height = 14
        Caption = 'Qtd.Devolvida'
      end
      object RLLabel13: TRLLabel
        Left = 765
        Top = 52
        Width = 68
        Height = 14
        Caption = 'Qtd.Pendente'
      end
      object RLLabel4: TRLLabel
        Left = 938
        Top = 52
        Width = 56
        Height = 14
        Caption = 'Vlr.Unit'#225'rio'
      end
      object RLLabel5: TRLLabel
        Left = 198
        Top = 54
        Width = 52
        Height = 12
        Caption = 'Dt.Emiss'#227'o'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel14: TRLLabel
        Left = 1004
        Top = 52
        Width = 65
        Height = 14
        Caption = 'Vlr.Pendente'
      end
      object RLLabel29: TRLLabel
        Left = 3
        Top = 5
        Width = 358
        Height = 12
        AutoSize = False
        Caption = 'Fornecedor:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
    end
    object RLSubDetail1: TRLSubDetail
      Left = 26
      Top = 95
      Width = 1071
      Height = 146
      DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
      object RLBand2: TRLBand
        Left = 0
        Top = 0
        Width = 1071
        Height = 16
        BeforePrint = RLBand2BeforePrint
        object RLDBText2: TRLDBText
          Left = 292
          Top = 2
          Width = 371
          Height = 11
          AutoSize = False
          DataField = 'NOMEPRODUTO'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText3: TRLDBText
          Left = 666
          Top = 2
          Width = 85
          Height = 11
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'QTD'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw2: TRLDraw
          Left = 0
          Top = 14
          Width = 1071
          Height = 2
          Align = faBottom
          DrawKind = dkLine
          Pen.Style = psDot
          Visible = False
        end
        object RLDBText5: TRLDBText
          Left = 1
          Top = 2
          Width = 54
          Height = 11
          Alignment = taCenter
          AutoSize = False
          DataField = 'NUMNOTA'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText1: TRLDBText
          Left = 56
          Top = 2
          Width = 26
          Height = 11
          Alignment = taCenter
          AutoSize = False
          DataField = 'SERIE'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText4: TRLDBText
          Left = 82
          Top = 2
          Width = 18
          Height = 11
          Alignment = taCenter
          AutoSize = False
          DataField = 'FILIAL'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText6: TRLDBText
          Left = 159
          Top = 2
          Width = 34
          Height = 11
          Alignment = taCenter
          AutoSize = False
          DataField = 'CODCFOP'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText7: TRLDBText
          Left = 193
          Top = 2
          Width = 60
          Height = 11
          Alignment = taCenter
          AutoSize = False
          DataField = 'DTEMISSAO'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText8: TRLDBText
          Left = 838
          Top = 2
          Width = 85
          Height = 11
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'QTDDEVOLVIDA'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText9: TRLDBText
          Left = 752
          Top = 2
          Width = 85
          Height = 11
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'QTDRESTANTE'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText10: TRLDBText
          Left = 924
          Top = 2
          Width = 74
          Height = 11
          Alignment = taRightJustify
          AutoSize = False
          DataField = 'VLR_UNITARIO'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel15: TRLLabel
          Left = 999
          Top = 2
          Width = 70
          Height = 11
          Alignment = taRightJustify
          AutoSize = False
          Caption = '0.00'
        end
        object RLDBText11: TRLDBText
          Left = 100
          Top = 2
          Width = 58
          Height = 11
          AutoSize = False
          DataField = 'NOMEFILIAL'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -8
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText19: TRLDBText
          Left = 255
          Top = 2
          Width = 36
          Height = 11
          Alignment = taCenter
          AutoSize = False
          DataField = 'ID_PRODUTO'
          DataSource = DMConsNotaBeneficiamento.dsNotaEntrada
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object RLSubDetail2: TRLSubDetail
        Left = 0
        Top = 16
        Width = 1071
        Height = 62
        DataSource = DMConsNotaBeneficiamento.dsNotaDevolvida
        object RLDetailGrid1: TRLDetailGrid
          Left = 0
          Top = 17
          Width = 1071
          Height = 16
          ColCount = 3
          BeforePrint = RLDetailGrid1BeforePrint
          object RLDBText13: TRLDBText
            Left = 232
            Top = 2
            Width = 89
            Height = 12
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'QTD'
            DataSource = DMConsNotaBeneficiamento.dsNotaDevolvida
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText12: TRLDBText
            Left = 157
            Top = 2
            Width = 56
            Height = 12
            DataField = 'DTEMISSAO'
            DataSource = DMConsNotaBeneficiamento.dsNotaDevolvida
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText14: TRLDBText
            Left = 55
            Top = 2
            Width = 58
            Height = 13
            Alignment = taCenter
            AutoSize = False
            DataField = 'NUMNOTA'
            DataSource = DMConsNotaBeneficiamento.dsNotaDevolvida
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDraw3: TRLDraw
            Left = 351
            Top = 1
            Width = 3
            Height = 15
            Pen.Style = psDot
          end
          object RLDBText15: TRLDBText
            Left = 119
            Top = 2
            Width = 32
            Height = 13
            Alignment = taCenter
            AutoSize = False
            DataField = 'SERIE'
            DataSource = DMConsNotaBeneficiamento.dsNotaDevolvida
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel33: TRLLabel
            Left = 327
            Top = 1
            Width = 19
            Height = 14
            Caption = 'E/S'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand3: TRLBand
          Left = 0
          Top = 0
          Width = 1071
          Height = 17
          BandType = btHeader
          BeforePrint = RLBand3BeforePrint
          object RLDraw9: TRLDraw
            Left = 24
            Top = 0
            Width = 1041
            Height = 16
          end
          object RLLabel3: TRLLabel
            Left = 55
            Top = 2
            Width = 56
            Height = 14
            Caption = 'Nota Fiscal'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel16: TRLLabel
            Left = 159
            Top = 2
            Width = 56
            Height = 14
            Caption = 'Dt.Emiss'#227'o'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel17: TRLLabel
            Left = 263
            Top = 2
            Width = 58
            Height = 14
            Caption = 'Quantidade'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDraw4: TRLDraw
            Left = 351
            Top = 2
            Width = 3
            Height = 14
            Pen.Style = psDot
          end
          object RLLabel28: TRLLabel
            Left = 119
            Top = 3
            Width = 28
            Height = 14
            Caption = 'S'#233'rie'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel32: TRLLabel
            Left = 327
            Top = 1
            Width = 19
            Height = 14
            Caption = 'E/S'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel18: TRLLabel
            Left = 411
            Top = 1
            Width = 56
            Height = 14
            Caption = 'Nota Fiscal'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel19: TRLLabel
            Left = 515
            Top = 1
            Width = 56
            Height = 14
            Caption = 'Dt.Emiss'#227'o'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel20: TRLLabel
            Left = 619
            Top = 1
            Width = 58
            Height = 14
            Caption = 'Quantidade'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel24: TRLLabel
            Left = 475
            Top = 1
            Width = 28
            Height = 14
            Caption = 'S'#233'rie'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel26: TRLLabel
            Left = 683
            Top = 1
            Width = 19
            Height = 14
            Caption = 'E/S'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel40: TRLLabel
            Left = 768
            Top = 1
            Width = 56
            Height = 14
            Caption = 'Nota Fiscal'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel41: TRLLabel
            Left = 872
            Top = 1
            Width = 56
            Height = 14
            Caption = 'Dt.Emiss'#227'o'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel42: TRLLabel
            Left = 976
            Top = 1
            Width = 58
            Height = 14
            Caption = 'Quantidade'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel44: TRLLabel
            Left = 832
            Top = 1
            Width = 28
            Height = 14
            Caption = 'S'#233'rie'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel45: TRLLabel
            Left = 1040
            Top = 1
            Width = 19
            Height = 14
            Caption = 'E/S'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDraw8: TRLDraw
            Left = 707
            Top = 3
            Width = 3
            Height = 14
            Pen.Style = psDot
          end
        end
        object RLBand6: TRLBand
          Left = 0
          Top = 33
          Width = 1071
          Height = 15
          BandType = btFooter
          BeforePrint = RLBand6BeforePrint
          object RLDraw5: TRLDraw
            Left = 0
            Top = 0
            Width = 1071
            Height = 3
            Align = faTop
            DrawKind = dkLine
            Pen.Style = psDot
          end
        end
      end
    end
  end
  object RLReport2: TRLReport
    Left = 1165
    Top = 16
    Width = 794
    Height = 1123
    DataSource = DMConsNotaBeneficiamento.dsmMaterial
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -9
    Font.Name = 'Arial'
    Font.Style = []
    Margins.LeftMargin = 7.000000000000000000
    Margins.TopMargin = 7.000000000000000000
    Margins.RightMargin = 7.000000000000000000
    Margins.BottomMargin = 7.000000000000000000
    BeforePrint = RLReport2BeforePrint
    object RLSubDetail3: TRLSubDetail
      Left = 26
      Top = 94
      Width = 742
      Height = 367
      DataSource = DMConsNotaBeneficiamento.dsmMaterial
      object RLBand5: TRLBand
        Left = 0
        Top = 0
        Width = 742
        Height = 16
        object RLDBMemo1: TRLDBMemo
          Left = 2
          Top = 1
          Width = 479
          Height = 12
          Behavior = [beSiteExpander]
          DataField = 'Nome'
          DataSource = DMConsNotaBeneficiamento.dsmMaterial
        end
        object RLDBText16: TRLDBText
          Left = 684
          Top = 1
          Width = 56
          Height = 12
          Alignment = taRightJustify
          DataField = 'QtdRestante'
          DataSource = DMConsNotaBeneficiamento.dsmMaterial
        end
        object RLDBText17: TRLDBText
          Left = 593
          Top = 2
          Width = 61
          Height = 12
          Alignment = taRightJustify
          DataField = 'QtdDevolvida'
          DataSource = DMConsNotaBeneficiamento.dsmMaterial
        end
        object RLDBText18: TRLDBText
          Left = 549
          Top = 2
          Width = 18
          Height = 12
          Alignment = taRightJustify
          DataField = 'Qtd'
          DataSource = DMConsNotaBeneficiamento.dsmMaterial
        end
        object RLDraw7: TRLDraw
          Left = 0
          Top = 14
          Width = 742
          Height = 2
          Align = faBottom
          DrawKind = dkLine
          Pen.Style = psDot
        end
      end
    end
    object RLBand4: TRLBand
      Left = 26
      Top = 26
      Width = 742
      Height = 68
      BandType = btHeader
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      BeforePrint = RLBand4BeforePrint
      object RLLabel30: TRLLabel
        Left = 200
        Top = 21
        Width = 339
        Height = 16
        Caption = 'Relat'#243'rio de Materiais de Terceiros (Beneficiamento)'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold, fsUnderline]
        ParentFont = False
      end
      object RLLabel31: TRLLabel
        Left = 0
        Top = 39
        Width = 33
        Height = 12
        Caption = 'Op'#231#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object rllbOpcao_Mat: TRLLabel
        Left = 35
        Top = 39
        Width = 33
        Height = 12
        Caption = 'Op'#231#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object rllbFornecedor_Mat: TRLLabel
        Left = 3
        Top = 5
        Width = 358
        Height = 12
        AutoSize = False
        Caption = 'Fornecedor:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object RLLabel34: TRLLabel
        Left = 648
        Top = 2
        Width = 22
        Height = 12
        Caption = 'Pag:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel35: TRLLabel
        Left = 628
        Top = 18
        Width = 42
        Height = 12
        Caption = 'Emiss'#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLSystemInfo3: TRLSystemInfo
        Left = 672
        Top = 18
        Width = 64
        Height = 12
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLSystemInfo4: TRLSystemInfo
        Left = 672
        Top = 2
        Width = 32
        Height = 12
        Alignment = taCenter
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        Info = itPageNumber
        ParentFont = False
      end
      object RLLabel36: TRLLabel
        Left = 3
        Top = 53
        Width = 35
        Height = 12
        Caption = 'Material'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -9
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel37: TRLLabel
        Left = 544
        Top = 51
        Width = 23
        Height = 14
        Caption = 'Qtd.'
      end
      object RLLabel38: TRLLabel
        Left = 672
        Top = 51
        Width = 68
        Height = 14
        Caption = 'Qtd.Pendente'
      end
      object RLLabel39: TRLLabel
        Left = 584
        Top = 51
        Width = 70
        Height = 14
        Caption = 'Qtd.Devolvida'
      end
      object RLDraw6: TRLDraw
        Left = 0
        Top = 66
        Width = 742
        Height = 2
        Align = faBottom
        DrawKind = dkLine
      end
    end
  end
end
