object fRelPedido2: TfRelPedido2
  Left = 333
  Top = 38
  Width = 874
  Height = 666
  Caption = 'Pedido'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
  object RLReport1: TRLReport
    Left = 48
    Top = 8
    Width = 794
    Height = 1123
    DataSource = DMCadPedido.dsPedidoImp
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    Margins.LeftMargin = 7.000000000000000000
    Margins.TopMargin = 7.000000000000000000
    Margins.RightMargin = 7.000000000000000000
    Margins.BottomMargin = 7.000000000000000000
    RecordRange = rrCurrentOnly
    ShowProgress = False
    BeforePrint = RLReport1BeforePrint
    object RLSubDetail1: TRLSubDetail
      Left = 26
      Top = 26
      Width = 742
      Height = 623
      DataSource = DMCadPedido.dsPedidoImp
      object RLBand1: TRLBand
        Left = 0
        Top = 0
        Width = 742
        Height = 159
        BandType = btHeader
        BeforePrint = RLBand1BeforePrint
        object RLDraw8: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 43
          Align = faTop
        end
        object RLLabel4: TRLLabel
          Left = 3
          Top = 26
          Width = 88
          Height = 15
          Caption = 'Pedido Interno:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel7: TRLLabel
          Left = 591
          Top = 4
          Width = 70
          Height = 15
          Caption = 'Dt.Emiss'#227'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel8: TRLLabel
          Left = 247
          Top = 26
          Width = 87
          Height = 15
          Caption = 'Pedido Cliente:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText2: TRLDBText
          Left = 667
          Top = 4
          Width = 71
          Height = 15
          DataField = 'DTEMISSAO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText3: TRLDBText
          Left = 336
          Top = 26
          Width = 100
          Height = 15
          DataField = 'PEDIDO_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDraw2: TRLDraw
          Left = 0
          Top = 42
          Width = 742
          Height = 66
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel10: TRLLabel
          Left = 26
          Top = 45
          Width = 35
          Height = 12
          Caption = 'Cliente:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel11: TRLLabel
          Left = 16
          Top = 57
          Width = 45
          Height = 12
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel12: TRLLabel
          Left = 31
          Top = 68
          Width = 30
          Height = 12
          Caption = 'Bairro:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel13: TRLLabel
          Left = 26
          Top = 81
          Width = 35
          Height = 12
          Caption = 'Cidade:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText4: TRLDBText
          Left = 65
          Top = 45
          Width = 51
          Height = 11
          DataField = 'NOME_CLI'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText6: TRLDBText
          Left = 65
          Top = 68
          Width = 83
          Height = 12
          DataField = 'BAIRRO_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel19: TRLLabel
          Left = 433
          Top = 45
          Width = 45
          Height = 12
          Caption = 'Telefone :'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel20: TRLLabel
          Left = 455
          Top = 57
          Width = 23
          Height = 12
          Caption = 'Cep:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel21: TRLLabel
          Left = 443
          Top = 68
          Width = 35
          Height = 12
          Caption = 'Estado:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel23: TRLLabel
          Left = 428
          Top = 93
          Width = 50
          Height = 12
          Caption = 'Inscr. Est.:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel24: TRLLabel
          Left = 447
          Top = 81
          Width = 31
          Height = 12
          Caption = 'CNPJ:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText11: TRLDBText
          Left = 508
          Top = 45
          Width = 73
          Height = 12
          DataField = 'FONE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText12: TRLDBText
          Left = 482
          Top = 57
          Width = 66
          Height = 12
          DataField = 'CEP_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText13: TRLDBText
          Left = 482
          Top = 68
          Width = 16
          Height = 12
          DataField = 'UF'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText14: TRLDBText
          Left = 482
          Top = 81
          Width = 96
          Height = 12
          DataField = 'CNPJ_CPF_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText15: TRLDBText
          Left = 482
          Top = 93
          Width = 99
          Height = 12
          DataField = 'INSCR_EST_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel25: TRLLabel
          Left = 598
          Top = 45
          Width = 22
          Height = 12
          Caption = 'Fax:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText17: TRLDBText
          Left = 648
          Top = 45
          Width = 64
          Height = 12
          DataField = 'FAX_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel30: TRLLabel
          Left = 173
          Top = 145
          Width = 69
          Height = 11
          Caption = 'Produto/Marca'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel32: TRLLabel
          Left = 27
          Top = 145
          Width = 51
          Height = 11
          Caption = 'Refer'#234'ncia'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel33: TRLLabel
          Left = 4
          Top = 145
          Width = 22
          Height = 11
          Caption = 'Item'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel34: TRLLabel
          Left = 686
          Top = 145
          Width = 54
          Height = 11
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Pr.Total'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel35: TRLLabel
          Left = 646
          Top = 145
          Width = 38
          Height = 11
          Alignment = taCenter
          Caption = 'Pr.Unit.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel37: TRLLabel
          Left = 138
          Top = 145
          Width = 28
          Height = 11
          Alignment = taCenter
          Caption = 'Qtde.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText20: TRLDBText
          Left = 93
          Top = 25
          Width = 62
          Height = 16
          AutoSize = False
          DataField = 'NUM_PEDIDO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel18: TRLLabel
          Left = 11
          Top = 94
          Width = 50
          Height = 12
          Alignment = taRightJustify
          Caption = 'Email NFe:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText7: TRLDBText
          Left = 482
          Top = 45
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object rlEndereco: TRLLabel
          Left = 65
          Top = 57
          Width = 368
          Height = 12
          AutoSize = False
          Caption = 'Endere'#231'o:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText31: TRLDBText
          Left = 2
          Top = 1
          Width = 308
          Height = 14
          AutoSize = False
          DataField = 'NOME_FILIAL'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText37: TRLDBText
          Left = 65
          Top = 81
          Width = 83
          Height = 12
          DataField = 'CIDADE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText38: TRLDBText
          Left = 65
          Top = 94
          Width = 98
          Height = 12
          DataField = 'EMAIL_NFE_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText39: TRLDBText
          Left = 622
          Top = 45
          Width = 24
          Height = 12
          Alignment = taCenter
          AutoSize = False
          DataField = 'DDD_FAX_CLIENTE'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw12: TRLDraw
          Left = 0
          Top = 107
          Width = 742
          Height = 32
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
        end
        object RLLabel9: TRLLabel
          Left = 77
          Top = 122
          Width = 54
          Height = 14
          Caption = 'Vendedor:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText28: TRLDBText
          Left = 134
          Top = 124
          Width = 513
          Height = 12
          AutoSize = False
          DataField = 'NOME_VENDEDOR'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel28: TRLLabel
          Left = 104
          Top = 145
          Width = 22
          Height = 11
          Alignment = taCenter
          Caption = 'Uni.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel5: TRLLabel
          Left = 9
          Top = 108
          Width = 122
          Height = 14
          Caption = 'Condi'#231#227'o de Pagamento:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDBText9: TRLDBText
          Left = 134
          Top = 110
          Width = 513
          Height = 12
          AutoSize = False
          DataField = 'NOME_CONDPGTO'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel1: TRLLabel
          Left = 596
          Top = 26
          Width = 65
          Height = 15
          Caption = 'Dt.Entrega:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDBText1: TRLDBText
          Left = 667
          Top = 26
          Width = 71
          Height = 15
          DataField = 'DTENTREGA'
          DataSource = DMCadPedido.dsPedidoImp
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLLabel6: TRLLabel
          Left = 335
          Top = 2
          Width = 172
          Height = 14
          Caption = 'Relat'#243'rio de Confer'#234'ncia do Pedido'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLLabel15: TRLLabel
          Left = 489
          Top = 145
          Width = 57
          Height = 11
          Caption = 'Localiza'#231#227'o'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object RLDraw7: TRLDraw
          Left = 0
          Top = 158
          Width = 742
          Height = 1
          Align = faBottom
          DrawKind = dkLine
          Pen.Style = psDot
        end
        object RLLabel17: TRLLabel
          Left = 616
          Top = 145
          Width = 24
          Height = 11
          Caption = 'V.IPI'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
      object RLSubDetail2: TRLSubDetail
        Left = 0
        Top = 159
        Width = 742
        Height = 98
        DataSource = DMCadPedido.dsPedidoImp_Itens
        object RLBand2: TRLBand
          Left = 0
          Top = 0
          Width = 742
          Height = 16
          BeforePrint = RLBand2BeforePrint
          object RLDBText18: TRLDBText
            Left = 1
            Top = 1
            Width = 24
            Height = 12
            Alignment = taCenter
            AutoSize = False
            Borders.Sides = sdCustom
            Borders.DrawLeft = False
            Borders.DrawTop = False
            Borders.DrawRight = False
            Borders.DrawBottom = False
            DataField = 'ITEM'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText22: TRLDBText
            Left = 139
            Top = 1
            Width = 22
            Height = 12
            Alignment = taRightJustify
            DataField = 'QTD'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText29: TRLDBText
            Left = 25
            Top = 1
            Width = 79
            Height = 12
            AutoSize = False
            DataField = 'REFERENCIA'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object rlPreco: TRLLabel
            Left = 640
            Top = 1
            Width = 46
            Height = 12
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Pre'#231'o'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object rlVlrTotal: TRLLabel
            Left = 687
            Top = 1
            Width = 54
            Height = 12
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Vlr.Total'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText49: TRLDBText
            Left = 100
            Top = 1
            Width = 30
            Height = 12
            Alignment = taCenter
            AutoSize = False
            DataField = 'UNIDADE'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText5: TRLDBText
            Left = 487
            Top = 1
            Width = 111
            Height = 12
            AutoSize = False
            DataField = 'LOCALIZACAO'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLMemo2: TRLMemo
            Left = 171
            Top = 1
            Width = 315
            Height = 12
            Behavior = [beSiteExpander]
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText8: TRLDBText
            Left = 599
            Top = 1
            Width = 40
            Height = 12
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_IPI'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand4: TRLBand
          Left = 0
          Top = 47
          Width = 742
          Height = 29
          BandType = btSummary
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          BeforePrint = RLBand4BeforePrint
          object RLDraw6: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 2
            HelpContext = 2
            Align = faTop
            DrawKind = dkLine
            Pen.Style = psDot
          end
          object RLLabel45: TRLLabel
            Left = 559
            Top = 15
            Width = 98
            Height = 11
            Caption = 'Vlr.Total de Pedidos:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText34: TRLDBText
            Left = 683
            Top = 15
            Width = 55
            Height = 11
            Alignment = taRightJustify
            DataField = 'VLR_TOTAL'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText10: TRLDBText
            Left = 317
            Top = 15
            Width = 39
            Height = 11
            DataField = 'VLR_IPI'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel22: TRLLabel
            Left = 280
            Top = 15
            Width = 34
            Height = 11
            Caption = 'Vlr.IPI:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel26: TRLLabel
            Left = 14
            Top = 15
            Width = 106
            Height = 11
            Caption = 'Vlr. Icms Substitui'#231#227'o:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText16: TRLDBText
            Left = 123
            Top = 15
            Width = 81
            Height = 11
            DataField = 'VLR_ICMSSUBST'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel27: TRLLabel
            Left = 28
            Top = 3
            Width = 92
            Height = 11
            Caption = 'Vlr. Total Produtos:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText19: TRLDBText
            Left = 123
            Top = 3
            Width = 59
            Height = 11
            DataField = 'VLR_ITENS2'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel29: TRLLabel
            Left = 249
            Top = 3
            Width = 65
            Height = 11
            Caption = 'Vlr.Desconto:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText21: TRLDBText
            Left = 317
            Top = 3
            Width = 79
            Height = 11
            DataField = 'VLR_DESCONTO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLLabel31: TRLLabel
            Left = 600
            Top = 3
            Width = 57
            Height = 11
            Caption = 'Vlr.Entrada:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object RLDBText23: TRLDBText
            Left = 660
            Top = 3
            Width = 78
            Height = 11
            Alignment = taRightJustify
            AutoSize = False
            DataField = 'VLR_ADIANTAMENTO'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
          end
        end
        object RLBand14: TRLBand
          Left = 0
          Top = 30
          Width = 742
          Height = 17
          BandType = btSummary
          BeforePrint = RLBand14BeforePrint
          object RLDraw16: TRLDraw
            Left = 0
            Top = 0
            Width = 742
            Height = 18
            Align = faTop
          end
          object RLLabel70: TRLLabel
            Left = 12
            Top = 2
            Width = 134
            Height = 12
            Caption = 'Vlr. ICMS. Combate a Pobreza:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel71: TRLLabel
            Left = 261
            Top = 2
            Width = 97
            Height = 12
            Caption = 'Vlr. ICMS UF Destino:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText61: TRLDBText
            Left = 148
            Top = 2
            Width = 73
            Height = 12
            DataField = 'VLR_ICMS_FCP'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText60: TRLDBText
            Left = 361
            Top = 2
            Width = 96
            Height = 12
            DataField = 'VLR_ICMS_UF_DEST'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLLabel72: TRLLabel
            Left = 501
            Top = 2
            Width = 93
            Height = 12
            Caption = 'Vlr. ICMS UF Remet:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object RLDBText62: TRLDBText
            Left = 595
            Top = 2
            Width = 103
            Height = 12
            DataField = 'VLR_ICMS_UF_REMET'
            DataSource = DMCadPedido.dsPedidoImp
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object RLBand6: TRLBand
          Left = 0
          Top = 16
          Width = 742
          Height = 14
          BeforePrint = RLBand6BeforePrint
          object RLDBText24: TRLDBText
            Left = 171
            Top = -2
            Width = 22
            Height = 12
            DataField = 'OBS'
            DataSource = DMCadPedido.dsPedidoImp_Itens
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -9
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object RLBand7: TRLBand
        Left = 0
        Top = 257
        Width = 742
        Height = 36
        BandType = btSummary
        IntegralHeight = False
        BeforePrint = RLBand7BeforePrint
        object RLDraw3: TRLDraw
          Left = 0
          Top = 0
          Width = 742
          Height = 36
          Align = faClient
        end
        object RLLabel46: TRLLabel
          Left = 7
          Top = 2
          Width = 79
          Height = 14
          Caption = 'Observa'#231#245'es:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold, fsUnderline]
          ParentFont = False
        end
        object RLMemo1: TRLMemo
          Left = 7
          Top = 17
          Width = 705
          Height = 16
          Behavior = [beSiteExpander]
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          IntegralHeight = True
          ParentFont = False
        end
      end
      object RLBand3: TRLBand
        Left = 0
        Top = 293
        Width = 742
        Height = 36
        BandType = btSummary
        object RLLabel16: TRLLabel
          Left = 339
          Top = 21
          Width = 53
          Height = 12
          Alignment = taRightJustify
          Caption = 'Conferente:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -9
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object RLDraw4: TRLDraw
          Left = 396
          Top = 32
          Width = 242
          Height = 2
          DrawKind = dkLine
        end
      end
    end
    object RLBand5: TRLBand
      Left = 26
      Top = 649
      Width = 742
      Height = 17
      BandType = btFooter
      object RLLabel2: TRLLabel
        Left = 501
        Top = 4
        Width = 36
        Height = 10
        Caption = 'Imp. Data:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -8
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLLabel3: TRLLabel
        Left = 629
        Top = 4
        Width = 21
        Height = 10
        Caption = 'Hora:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -8
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLSystemInfo1: TRLSystemInfo
        Left = 550
        Top = 2
        Width = 62
        Height = 12
        Alignment = taCenter
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -8
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object RLSystemInfo2: TRLSystemInfo
        Left = 659
        Top = 3
        Width = 62
        Height = 11
        Alignment = taCenter
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -8
        Font.Name = 'Arial'
        Font.Style = []
        Info = itHour
        ParentFont = False
      end
    end
  end
end
